### ISSUE TITLE
mint-x-icons: Education category missing

### ISSUE THREAD

**Issue by Harry-W-Haines-III** [linuxmint/mint22-beta#1]
This is for the Cinnamon Edition.  There is a missing icon in the Education Category in the Start Menu when you switch to the Minx-X icons.  See the screen captures below.
Here is the default Mint-Y Sand.

![mint-y-sand](https://github.com/linuxmint/mint22-beta/assets/45599505/28319cf4-c434-4f86-9517-d4a63455654a)

Here is Mint-L Yellow
![mint-l-yellow](https://github.com/linuxmint/mint22-beta/assets/45599505/fe2a5ee2-a3a9-4880-b9ff-26f72a576579)

Here is Mint-X Yellow
![mint-x-yellow](https://github.com/linuxmint/mint22-beta/assets/45599505/3e9f05c3-e620-4a6d-8cd2-14e767624ad0)

**Comment by clefebvre** [comment]
Fixed in mint-x-icons 1.7.0 (same icon as science for now, until we get a new one).
