### ISSUE TITLE
[Xfce] "Appearance" program has a major multi-second lag/delay between the window appearing and being able to interact with it

### ISSUE THREAD

**Issue by NintendoManiac64** [linuxmint/mint22-beta#100]
Really simple—in Mint 22 Xfce (tested via the live ISO), simply open the "Appearance" program and try to interact with the window right when it appears.

For whatever reason, there's like a 5 to 10 second lag or delay before you can actually interact with the window content.

I can at least say this didn't happen on Xubuntu 24.04 so I don't think it's an Xfce thing.

**UPDATE**:
> I just did some farther testing with older versions of Mint Xfce and it turns out this issue was actually introduced with Mint Xfce 21.3...
> 
> But Mint Xfce 21.2 does _not_ have this issue despite having just as many amount of styles (67) and icons (71) as both Mint Xfce 21.3 and 22(.0) beta (actually the latter as one _fewer_ icon set), so I don't think that has anything to do with this issue.

**Comment by RoyJubilado** [comment]
The reason seems simple: too many themes that ship with LM natively. If you remove them, 'Appearance' should launch (much) faster. Xubuntu and other Xfce-based distros don't come with too many themes preinstalled and there is no lag. I guess Cinnamon could benefit from their reduction as well.

**Comment by RoyJubilado** [comment]
Remove some icon sets as well. Then the appearance module should launch faster.

**Comment by NintendoManiac64** [comment]
I just did some farther testing with older versions of Mint Xfce and it turns out this issue was actually introduced with Mint Xfce 21.3...

But Mint Xfce 21.2 does *not* have this issue despite having just as many amount of styles (67) and icons (71) as both Mint Xfce 21.3 and 22(.0) beta (actually the latter as one *fewer* icon set), so I don't think that has anything to do with this issue.

**Comment by clefebvre** [comment]
This is upstream from us and should be reported with Xfce. The tool probably generates cache or thumbnails/previews for the various icon themes., it might just need to do so asynchronously and show a loading page while doing so. This should be a feature request for Xfce.
