### ISSUE TITLE
"Medium" and "Full" font hinting settings seem to be broken

### ISSUE THREAD

**Issue by NintendoManiac64** [linuxmint/mint22-beta#101]
Simply put, in at least both Cinnamon and Xfce live ISOs of Mint 22 beta, the font hinting options for "medium" and "full" seem to be broken.

With anti-aliasing enabled, "medium" and "full" look extremely similar to hinting set to "none" (I'd say it's identical but I got different checksums for the resulting screenshots, though "medium" and "full" had identical checksums relative to one-another)

With anti-aliasing disabled, "medium" and "full" look extremely similar to hinting set to "low" (I did not think to compare the checksums of the screenshots, but the issue is much more noticeable without anti-aliasing especially with "full" hinting)

I can't help but wonder if this is due to #9 considering that this definitely didn't exist on older versions as someone that uses hinting set to "full" which is how I quickly noticed it

　
**UPDATE**: Screenshots! (zoomed in 200% to make sure everyone can see the individual pixels)

### Mint Cinnamon 22(.0) beta (click image for full-size)
![full](https://github.com/linuxmint/mint22-beta/assets/11896003/f9504557-1af0-4dfe-980a-76bdad9cd825)
![medium](https://github.com/linuxmint/mint22-beta/assets/11896003/59a6fdba-39b9-49fb-9a03-91bbc88eedb6)
![slight](https://github.com/linuxmint/mint22-beta/assets/11896003/a1f90091-ccaa-4073-9812-97ec3d9a9ce0)
![none](https://github.com/linuxmint/mint22-beta/assets/11896003/990053cc-23a2-47b8-b6c7-84434090051f)

　
### Mint Cinnamon 21.3 (click image for full-size)
![full](https://github.com/linuxmint/mint22-beta/assets/11896003/94169863-8ed5-4bc9-9c34-165dd9e046ce)
![medium](https://github.com/linuxmint/mint22-beta/assets/11896003/76634a04-fc79-415c-8b1d-a2b243cab65a)
![slight](https://github.com/linuxmint/mint22-beta/assets/11896003/3c5df4f4-8da9-4898-89bd-36c81ba6bbf9)
![none](https://github.com/linuxmint/mint22-beta/assets/11896003/4a44691a-92a4-4768-a0bb-709f5e852999)

**Comment by Harry-W-Haines-III** [comment]
There is a work around.  This will install the 'fuller' looking fonts that have been in use for years.  https://discourse.ubuntu.com/t/ubuntu-24-04-lts-noble-numbat-release-notes/39890#updated-ubuntu-font

**Comment by NintendoManiac64** [comment]
Font thinness is not the issue I am describing though—when anti-aliasing is disabled and not using display scaling, your font in the likes of Nemo and/or Thunar is still just a single pixel wide in both the current and older versions of Mint, yet the non-anti-aliased text looks particularly ugly.

Perhaps I should provide some screenshots since I suppose not everyone is using a non-HiDPI screen and therefore may not be able to see the individual pixels—the `~/` directory set to "list" view provides a pretty easy example of the difference.

**EDIT**: Added screenshots that also have 200% zoom pre-applied in order to make sure everyone can see the individual pixels (be sure to click them for full size).

**Comment by clefebvre** [comment]
Check https://www.freedesktop.org/wiki/Specifications/XSettingsRegistry/.

These settings are XSettings, the desktop is just expected to let the user change the setting and give the system the appropriate value. This is usually done by a setting daemon in MATE/Cinnamon/Xfce etc..

After that, I suppose it's fontconfig or whatever which uses the information to render things differently. Some fonts might look different depending on the values, others might not.

From a desktop point of view, our role is simply to expose these settings though.
