### ISSUE TITLE
iso: Add fonts-noto-core to software selection

### ISSUE THREAD

**Issue by archisman-panigrahi** [linuxmint/mint22-beta#102]
I am a native speaker of Bangla/Bengali language, which is a widely spoken language in India and Bangladesh.

I have some files whose names are saved in Bangla. 
In Mint 22 these file names are displayed with some boxes. It worked out of the box in Mint 21.

The workaround is to install `fonts-noto-core`, which supports all major Indic languages.

**Comment by Harry-W-Haines-III** [comment]
https://www.linuxmint.com/rel_wilma_whatsnew.php
"In addition, the following languages do not require an Internet connection since their language packs are present on the ISO image: English, German, Spanish, French, Russian, Portuguese, Dutch and Italian."  For other languages out of the box you will need to install a language pack.

**Comment by archisman-panigrahi** [comment]
My proposal is to bring back out of the box support for all major languages around the world. 
Mint 21 had that feature. So does Ubuntu 24.04.

It is not necessary to install language packs.

I only want `fonts-noto-core` to be installed so that the fonts are displayed correctly.

**Comment by clefebvre** [comment]
Can you give an example filename to test?

**Comment by archisman-panigrahi** [comment]
I am uploading an example file to google drive (uploading to github would rename the filename to English)

https://drive.google.com/file/d/1G0icPJpn4DpRDSm2OeijuBJ6PKwvWxvD/view?usp=sharing

The filename should look like this 

![image](https://github.com/user-attachments/assets/cdbff65a-db6e-4aa2-a262-fedcd8058d90)


The contents should look like this

![image](https://github.com/user-attachments/assets/21068bb3-baf6-4567-a389-37944dbdcb23)

**Comment by clefebvre** [comment]
আমি বাংলায় গান গাই

**Comment by archisman-panigrahi** [comment]
Looks good. Does the filename also look like this?  https://private-user-images.githubusercontent.com/3063132/348269773-cdbff65a-db6e-4aa2-a262-fedcd8058d90.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA3OTc0OTEsIm5iZiI6MTcyMDc5NzE5MSwicGF0aCI6Ii8zMDYzMTMyLzM0ODI2OTc3My1jZGJmZjY1YS1kYjZlLTRhYTItYTI2Mi1mZWRjZDgwNThkOTAucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDcxMiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA3MTJUMTUxMzExWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MWQzNDM4ZTE4YTI0MTE1OTdlYWRlOTJiZWI2OTNmNmQyYmNiN2RlMmEzZDE4Y2U0NzA2MDM0YTQ3M2UwZWRlNiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.FIwTyNEt7ZCo3A0DHRhFODnu1aFUWF_u9kVZ17_CBtY

**Comment by clefebvre** [comment]
fonts-noto-core added to next ISOs.
