### ISSUE TITLE
gscan2pdf not running

### ISSUE THREAD

**Issue by Qynoc** [linuxmint/mint22-beta#103]
Linux Mint 22 Beta running with kvm/qemu

gscan2pdf version 2.13.2-1 installed via software manager does not start and the output when running from command line is: 
given is deprecated at /usr/share/perl5/Gscan2pdf/Scanner/Options.pm line 241.
when is deprecated at /usr/share/perl5/Gscan2pdf/ Scanner/Options.pm line 242.
…...
Error: cannot close /etc/upstream-release

The installed Perl version is 5.38.2-3.2build2.
Found the information that gscan2pdf version 2.13.3.-1 should have fixed the problem with the deprecated „given“ and „when“.

Installed gscan2pdf 2.13.3-1 from https:\\sourceforge.net/projects/gscan2pdf/ .

The „given“ and „when“ errors disappeared but „Error: cannot close /etc/upstream-release“ is still there.

I don’t know if it is a Mint or gscan2pdf problem. Gscan2pdf runs in Mint 21.3 without any problem.

**Comment by clefebvre** [comment]
`/etc/upstream-release` is a directory, not a file.
The file is in `/etc/upstream-release/lsb-release`.

![image](https://github.com/linuxmint/mint22-beta/assets/1138515/12d1175e-1d91-4e71-a489-336c9aee6bcb)

Looking at the gscan2pdf code I don't see where it reads this though, it's probably in a library it uses? Either way, this is an issue in gscan2pdf. We're happy to help if they want to get in touch with us and get more information.

They can reach us at https://matrix.to/#/#linuxmint-dev:matrix.org if needed.

**Comment by Qynoc** [comment]
There is a fix for gscan2pdf. see https://sourceforge.net/p/gscan2pdf/bugs/430/
