### ISSUE TITLE
GNOME Terminal menubar does not respect Mint-L themes

### ISSUE THREAD

**Issue by contrarybaton60** [linuxmint/mint22-beta#105]
![VirtualBox_LM 22_06_07_2024_10_29_12](https://github.com/linuxmint/mint22-beta/assets/110365948/36321c98-e38e-4a8e-a7c3-ddc1e7fd313f)

**Comment by clefebvre** [comment]
That's just a preset to make it Dark by default. It's a light app otherwise.

In the settings, switch it to Theme Variant -> Default.

![image](https://github.com/linuxmint/mint22-beta/assets/1138515/0ac1f8dd-71e5-424d-b7ef-41f02f62a817)

**Comment by contrarybaton60** [comment]
the gtk-dark.css file is not in the light variants of Mint-L (it's also like that in 21.3) I don't know if you consider that a bug or not. It would be better if the default option in GNOME Terminal is the default, in my opinion.
