### ISSUE TITLE
Available nVidia Proprietary Display Driver Is Out Of Date?

### ISSUE THREAD

**Issue by JesseLeePalser** [linuxmint/mint22-beta#106]
Hi,

Why is the available nVidia proprietary display driver so out of date?
On v21.3 there were several newer ones?

Jesse Lee

**Comment by Harry-W-Haines-III** [comment]
Hello Jesse:  There is a common misconception about the the numbering of the Nvidia drivers and which ones you should be using on your particular video card.

Open a terminal window and type the following command: "ubuntu-drivers devices"
It should give you the driver for your card that matches the driver manager.  If you take a look at the package nvidia-driver-535_535.183.01-0ubuntu0.24.04.1_amd64.deb with the archive manager, you will see that it is quite recent -- May 30, 2024.

Here is what the change log shows:

nvidia-graphics-drivers-535 (535.183.01-0ubuntu0.24.04.1) noble; urgency=medium
  * New upstream release (LP: #2067597)
 -- Eduard de Vidal Flores <eduard.de.vidal.flores@canonical.com>  Thu, 30 May 2024 12:53:28 +0200

The higher version numbers you see are for more recent cards.  For 80% of the Nvidia cards out there, the 535 driver will give coverage.

**Comment by JesseLeePalser** [comment]
Ok, running a two year old nVidia 3060 RTX 12GB

**Comment by Harry-W-Haines-III** [comment]
So what does the driver manager recommend?

**Comment by JesseLeePalser** [comment]
v535

**Comment by Harry-W-Haines-III** [comment]
Its also common for distros to use a different numbering system than on the Nvidia driver website so its hard to make an apples to apples comparison.  Ubuntu + Mint do all the work for you.  Its quite tricky to install drivers manually from the Nvidia website.  If you are satisfied with this answer, please close out the issue.  Thanks.

**Comment by JesseLeePalser** [comment]
Driver up to date
