### ISSUE TITLE
LM22xfce/beta: removing "mintchat" does not remove start-menu entry (Matrix)

### ISSUE THREAD

**Issue by Rhinou** [linuxmint/mint22-beta#107]
Package "mintchat" removed by Software Manager, but orphaned entry for "Matrix" (online chat) remains in start-menu (LM->Internet). After trying to run it complains:

> Failed to execute command "mintchat".
> Failed to execute child process "mintchat" (No such file or directory)
> Close

**Comment by WhosyVox** [comment]
It looks like this might be due to the fact the desktop file is listed in conffiles: uninstalling the package doesn't delete its desktop entry.

I don't know what the best way to resolve this might be; maybe have that file deleted in an uninstall script?

**Comment by clefebvre** [comment]
The package is only there to create the webapp for new users.

If you want to remove the webapp (and thus the menu item), open webapp-manager and delete the webapp.

**Comment by LAP47** [comment]
> The package is only there to create the webapp for new users.
> 
> If you want to remove the webapp (and thus the menu item), open webapp-manager and delete the webapp.

How do we add the matrix entry to the menu if it's not already there after installing LM22?

**Comment by clefebvre** [comment]
It's added via etc/skel, it's part of mintchat.

**Comment by LAP47** [comment]
> It's added via etc/skel, it's part of mintchat.

So is there a way to add it?
