### ISSUE TITLE
Multiple entries for a single scanning-device if wireless connected

### ISSUE THREAD

**Issue by MenthaSuaveolens** [linuxmint/mint22-beta#109]
The hp3630 wireless printer/scanner is detected automatically (Linux Mint 22 Cinnamon). When opening simplescan, the app shows "HP Deskjet 3630 Series [600231]". However trying to scan fails: "Document Feeder Empty" (See log simple-scan-SaneStatusNoDocs.log). The scanner is listed up 3 times as available devices:  "HP Deskjet 3630 Series [600231]", "HP Deskjet 3630 Series" and "eSCL HP Deskjet 3630 Series [600231]". When selecting one the bottom two scanners, the scanner is working ok. After that only the two bottom scanners are listed up. This is very confusing.
![ScanDevices](https://github.com/linuxmint/mint22-beta/assets/47174957/3c572b0c-7b36-4829-bc6f-468b2dbb8545)
[simple-scan-SaneStatusNoDocs.log](https://github.com/user-attachments/files/16118685/simple-scan-SaneStatusNoDocs.log)

**Comment by MiZoG99** [comment]
Running the command **scanimage -L** in a terminal returns two entries for the same scanner bundled with an all-in-one Epson WF-3820

```
device 'escl:https://192.168.1.11:443' is a Epson WF-3820 Series platen,adf scanner
device 'airscan:e0:EPSON WF-3820 Series' is a eSCL EPSON WF-3820 Series ip=192.168.1.11
```

The same results are shown by simple-scan.
There are 2 backends available for this scanner: sane-airscan and sane-escl in my system,
hence the two entries for the same device.

**Comment by clefebvre** [comment]
That's it exactly. I agree it's confusing.

It's upstream from us. It's a consequence of moving towards driverless printing.

I'd suggest reporting the bug towards scanimage and/or image-scan. These could be displayed in a more explicit way.
