### ISSUE TITLE
thunderbird: Unsupported version warning

### ISSUE THREAD

**Issue by MiZoG99** [linuxmint/mint22-beta#11]
Not a bug but still an "issue"

Running Thunderbird (now packaged by Mint team) for a first time I'm greeted with this warning:
![ThunderbirdWarning](https://github.com/linuxmint/mint22-beta/assets/137620210/778e9949-63b4-4fc5-b518-f6ceccb6ee60)

Warning persists after setting up an email account and launching the app several times. It is the first thing I see when I open Thunderbird since it is set by default start page Thunderbird setting.

Other distros seem to default to 115.x channel which apparently is treated as "supported" by Thunderbird devs.
Is shipping the latest build a deliberate choice? If yes, then how about change the default start page from
chrome://messenger/content/release-candidate.html to something Linux Mint-related?

**Comment by securerootd** [comment]
I think we should be following/packaging Thunderbird stable instead of the beta releases? 
It should be 115.12.2
127.x has been superseded by 128.x which is still in beta

**Comment by clefebvre** [comment]
Fixed with 128.0esr.
