### ISSUE TITLE
Xfce: some system tray icons don't scale

### ISSUE THREAD

**Issue by RoyJubilado** [linuxmint/mint22-beta#110]
Some Xfce system tray icons don't resize. The Notification, Power Manager and PulseAudio plugin icons resize as expected, but others /Network connection, Notes, etc/  don't. It result's in visual discrepancy when setting higher size values, the icons affected by the bug sit too tightly to each other as well.
Used the only way to resize the panel system tray icons known to me, eg. via the panel preferences widget.
In Mint 21.3 Xfce resizing worked flawlessly, same for Xubuntu 24.04.

**Comment by mtwebster** [comment]
You can specify the size now in the xapp tray applet's right-click menu now, for both symbolic and color icons. This was done because we deliberately wanted the tray icons slightly smaller in the default layout.
