### ISSUE TITLE
Feature Request for Live Media: Assistant for selecting language, keyboard and internet connection on startup

### ISSUE THREAD

**Issue by atarax42** [linuxmint/mint22-beta#111]
I think it would raise the ease to use the LM live media especially for first-timers, if an assistant would pop up after startup to help selecting the system language, the appropriate keyboard layout and to establish an internet connection, because in my experience this is what you pretty much always will want to do first (unless you want to stay with the default language setting). And these settings are spread over individual menu entries an unexperienced user will have to find first. I guess many first-timers will feel much more welcome when taken by the hand this way.

For example a German newbie might want to establish an internet connection first. But this repeatedly fails because that person is using unknowingly the wrong keyboard layout (Y and Z are switched on German keyboards) and this is unnoticed because the password entry normaly does not reveal what keys have been pressed.

I have seen such assistant on other distros and really liked it.

I don't know if this is an issue in its own right, but when selecting another language in the respective settings dialog (like switching from German to English) I confirm my changes but the language of the desktop (menus, dialogs etc) remains the same. That is true for the live media and for an installed system... (Edit: the last statement is not true, it works on live media and an installed system _after a new login_, this should be notified, I think)

**Comment by fredcw** [comment]
The language and keyboard is set during installation so why would you need to do it afterwards?

**Comment by atarax42** [comment]
The live media user might have an extensive look around the system _before_ deciding to install it. Or he/she might use the live media for any other purpose but for installation.

**Comment by fredcw** [comment]
Sorry, I misread what you said. Yes, ubuntu does this, it allows you to select a language before the live media desktop appears.

**Comment by clefebvre** [comment]
Thank you for this recommendation.
