### ISSUE TITLE
blueman: Double clicking icon makes it hang for ~15 seconds then error message

### ISSUE THREAD

**Issue by Average-GH-Enjoyer** [linuxmint/mint22-beta#113]
After closing Blueman-Manager for the first time using the X button, it minimizes to a tray icon. However, I've noticed a strange bug. When I open it with a single click, the Blueman Manager window reappears. But if I double-click it, I get a "Blueman-Manager not responding" message, followed by this error:
![blueman](https://github.com/linuxmint/mint22-beta/assets/34612481/338c604e-ef81-4580-b1fb-ce1f138fbce3)

Despite the error message, the Blueman-Manager seems to work fine afterwards.

**Comment by clefebvre** [comment]
Confirmed. I can reproduce this as well.

This is upstream from us and should be reported to Blueman directly. https://github.com/blueman-project/blueman/issues
