### ISSUE TITLE
Backport gtk4 file picker?

### ISSUE THREAD

**Issue by Qronikarz** [linuxmint/mint22-beta#115]
After many years GTK4 finally added the file picker that has bigger thumbnails and grid view.

However Mint stays on GTK3 and downgraded the apps back to it so the new file picker can't be used.
Here's how it looks when you upload files with Firefox:
![mintfilepicker](https://github.com/linuxmint/mint22-beta/assets/84787215/daffe255-abb6-46a5-b642-b66caab66374)
And here's how it looks if you upgrade the programs that were downgraded: (screenshot taken from forum post)
![Screenshot-from-2024-07-02-05-42-42](https://github.com/linuxmint/mint22-beta/assets/84787215/3127d0cc-7795-4481-9955-0c7f44340d46)

So now the question. Can the new file picker be somehow backported to GTK3? Or just make it open the Nemo in some mode where you can select files you wanted to choose?

Links:
forum post - https://forums.linuxmint.com/viewtopic.php?p=2489176#p2489176
reddit post (2 years ago)- https://www.reddit.com/r/linux/comments/yab9ux/gtk_file_picker_meme_is_finally_dead_after_18/

I'll convert it into discussion in case it's not the place for that, but the docs state that ideas can also be posted and it would be a nice feature to have in Mint 22.

**Comment by JosephMcc** [comment]
> Can the new file picker be somehow backported to GTK3

No. The only way this would really be possible would be for Mint to maintain a their own version of Gtk3 and write this code themselves.
