### ISSUE TITLE
Use uixfce4-2-0 beyond 4.18.5 for fixing super key menu pop up

### ISSUE THREAD

**Issue by Watynecc** [linuxmint/mint22-beta#117]
Why ? because in cinnamon when you press the super key nothing happen. I believe the DE wait the second input or the release of the key before acting but for some reason the beta of LM xfce and even the stable version got this weird behavior with the super key since it doesn't wait before doing anything (so the startup menu show up while doing Win + E for example).

I found out that the bug was related to the uixfce4 package and they fixed in 4.18.5  (link : https://gitlab.xfce.org/xfce/libxfce4ui/-/blob/xfce-4.18/NEWS?ref_type=heads)

Since the new LTS version will use 4.18.4 based on this website (link : https://packages.ubuntu.com/noble/arm64/libxfce4ui-2-0) It would be great for shortcut based windows user to have this bug fixed before the new linux mint release :D !

**Comment by WhosyVox** [comment]
Translation/clarification of the issue:

In the current Mint22 beta XFCE session, keyboard shortcuts are being erroneously triggered during key-down events on single-key bindings.


This can cause key bindings with multiple keys to trigger the single-key event in the process.

Such as Super+E opening both the file manager `[Super+E]` and the panel's menu `[Super]`

**Comment by Watynecc** [comment]
Thank you for the clarification. :D

**Comment by Angedestenebres** [comment]
If you wish the fix in Ubuntu repo, you have to fill an issue on Ubuntu side.

Upstream issue will be not solved by Mint team, see: https://github.com/linuxmint/mint22-beta/blob/master/README.md
