### ISSUE TITLE
Update Request: Evolution 3.52.0 to 3.52.3 upgrade needed at release of Mint 22

### ISSUE THREAD

**Issue by phred2** [linuxmint/mint22-beta#119]
On September 16th 2024, "free" Microsoft email accounts (Outlook and Hotmail) will require OAuth2 authentication. Evolution mail supports OAuth2 but not at 3.52.0-1build2 as in Mint 22 beta. 

I have confirmed Evolution 3.52.3 does have OAuth2 support.

Mint 22 beta is expected to go from beta to release in early August. That's a very short time before the version of Evolution currently in Mint 22 will stop working on Microsoft Hotmail/Outlook accounts.

Is there any possibility for consideration of having an update/upgrade from Evolution 3.52.0 to 3.52.3 available before Mint 22 release? For the beta? Like anytime soon? Please.

Respectfully,
Phred

**Comment by Harry-W-Haines-III** [comment]
Hello Phred:  That is the responsibility of the Evolution package managers as the package is part of the Ubuntu base.  You might try contacting Maintainer: Ubuntu Developers <ubuntu-devel-discuss@lists.ubuntu.com>

**Comment by phred2** [comment]
Thanks H-W-H III

**Comment by phred2** [comment]
Thanks H-W-H III
