### ISSUE TITLE
Proposition mise à jour application

### ISSUE THREAD

**Issue by ericwot8** [linuxmint/mint22-beta#123]
J'ai aussi constaté que beaucoup d'applications n'étaient pas à jour à la dernière version si ça serait possible que vous mettez une option qui permettra à Linux mint d'aller chercher la toute dernière mise à jour des applications déjà par mesure de sécurité et par mesure de fonctionnalité merci beaucoup à toute l'équipe de Linux et changer un peu le thème aussi car c'est toujours le même.

**Comment by fredcw** [comment]
Translated:

I also noticed that many applications were not up to date with the latest version if it would be possible if you put an option which will allow Linux mint to fetch the very latest update of the applications already as a measure of security and for functionality, thank you very much to the entire Linux team and change the theme a little too because it's still the same.

**Comment by Angedestenebres** [comment]
Yes, Flatpaks give the oppotunity to have newest version for a lot of software.

For the others, except for Mint Tools, they come from Ubuntu LTS repo and this is the same thing than the answer here: https://github.com/linuxmint/mint22-beta/issues/122#issuecomment-2214648095

**Comment by clefebvre** [comment]
Yep, it's all been said above.

**Comment by carlosmintfan** [comment]
> Using flatpaks is an option, and they're connected with system packages in mintinstall.

@ericwot8 En utilisant les Flatpaks est une option, et ils sont connectés avec les paquets système dans mintinstall.

**Comment by carlosmintfan** [comment]
> Yes, Flatpaks give the oppotunity to have newest version for a lot of software.
> 
> For the others, except for Mint Tools, they come from Ubuntu LTS repo and this is the same thing than the answer here: [#122 (comment)](https://github.com/linuxmint/mint22-beta/issues/122#issuecomment-2214648095)

Oui, les Flatpaks offrent l'opportunité d'avoir les dernières versions de nombreux logiciels.

Pour les autres, à l'exception des outils de Mint, ils proviennent du référentiel Ubuntu LTS, ce qui est similaire à la réponse ici : #122 (comment).

**Comment by carlosmintfan** [comment]
> Yep, it's all been said above.

Oui, tout a été dit ci-dessus.
