### ISSUE TITLE
mintsources: Banner replacement is not noticeable enough

### ISSUE THREAD

**Issue by carlosmintfan** [linuxmint/mint22-beta#124]
The banner before was more noticeable and clear. Ref: https://matrix.to/#/!sxwkYMHZAFBBLgzlFX%3Amatrix.org/%243KMbu-UAyfWE1DFw0__-uIJyoyr7AG95atqXhWogf34

https://matrix.to/#/!sxwkYMHZAFBBLgzlFX%3Amatrix.org/%24L9sJzRuOk894Qd-CZgMPutCdzm5TfxNd5xHEtdyGP-A

**Comment by Harry-W-Haines-III** [comment]
I agree.  We should be consistent in Linux Mint in advising users of needed actions.  I'm in favor of using one similar to advising a user to reboot after updates that require a reboot.

**Comment by KAMI911** [comment]
Others in the Hungarian community also noticed this, and I share @carlosmintfan 's viewpoint on this issue.

**Comment by pilatomic** [comment]
I also agree on that, maybe it should be in a colored box ?

**Comment by carlosmintfan** [comment]
What we need to know is why Clem changed it. But great that you agree with me. And thanks @anaximeno for the original report in the Matrix!

**Comment by billyswong** [comment]
I am copying the screenshots from Matrix chat into here. The Matrix chat is clumsy to access for people who aren't regular Matrix chat users.

Before:
![image](https://github.com/linuxmint/mint22-beta/assets/33863356/8a2b5335-84a3-4f81-af95-1d08cd902fdd)
After in 22 Beta:
![image](https://github.com/linuxmint/mint22-beta/assets/33863356/b6c79c30-0dcd-453e-a3c8-192cd67221f3)

**Comment by clefebvre** [comment]
> What we need to know is why Clem changed it. But great that you agree with me. And thanks @anaximeno for the original report in the Matrix!

It was too noticeable, too intrusive and it moved or hid content within the window.

I kinda agree that it's not noticeable enough now though. I think I'll leave it where it is but give it relief and maybe turn it into a suggested action (i.e. green button).
