### ISSUE TITLE
Can't install libglib2-0-0

### ISSUE THREAD

**Issue by throughwind** [linuxmint/mint22-beta#126]
sudo apt-get install libglib2.0-0
Reading package lists... Done
Building a dependency tree... Done
Reading status information... Done
Some packages cannot be installed. Perhaps what you are asking is
is not feasible, or you are using an unstable version of the distribution, where
The packages you requested have not yet been created or have been removed from Incoming.
The following information may help you:

The following packages have unmet dependencies:
 mintsources: Depends: python3-gi but it won't install
 Depends: python3-gi-cairo but it won't install
 Depends: python3-repolib but it won't install
 Depends: mint-common (>= 2) but it won't be installed
 Depends: gir1.2-gdkpixbuf-2.0 but it will not be installed
 Depends: gir1.2-glib-2.0 but it will not be installed
 Depends: gir1.2-gtk-3.0 but it will not be installed
 Depends: gir1.2-packagekitglib-1.0 but it will not be installed
 Depends: gir1.2-pango-1.0 but it won't install
 Depends: gir1.2-vte-2.91 but it will not be installed
 Depends: gir1.2-xapp-1.0 but it will not be installed
E: Error: pkgProblemResolver::Resolve resulted in broken packages. This may be caused by frozen packets.

**Comment by mtwebster** [comment]
Mint 22 has libglib already. It's heavily used by many apps. Why are you trying to install it? Is this a different version?

I'm not sure what's going on but if you're missing that you're better off re-installing the iso.

**Comment by throughwind** [comment]
For example I can't install anydesk. 
Maybe it wants to install a version that is not yet supported by the system?
![image](https://github.com/linuxmint/mint22-beta/assets/93036302/9fc7351c-ac82-4512-9bbe-9e071b4af561)

**Comment by mtwebster** [comment]
The .deb package from their website installs ok. It wants to install a single package, but there's no conflict (and it's not libglib)  Did you have any package issues prior to this

Paste the output from:
```
apt install -f --simulate
```

**Comment by throughwind** [comment]
![image](https://github.com/linuxmint/mint22-beta/assets/93036302/c7c96095-7926-49e2-ad91-bb50fb08fa5c)

**Comment by throughwind** [comment]
![image](https://github.com/linuxmint/mint22-beta/assets/93036302/605c8030-c137-4ca2-bd91-9627062178f1)

**Comment by mtwebster** [comment]
What does:
```
dpkg --list | grep libglib
```
return?

**Comment by throughwind** [comment]
![image](https://github.com/linuxmint/mint22-beta/assets/93036302/27becb0f-c92f-4136-a5d3-b833fe60a874)

**Comment by throughwind** [comment]
I don't know what caused it, but it worked
![image](https://github.com/linuxmint/mint22-beta/assets/93036302/ac223fdb-4582-43fa-bc90-b86153928f83)

**Comment by throughwind** [comment]
The problem resolved itself, perhaps a system update helped.
