### ISSUE TITLE
MATE - Volume icon has disappeared from taskbar

### ISSUE THREAD

**Issue by ewangi** [linuxmint/mint22-beta#127]
Linux Mint Wilma MATE beta.

I don't know when it happened but the volume icon has disappeared from the notifications area of my taskbar. There are no unnatural gaps between the icons there, and if I add an additional Xapp Status Applet to the tray then it only has the wifi, battery and update manager icons (I'm assuming that the volume icon is usually one of these).

I am able to add the standard Volume Control icon to the tray but it is gray on gray (I'm using Mint-X) and thus hardly visible, although it works fine. Sound is working fine on the machine.

**Comment by billyswong** [comment]
The same happen here too. I usually test beta ISO via VM, but I boot the live in bare metal this time and see the same. Sound is working but the volume tray icon isn't there.

**Comment by clefebvre** [comment]
Fixed.

**Comment by ewangi** [comment]
Confirmed working after installation of mate-media 1.26.2+mint2+wilma and reboot. Many thanks.
