### ISSUE TITLE
Intuos BT M connected, but not working

### ISSUE THREAD

**Issue by caliarim** [linuxmint/mint22-beta#131]
My Wacom Intuos BT M is recognized and connected by blueman-manager, but Graphics Tablet does not find any sylus and says that no tablet is detected. If I connect it by the USB cable, everything works. The same tablet works via bluetooth in Mint 19.3.

**Comment by caliarim** [comment]
A similar issue is described here: [https://github.com/blueman-project/blueman/issues/2219](https://github.com/blueman-project/blueman/issues/2219)
It is necessary first to pair, then connect. Unfortunately, **Connect** is the first entry, in bold, and I even did not notice the entry Pair.

**Comment by mtwebster** [comment]
So to be clear, this is resolved on your end? (We can't do too much about blueman's GUI, unfortunately)

**Comment by caliarim** [comment]
Yes, it is resolved and you are right that it is a blueman's GUI defect.
