### ISSUE TITLE
l10n: Chinese translations not approved on Launchpad

### ISSUE THREAD

**Issue by aaasoft** [linuxmint/mint22-beta#132]
I'm a chinese Linux Mint user.I install mint22-beta-cinnamon on my work PC.A lot of UI(such as System Settings) not translated in mint22 beta.
I found chinese translation team in launchpad.net didn't work at all.
Some translate suggestion was suggested TWO or THREE YEARS ago,but the translation team do not review at all.Item's still display as '(no translation yet)'.
Some people make great help of translation.they want to joint translation team,but the translation team have no response.

Linux Mint Chinese translation URL:[https://translations.launchpad.net/linuxmint/latest/+lang/zh_CN](https://translations.launchpad.net/linuxmint/latest/+lang/zh_CN)

![图片](https://github.com/linuxmint/mint22-beta/assets/1552027/89662397-5442-4dd0-b585-be7c08bead11)
![图片](https://github.com/linuxmint/mint22-beta/assets/1552027/e5e5fb39-1a48-470a-970a-c03a2c1ab51e)
![图片](https://github.com/linuxmint/mint22-beta/assets/1552027/22867ebb-1830-43f8-8ad7-ea5108b97177)

**Comment by clefebvre** [comment]
Thanks for bringing this to our attention. It's a pity this translation group didn't succeed.

A new group was created. People are welcome to join.

**Comment by clefebvre** [comment]
Don't hesitate to review/approve translations. We still have time before the stable release.

**Comment by aaasoft** [comment]
Thanks,I was join the new translation group now.
