### ISSUE TITLE
mintinstall: Flatpak verification errors

### ISSUE THREAD

**Issue by Qronikarz** [linuxmint/mint22-beta#133]
Other programs are verified correctly.
Czkawka:
![vererror](https://github.com/linuxmint/mint22-beta/assets/84787215/a535bc21-e3a5-4dec-8901-b8629e7a31e2)
Amberol:
![amberror](https://github.com/linuxmint/mint22-beta/assets/84787215/f6d45c60-6c41-4adf-bc65-faa25173a416)

Another case is with Krita:
![kritaverif](https://github.com/linuxmint/mint22-beta/assets/84787215/2572cc8c-771c-41b4-bae6-171484705caa)

Mint 22 is up to date and I refreshed the list in mintinstall menu.

**Comment by haggen88** [comment]
#6  duplicate

**Comment by Qronikarz** [comment]
That's my own issue. And it was about something else.

Your post does in fact have the same issue like here, but the topic got closed either way so it was missed and the problem still happens.
Also, the Krita problem is new.

**Comment by mtwebster** [comment]
This was not a duplicate, and I don't see a problem with Krita - it shows that it's verified above.

**Comment by Qronikarz** [comment]
> I don't see a problem with Krita

My bad, I changed the topic to include it, but probably didn't convey it clearly enough. The problem with Krita is that it is in fact verified, but it shows "by مؤسسة كرينا" instead of "by Krita foundation". And I use Polish language pack.

(note, the Arabic text was taken from Google images OCR so it may be wrong)

**Comment by mtwebster** [comment]
Ah ok I didn't notice that, I check it out.

**Comment by mtwebster** [comment]
developer name translations fixed: https://github.com/linuxmint/mintcommon/commit/b95e908bd22b3afdd96d147748c58bca8f0a7dc6
