### ISSUE TITLE
GTK: a question about SublimeText; a general point

### ISSUE THREAD

**Issue by LinuxOnTheDesktop** [linuxmint/mint22-beta#135]
1) Sublime Text 4 has problems with hardware acceleration (even in its latest development version and at least on some platforms). One such problem is flickering of the tab bar. I have had that problem. [A Sublime developer locates the problem](https://forum.sublimetext.com/t/huge-screen-flickering-and-window-rendering-bugs/62293/3) in GTK3. (Still, the Linux version of the editor comes with hardware acceleration disabled by default.) Does Mint 22 have the problem? (I could test hardware-accelerated Sublime on Mint 22 within a virtual machine, but that would be a poor test.)

2) I think Mint users could use reassurance that they will not have to wait that long to get GTK4 or a near equivalent. For, GTK4 includes many improvements over GTK3 (including [this improvement](https://github.com/linuxmint/mint22-beta/issues/115) that Mint's beta test has raised already).

Thanks for your time.

**Comment by Qronikarz** [comment]
1. I tested that and didn't notice any flickering. But I actually never had that problem in anything on Mint (only the menu rarely) so you may need to test it yourself.



> 2\. including [this improvement](https://github.com/linuxmint/mint22-beta/issues/115) that Mint's beta test has raised already

I made a follow up to this issue and it was also closed by one of the maintainers. Citing:
> This is outside of the scope of Mint really. The file choosers are supplied by whatever toolkit was used to create the application. Which means most of the time either Qt or Gtk. There was really no reason to reopen this here.

Waiting for next reply there. EDIT: Link here - https://github.com/orgs/linuxmint/discussions/513

While testing Sublime I noticed this:
![subinstall](https://github.com/linuxmint/mint22-beta/assets/84787215/8b6eb3c2-8b2c-41f1-b60f-3e15db4ba144)
The "run" button is missing. It normally used to happen to CLI apps/libraries, but Sublime is an editor that you can run. And it even shows up in Programming section in Mint menu:
![submenu](https://github.com/linuxmint/mint22-beta/assets/84787215/158c149e-b94a-4f04-9b6e-1e60210c9228)
Don't know if it's mintinstall bug or just sublime being categorized wrong so just adding this to the current issue.

**Comment by LinuxOnTheDesktop** [comment]
@Qronikarz

Thanks.

**Part of what I'm asking/hoping is that, _unlike_ in the file-picker case that you raised, the Sublime-flickering problem is fixed in a newer version of GTK3 shipped by Mint 22** (via Ubuntu 24) - presuming, for one thing, that Mint's version of GTK3 _is_ newer. Still, my more general point was, indeed: _are we going to get this sort of goody ever on Mint?_

**On the missing 'run' button within the Software Manager when that manager is showing Sublime**: I think that the English label for that button is in fact 'launch'; and it is not a regression. **So I created [this issue](https://github.com/linuxmint/mintinstall/issues/426)**. (I take it that your point about Sublime being filed under 'programming' is this: the categorisation suggests something that is indeed true, namely, that Sublime is a launchable program.)

**Comment by Qronikarz** [comment]
> presuming, for one thing, that Mint's version of GTK3 _is_ newer

I thought GTK3 is not developed anymore so don't know if it can be newer.

> Still, my more general point was, indeed: _are we going to get this sort of goody ever on Mint?

I think that's a topic for a whole different discussion. Mint wants to develop the XAPPS ecosystem more and they use GTK3 so they should work on more "goodies", but that's not an easy task. Two other Desktop Environments that parted with GTK4 - Budgie and Cosmic still are not done migrating the stuff to new toolkits (and in their case it's now 2 and 3 years since they announced it). Really, that is a topic for a different discussion, but it would be good to have it to know what they are focusing on since we only had this in April: https://blog.linuxmint.com/?p=4675. A roadmap that informs users what was worked on and what needs to still be worked on would be nice to have.

> I think that the English label for that button is in fact 'launch'

It may be. I just translated the Polish button name so it could have been both of them as they mean exact same thing.

**Comment by fredcw** [comment]
@LinuxOnTheDesktop 

>I think Mint users could use reassurance that they will not have to wait that long to get GTK4 or a near equivalent.

Mint does has Gtk4. If you install a gtk4 app, gtk4 is installed as a dependency.

**Comment by LinuxOnTheDesktop** [comment]
@fredcw 

Ah. Thank you for telling me. I presume then that apps developed by Mint itself use Gtk3.

As per the post I linked above, seemingly Sublime's devs are - or at least were - awaiting a patch for Gtk3, unless that patch has actually arrived (but not reached Mint 21 yet). One can hope though - unless this will cause problems with Mint - that Sublime will move to Gtk4 at some point.

**Comment by JosephMcc** [comment]
> I think Mint users could use reassurance that they will not have to wait that long to get GTK4 or a near equivalent. For, GTK4 includes many improvements over GTK3 (including https://github.com/linuxmint/mint22-beta/issues/115 that Mint's beta test has raised already).

You will already get that if you install any app that is built with Gtk4. There are quite a few of them in the repos though most also seem to use libadwaita.

**Comment by fredcw** [comment]
@LinuxOnTheDesktop 

> I presume then that apps developed by Mint itself use Gtk3.

Yes, system settings and AFAIK, all the xapps & timeshift etc, are gtk3. Except for the panel and xlets which use clutter.

>awaiting a patch for Gtk3

Gtk3 is still slowly getting bug fixes according to the [changelog](https://gitlab.gnome.org/GNOME/gtk/-/blob/gtk-3-24/NEWS). Mint 22 uses ubuntu's gtk3 which is at version 3.24.41 dated 23-01-2024. I don't know if that's updated between ubuntu releases though.

>that Sublime will move to Gtk4 at some point.

I don't know but it seems unlikely to me since gtk4/libadwaita doesn't even have a proper menubar widget, it only has the hamburger style menus so it would have to be a complete redesign of the UI. Tbh, I don't see how gtk4 is even suitable for large or complex applications.

**Comment by LinuxOnTheDesktop** [comment]
> Mint 22 uses ubuntu's gtk3 which is at version 3.24.41

Mint 21.3 reports the following.

```
$ pkg-config --modversion gtk+-3.0
3.24.33
```

Thus, going by the changelog (thanks, fredcw!), between Mint 21.3 and Mint 22 gtk has undergone the following changes.

```
* Fix a crash introduced in the X11 changes in 3.24.40

* Build fixes

* Wayland: Fix interpretation of gtk-shell protocol

[. . . .]

* GtkEmojiChooser:
 - Update to CLDR v44
 - Add more translations

* GtkGestures:
 - Preserve accuracy when translating events

* X11
 - Support 'virtual' XRANDR monitors

[. . . .]

* GtkMountOperation:
 - Avoid a segfault

* GtkTooltip:
 - Fix some positioning problems

* GtkFileChooser:
 - Handle webdav in the pathbar

* GtkFileChooserNative:
 - Fix closing portal file choosers

* GDK:
 - Handle offscreen windows better in some places

* Wayland:
 - Create pad devices on enter
 - Ensure device-added/removed are emitted
 - Make stylus button mappings compatible with X11
 - Try harder to preserve cursor size with scaling
 - Avoid oob access to cursor images
 - Support tiling in xdg-shell
 - Avoid using legacy cursor names
 - Fix buffer size for scaled custom cursors

* X11:
 - Remove slow path in gdk_cairo_draw_from_gl
 - Trap more XRANDR errors

[. . . .]

* GtkFileChooser:
 - Avoid warnings with GLib 2.76

* Theme:
 - Set caret color in the dark theme

[. . . .]

* Wayland:
 - Notify on initial setting changes
 - Don't crash on 0 size cursors
 - Don't crash if xdg_activation_v1 is missing

* Debugging:
 - Show more information in the inspector

[. . . .]

* Support the file transfer portal for copy-paste and DND

* Treat XKB_MODE_NAME_LODO as super key

* Refactor startup notification handling to be in sync with GTK 4

* GL: Synchronie when calling MakeCurrent

* CSS: Fix a problem with stopping animations

* Wayland: Drop the legacy text input module

[. . . .]

* GtkLabel:
 - Tweak selection behavior

* GtkEmojiChooser:
 - Properly handle empty recent section

* GtkFileChooser:
 - Make ~ key work regardless of dead keys

* build:
 - Improve handling of flaky tests
 - Drop the autotools build

* Wayland:
 - Fix problems with X<>Wayland DND
 - Revert cursor changes from 3.24.35
 - Fix handling of surrounding text in input

[. . . .]

* GtkFontChooserWidget:
 - Fix a critical

* GtkAccelLabel:
 - Differentiate keypad keysyms in accelerators

* Input:
 - Recognize stylus devices as pens
 - Fix problems with motion compression

[. . . .]

* Wayland:
 - Fix problems with unreliable DND
 - Use GLES if required
 - Add support for titlebar gestures
 - Refactor handling of IM client updates
 - Fix cursor hotspots with scaled surfaces
 - Use the xdg-activation protocol
 - Load cursors on demand
 - Fix cursor size on hi-dpi displays

[. . . .]

* Include legacy hicolor icons

* Fix the build with gcc 12

[. . . .]

* X11:
 - Trap errors when getting output properties

* Wayland:
 - Ignore empty preedit updates This fixes a problem with
   textview scrolling

```

**Comment by JosephMcc** [comment]
> I don't know but it seems unlikely to me since gtk4/libadwaita doesn't even have a proper menubar widget, it only has the hamburger style menus so it would have to be a complete redesign of the UI

I don't know where people are getting this stuff but it isn't true. Gtk4 apps can have a menubar and menus just fine. Even gtk4-widget-factory has examples of it.

**Comment by fredcw** [comment]
I only see the hamburger style menus in gtk4-widget-factory (page 3, top middle) [Gnome HIG](https://developer.gnome.org/hig/patterns/controls/menus.html) seems to recommend only a primary and secondary menu.

**Comment by JosephMcc** [comment]
Right there in the middle where it says File, Edit, etc. Just like gtk3-widget-factory

![image](https://github.com/linuxmint/mint22-beta/assets/2231759/0e9c8861-7d05-4685-bad3-fe251629a1c5)

**Comment by LinuxOnTheDesktop** [comment]
@JosephMcc 
I'd like to close this issue. Before I do so, can you tell me whether under Mint 22 SublimeText has unproblematic graphical hardware acceleration?

**Comment by fredcw** [comment]
@JosephMcc You're right, the menu was completely invisible due to the theme I'm using :P

**Comment by clefebvre** [comment]
@LinuxOnTheDesktop sublime-text is my main editor here, I use it all the time. I never noticed any issue, but I guess that depends on your hardware. If acceleration is problematic, maybe it can be turned off?
