### ISSUE TITLE
cinnamon: can't poweroff

### ISSUE THREAD

**Issue by ggddver** [linuxmint/mint22-beta#137]
when i upgrade to linuxmint22,  my thinkpad t460p (i7 6820hq    nvidia 940mx gpu)can't poweroff from kernel6.8.36.  but  it's ok with the old 6.5.41kernel.
when i poweroff, it just close  the  screen  but my notebook still  running.  i can only press the power button for long time to force shutdown

**Comment by fredcw** [comment]
I'm having the same problem on Manjaro unstable. Click shutdown in menu, computer appears to shutdown, monitor switches off but computer is still running and power light remains on. Have to hard shutdown with power button or hard reset and then press power button.

cinnamon 6.2.4 kernel 6.6.37

cf. https://github.com/linuxmint/cinnamon-session/issues/173

**Comment by clefebvre** [comment]
Fixed in cinnamon-session 6.2.1
