### ISSUE TITLE
file-roller: Doesn't open encrypted 7z file 

### ISSUE THREAD

**Issue by kvishnunamboothiri** [linuxmint/mint22-beta#138]
When file-roller is used from Nemo to open 7z file in which file list is also encrypted, it shows an empty content list. But in some other programmes (peazip) it opens fine.
To reproduce the issue:
Right click on a folder with some content, create 7z archive with file list also encrypted.
Open it by double clicking. It will not ask for any password
The contents in the archive appears empty.
When right clicked on the archive and select "Extract here", the message "Extraction not performed appears"

**Comment by haggen88** [comment]
I confirm the bug, when creating a password encrypted file, when running file-roller it does not ask for a password and the file does not appear.

![Screenshot from 2024-07-09 17-31-19](https://github.com/linuxmint/mint22-beta/assets/68134588/48381819-8f51-4824-afb6-8a49eb049826)

![Screenshot from 2024-07-09 17-33-40](https://github.com/linuxmint/mint22-beta/assets/68134588/f5d5736c-1d4b-47fa-81c0-5d03ea8e9ac4)

https://termbin.com/2k58

PS. I have a similar bug in #15 with rar files

**Comment by haggen88** [comment]
perhaps this is related to https://gitlab.gnome.org/GNOME/file-roller/-/issues/252

**Comment by clefebvre** [comment]
This works with file-roller 3.42 (Mint 21.x) and 44.1 (Ubuntu 24.04) but not with 43.0 (Mint 22).

We can't upgrade to 44.1 (we don't want libAdwaita). We'll see if we can cherry pick a fix or not.

**Comment by clefebvre** [comment]
Compiling 43.0 on Mint 21.3.... it works.

I'm not sure what's going on here.

**Comment by clefebvre** [comment]
It's reproducible also with engrampa.

**Comment by clefebvre** [comment]
Confirmed also that it's a bug occurring when opening the archive, not when making it.

**Comment by Harry-W-Haines-III** [comment]
Seems like it is a library dependency issue.

**Comment by clefebvre** [comment]
I wonder if this is relevant https://gitlab.gnome.org/GNOME/file-roller/-/commit/844f6fbbef2a616f4bf1eb877710f55bced71d62

**Comment by clefebvre** [comment]
nope.. but it fixed https://github.com/linuxmint/mint22-beta/issues/176 :)

**Comment by clefebvre** [comment]
Ok it fixes this as well.

**Comment by clefebvre** [comment]
Fixed in file-roller 43.0+mint1
