### ISSUE TITLE
Laptop Idle Power Consumption - changes after the charger is plugged in and removed

### ISSUE THREAD

**Issue by jude-lieb** [linuxmint/mint22-beta#139]
Problem: After booting from battery power normally, the idle power consumption is about 5 watts. If I then plug in the laptop for a moment and then unplug it, the idle rate somehow drops to 3 watts. It maintains roughly the same amount until a significant application process runs, which of course increases the power usage. 

However, once the major application process (such as a web browser) is ended, the idle power consumption returns to the previous 5 watts and never goes back down unless the charger is again plugged in and then removed. This behavior occurs both with and without use of TLP power management. 

Lenovo Ideapad Laptop 15aba7
Ryzen 7 5825U

**Comment by clefebvre** [comment]
If this is a bug, more troubleshooting is needed to identify the responsible software component.

**Comment by clefebvre** [comment]
Marking as upstream since none of the components are ours, tlp, upower, gnome power statistics...
