### ISSUE TITLE
Cinnamon: Change was made to desktop themes selection graphic, now seems out of proportion.

### ISSUE THREAD

**Issue by Harry-W-Haines-III** [linuxmint/mint22-beta#141]
This applies to Cinnamon only.  I think there was a change made for another desktop but now in Cinnamon the graphic for the selection of the desktop themes seems out of proportion from what it was before.  The first screenshot was from the first Beta ISO, the second is from the current ISO fully updated.  The 2nd ISO/updates corrected the height of the Mint-L graphics so now all the desktops are uniform but the graphic to select a change seems out of proportion.

This might be nit-picky and if you believe it is, feel free to close this issue.

From the first ISO:
![1st-ISO](https://github.com/linuxmint/mint22-beta/assets/45599505/992cdc39-acc2-4197-aa27-168a99747edc)

From the current ISO fully updated:
![2nd-ISO](https://github.com/linuxmint/mint22-beta/assets/45599505/93b72df6-c9d8-4593-b171-870afce0026c)

**Comment by JosephMcc** [comment]
This change was already reverted in Cinnamon git master. It will come as an update.

**Comment by Harry-W-Haines-III** [comment]
Thank you!
