### ISSUE TITLE
relnotes: ZFS removal isn't mentioned

### ISSUE THREAD

**Issue by skirmess** [linuxmint/mint22-beta#143]
The installer doesn't offer to install on ZFS but neither [https://blog.linuxmint.com/?p=4725](https://blog.linuxmint.com/?p=4725), [https://www.linuxmint.com/rel_wilma_whatsnew.php](https://www.linuxmint.com/rel_wilma_whatsnew.php), nor [https://www.linuxmint.com/rel_wilma.php](https://www.linuxmint.com/rel_wilma.php) mention that ZFS is no longer supported.

**Comment by clefebvre** [comment]
Thanks. This was removed on purpose but it should be mentioned in the release notes indeed.

**Comment by clefebvre** [comment]
Release notes updated.
