### ISSUE TITLE
Greyscreen after Update / Recover option no possible

### ISSUE THREAD

**Issue by supermann63** [linuxmint/mint22-beta#146]
Strange on a lenovo notebook with dual boot, after update to the newest version of mint, a reboot must been done.
After that a grey screen and a recovery with shift keys not possible.
After a new installation from original medium, the notebook update the newest packages and about that the same grey screen!

Problem are equal on this machines the kernels. I have found this: 
5.15.0-113

The parameter nomodeset helps, but this is not possible for "Normal Users" when a recovery option is no possible to choice! 
Why shift keys not working - many other users report same problem?
Why when 3 or 4 times a start crashes, why Mint not boot automaticly in nomdeset - mode?

System:
  Kernel: 5.15.0-113-generic x86_64 bits: 64 compiler: gcc v: 11.4.0 Desktop: Cinnamon 5.8.4
    tk: GTK 3.24.33 wm: muffin dm: LightDM Distro: Linux Mint 21.2 Victoria base: Ubuntu 22.04 jammy
Machine:
  Type: Laptop System: LENOVO product: 82C7 v: Lenovo V15-ADA serial: <superuser required>
    Chassis: type: 10 v: Lenovo V15-ADA serial: <superuser required>
  Mobo: LENOVO model: LNVNB161216 v: No DPK serial: <superuser required> UEFI: LENOVO
    v: E8CN31WW date: 11/11/2021
Battery:
  ID-1: BAT0 charge: 33.9 Wh (95.5%) condition: 35.5/35.0 Wh (101.3%) volts: 8.7 min: 7.5
    model: SMP L16M2PB2 serial: <filter> status: Charging
CPU:
  Info: dual core model: AMD Athlon Gold 3150U with Radeon Graphics bits: 64 type: MT MCP
    arch: Zen/Zen+ note: check rev: 1 cache: L1: 192 KiB L2: 1024 KiB L3: 4 MiB
  Speed (MHz): avg: 1699 high: 2283 min/max: 1400/2400 boost: enabled cores: 1: 2283 2: 2181
    3: 1153 4: 1182 bogomips: 19163
  Flags: avx avx2 ht lm nx pae sse sse2 sse3 sse4_1 sse4_2 sse4a ssse3 svm
Graphics:
  Device-1: AMD Picasso/Raven 2 [Radeon Vega Series / Radeon Mobile Series] vendor: Lenovo
    driver: N/A pcie: speed: 8 GT/s lanes: 16 bus-ID: 02:00.0 chip-ID: 1002:15d8
  Device-2: Chicony Integrated Camera type: USB driver: uvcvideo bus-ID: 1-5:2
    chip-ID: 04f2:b624
  Display: x11 server: X.Org v: 1.21.1.4 driver: X: loaded: ati,vesa
    unloaded: fbdev,modesetting,radeon gpu: N/A display-ID: :0 screens: 1
  Screen-1: 0 s-res: 1280x1024 s-dpi: 96
  Monitor-1: default res: 1280x1024 size: N/A
  OpenGL: renderer: llvmpipe (LLVM 15.0.7 256 bits) v: 4.5 Mesa 23.2.1-1ubuntu3.1~22.04.2
    direct render: Yes
Audio:
  Device-1: AMD Raven/Raven2/Fenghuang HDMI/DP Audio vendor: Lenovo driver: snd_hda_intel
    v: kernel pcie: speed: 8 GT/s lanes: 16 bus-ID: 02:00.1 chip-ID: 1002:15de
  Device-2: AMD Raven/Raven2/FireFlight/Renoir Audio Processor vendor: Lenovo
    driver: snd_pci_acp3x v: kernel pcie: speed: 8 GT/s lanes: 16 bus-ID: 02:00.5 chip-ID: 1022:15e2
  Device-3: AMD Family 17h HD Audio vendor: Lenovo driver: snd_hda_intel v: kernel pcie:
    speed: 8 GT/s lanes: 16 bus-ID: 02:00.6 chip-ID: 1022:15e3
  Sound Server-1: ALSA v: k5.15.0-113-generic running: yes
  Sound Server-2: PulseAudio v: 15.99.1 running: yes
  Sound Server-3: PipeWire v: 0.3.48 running: yes
Network:
  Device-1: Realtek RTL8822CE 802.11ac PCIe Wireless Network Adapter vendor: Lenovo
    driver: rtw_8822ce v: N/A pcie: speed: 2.5 GT/s lanes: 1 port: 2000 bus-ID: 01:00.0
    chip-ID: 10ec:c822
  IF: wlp1s0 state: up mac: <filter>
Bluetooth:
  Device-1: Realtek Bluetooth Radio type: USB driver: btusb v: 0.8 bus-ID: 1-6:3
    chip-ID: 0bda:c123
  Report: hciconfig ID: hci0 rfk-id: 2 state: down bt-service: enabled,running rfk-block:
    hardware: no software: yes address: <filter>
Drives:
  Local Storage: total: 476.94 GiB used: 81.68 GiB (17.1%)
  ID-1: /dev/sda vendor: Silicon Power model: SPCC Solid State Disk size: 476.94 GiB
    speed: 6.0 Gb/s serial: <filter>
Partition:
  ID-1: / size: 152.74 GiB used: 40.57 GiB (26.6%) fs: ext4 dev: /dev/sda7
  ID-2: /boot/efi size: 99.2 MiB used: 32.5 MiB (32.8%) fs: vfat dev: /dev/sda2
Swap:
  ID-1: swap-1 type: partition size: 10 GiB used: 0 KiB (0.0%) priority: -2 dev: /dev/sda6
Sensors:
  Message: No sensor data found. Is lm-sensors configured?
Repos:
  Packages: 2164 apt: 2155 flatpak: 9
  No active apt repos in: /etc/apt/sources.list
  Active apt repos in: /etc/apt/sources.list.d/locale.list
    1: deb http: //live.linuxmint.com victoria main
    2: deb-src http: //live.linuxmint.com victoria main
  Active apt repos in: /etc/apt/sources.list.d/official-package-repositories.list
    1: deb http: //packages.linuxmint.com victoria main upstream import backport
    2: deb http: //archive.ubuntu.com/ubuntu jammy main restricted universe multiverse
    3: deb http: //archive.ubuntu.com/ubuntu jammy-updates main restricted universe multiverse
    4: deb http: //archive.ubuntu.com/ubuntu jammy-backports main restricted universe multiverse
    5: deb http: //security.ubuntu.com/ubuntu/ jammy-security main restricted universe multiverse
Info:
  Processes: 265 Uptime: 41m Memory: 5.66 GiB used: 2.51 GiB (44.3%) Init: systemd v: 249
  runlevel: 5 Compilers: gcc: 11.4.0 alt: 11/12 Client: Cinnamon v: 5.8.4 inxi: 3.3.13

**Comment by archisman-panigrahi** [comment]
You seem to be using Mint 21.3. This is bugtracker for Mint 22.
This issue should be closed.
