### ISSUE TITLE
Linux Mint 22 XFCE - No sound after screen locking

### ISSUE THREAD

**Issue by cod0b** [linuxmint/mint22-beta#147]
Music stops playing when the screen goes into sleep mode or is locked.
After unlocking sound plays again.

**Comment by mtwebster** [comment]
In Xfce this is normal behavior, due to how the lock-screen is implemented.

**Comment by clefebvre** [comment]
Yes, this is because it uses light-locker. It goes back to the greeter basically which isn't part of the user session. There are pros vs cons between light-locker and xfce4-screensaver, it's still the better alternative in our opinion, but this is one of them.
