### ISSUE TITLE
Dual boot LM 22 and Windows

### ISSUE THREAD

**Issue by zelimir86** [linuxmint/mint22-beta#148]
I'm not sure if this is problem with grub, but it can be. I am dual booting LM 22 and Windows 11 (which has bitlocker encription turn on), grub and os-prober can see Windows, but every time I choose Windows from grub it asks for bitlocker recovery key. On a previous LM versions (21.x) it only asks for bitlocker key the first time I run Windows from grub, on a next boot Windows from grub it did not ask for bitlocker key and boots into Windows right away.

**Comment by gmanskibiditoilet** [comment]
You would better turn OFF Bitlocker, because Bitlocker does not allow users to access the BIOS to change settings. That's why it's only the best to turn OFF Bitlocker and clean install Mint (you should only dual boot it in case dual booting for you is too mandatory).
