### ISSUE TITLE
file-roller: cannot decompress rar files with password

### ISSUE THREAD

**Issue by haggen88** [linuxmint/mint22-beta#15]
It is not possible to unzip a RAR file with a password. When trying to extract the content fille-roller shows an error.

e.g.: https://www.mediafire.com/file/9kzje2ntboghpyp/test+3+c+winrar_.rar/file
password: 123

![error](https://github.com/linuxmint/mint22-beta/assets/68134588/3bc75e18-85f1-4b9a-a204-b0560b1965b6)

I tried to experiment. On a Win10 partition I created several compressed files with password to open them in Mint22. Only rar files created with WinRar (7.01) give this problem.

P.S.  The problem is solved by installing **unrar** 1:7.0.7-1build1 or  **rar** 2:7.00-1build1, you should consider installing one of these applications by default.

**Comment by Qronikarz** [comment]
I think I had that problem few times on Mint 21.
However I also always had PeaZip flatpak installed so it never bothered me much.

**Comment by clefebvre** [comment]
unrar was removed from mint-meta-codecs.

It's non-free and it was a source of vulnerability. We preferred to see people add it willingly rather than depend on it and have it suggested as part of the codecs.
