### ISSUE TITLE
Linux Mint 22 XFCE - The colors of the icons in the tray cannot be changed

### ISSUE THREAD

**Issue by cod0b** [linuxmint/mint22-beta#150]
The colors of the icons in the tray cannot be changed.
Despite selecting different icon sets, most of the tray icons are black (or light in dark mode).
It would be nice to see colorful icons.
![icons](https://github.com/linuxmint/mint22-beta/assets/96794172/33fe7dfa-54f4-4dfa-9d33-7007dc1742ca)

**Comment by mtwebster** [comment]
These are 'symbolic' icons and this is deliberate - symbolic icons change their primary color depending on the theme being used, so that they're always visible (unlike color icons that can become muddy or poorly-contrasted with the wrong background.
