### ISSUE TITLE
Update Manager not showing all updates available.

### ISSUE THREAD

**Issue by erenfro** [linuxmint/mint22-beta#152]
In LM 22.0beta, I'm noticing a new issue with updates not always showing.
![image](https://github.com/linuxmint/mint22-beta/assets/1180990/f957a2b1-c334-4fdd-b01a-13635a6eb7d5)

Shows no updates, which recently just updated a system package and a flatpak package both. But still, `apt update` shows:
```
3 packages can be upgraded. Run 'apt list --upgradable' to see them.
```
Which is:
```
apparmor/noble-updates 4.0.1-0ubuntu0.24.04.2 amd64 [upgradable from: 4.0.0-beta3-0ubuntu3]
libapparmor1/noble-updates 4.0.1-0ubuntu0.24.04.2 amd64 [upgradable from: 4.0.0-beta3-0ubuntu3]
libapparmor1/noble-updates 4.0.1-0ubuntu0.24.04.2 i386 [upgradable from: 4.0.0-beta3-0ubuntu3]
```

This seems like something update manager should be updating normally.

**Comment by erenfro** [comment]
In combination with this, in another one of my test VM's, I ran `apt update`, was informed of 12 updates as follows:
```
apparmor/noble-updates 4.0.1-0ubuntu0.24.04.2 amd64 [upgradable from: 4.0.0-beta3-0ubuntu3]
firefox-locale-en/wilma 128.0+linuxmint1+wilma amd64 [upgradable from: 127.0.2+linuxmint1+wilma]
firefox/wilma 128.0+linuxmint1+wilma amd64 [upgradable from: 127.0.2+linuxmint1+wilma]
libapparmor1/noble-updates 4.0.1-0ubuntu0.24.04.2 amd64 [upgradable from: 4.0.0-beta3-0ubuntu3]
linux-generic/noble-updates 6.8.0-38.38 amd64 [upgradable from: 6.8.0-36.36]
linux-headers-generic/noble-updates 6.8.0-38.38 amd64 [upgradable from: 6.8.0-36.36]
linux-image-generic/noble-updates 6.8.0-38.38 amd64 [upgradable from: 6.8.0-36.36]
linux-libc-dev/noble-updates 6.8.0-38.38 amd64 [upgradable from: 6.8.0-36.36]
linux-tools-common/noble-updates,noble-updates 6.8.0-38.38 all [upgradable from: 6.8.0-36.36]
openssh-client/noble-updates,noble-security 1:9.6p1-3ubuntu13.4 amd64 [upgradable from: 1:9.6p1-3ubuntu13.3]
openssh-server/noble-updates,noble-security 1:9.6p1-3ubuntu13.4 amd64 [upgradable from: 1:9.6p1-3ubuntu13.3]
openssh-sftp-server/noble-updates,noble-security 1:9.6p1-3ubuntu13.4 amd64 [upgradable from: 1:9.6p1-3ubuntu13.3]
```

Update Manager presented me with updates for Firefox and openssh, and in the packages tab for openssh, it showed openssh-client, openssh-server, and openssh-sftp-server. 
After updating, all those packages were no longer showing in `apt list --upgradable` but neither were any of the linux-* packages either.

Inspecting the logs of the apt history, I see:
```
Start-Date: 2024-07-10  11:29:55
Commandline: /usr/sbin/synaptic --hide-main-window --non-interactive -o Synaptic::closeZvt=true --set-selections-file /tmp/tmpqwfqpdkc --parent-window-id 52428813
Requested-By: psi-jack (1000)
Upgrade: firefox-locale-en:amd64 (127.0.2+linuxmint1+wilma, 128.0+linuxmint1+wilma), openssh-client:amd64 (1:9.6p1-3ubuntu13.3, 1:9.6p1-3ubuntu13.4), openssh-server:amd64 (1:9.6p1-3ubuntu13.3, 1:9.6p1-3ubuntu13.4), firefox:amd64 (127.0.2+linuxmint1+wilma, 128.0+linuxmint1+wilma), openssh-sftp-server:amd64 (1:9.6p1-3ubuntu13.3, 1:9.6p1-3ubuntu13.4)
End-Date: 2024-07-10  11:30:02
```

I'm confused as to what's going on here...

**Comment by claudiux** [comment]
Linux Mint checks certain packages from Ubuntu. When these packages are correct (or correctly modified), they become available in the Linux Mint repositories. This ensures greater security for users.
We advise you never to execute the command: `apt upgrade`.

**Comment by erenfro** [comment]
As a Linux User of just over 30 years, I'm confused as to what's actually going on here, and why. Please don't treat me as a newbie that doesn't know better. What does "correct" or "correctly modified" mean in this context?

**Comment by claudiux** [comment]
It seems to me that a few years ago, a graphics card driver update (from Ubuntu) locked up many computers. Linux Mint is designed to avoid this.

**Comment by Angedestenebres** [comment]
Hey :cat: 

For packages related to linux kernel, you should have them now in Software Manager, at least I have them:

![VirtualBox_Linux Mint 22_10_07_2024_19_11_40](https://github.com/linuxmint/mint22-beta/assets/21110485/397dad23-3629-433d-b72f-6a09c7f4a016)

For Apparmor, it's still flagged as beta package (in package name). Anyway, there is a special update deployment (Phased Update) on Ubuntu package before they are considered as OK and suggested to all for update. For more information about that: https://wiki.ubuntu.com/PhasedUpdates

So in this case, that's normal if this package is not included in updates for your system. You can see this special status with an apt show packagename:

![VirtualBox_Linux Mint 22_10_07_2024_19_11_47](https://github.com/linuxmint/mint22-beta/assets/21110485/23444b32-ebc0-48de-a9ea-ee7abf3eb998)

I guess this is what @claudiux tried to said before. If I'm wrong or I missed something, feel free to add details ;)

**Comment by erenfro** [comment]
I was referred to this which helped me understand something I was not familiar with until now:
https://ubuntu.com/server/docs/about-apt-upgrade-and-phased-updates

**Comment by erenfro** [comment]
> It seems to me that a few years ago, a graphics card driver update (from Ubuntu) locked up many computers. Linux Mint is designed to avoid this.

It's also funny that you mention this, specifically. When I was on Arch Linux here recently, an update to linux 6.8.x's tail end, caused massive issues with anyone using a relatively current AMD GPU and did *not* have Resizable Bar enabled. My UEFI Setup did not have it enabled per default, I never knew this, until this happened, and found out the hard way when my system became so unstable it wasn't even usable anymore. This made me turn to openSUSE TW, and 2 weeks later the exact same thing happened all over again. 6.8.x was updated, and the same thing happened. This time I'd already known what was up, and figured out the solution, and performed it, this was, in part, actually thanks to the people of Arch Linux being kind testers to this catastrophic event. 🤣  But, it repeated, in openSUSE. It just surprised me that it did so.

So, while I may be using Liqourix on my Desktop, and Xanmod on my laptop running LM22 right now, if in the future any updates cause weird issues, I have a Linux 6.8 kernel to fall back to to validate whether that's the culprit.

**Comment by dayvid3** [comment]
I'm actually getting similar behavior in 21.3.  I've seen it before, but noticed today as well with a couple of dotnet 8x runtimes.

**Comment by carlosmintfan** [comment]
@claudiux Please tell me, where does Mint check this?? The level system has been thrown away years ago.

**Comment by carlosmintfan** [comment]
Mint has this apt policy and its upstream channel, but then, why does `apt update` show the updates??

**Comment by Harry-W-Haines-III** [comment]
Try this command and you will see something different "sudo mintupdate-cli upgrade"

**Comment by carlosmintfan** [comment]
But it would be great if you could give me a link to the code line...or tell me it it is the apt policy and that is ignored by apt upgrade...???

**Comment by Angedestenebres** [comment]
@carlosmintfan This is due to phased updates, please read these answers: https://github.com/linuxmint/mint22-beta/issues/152#issuecomment-2221066070 & https://github.com/linuxmint/mint22-beta/issues/152#issuecomment-2221140953

The explanation is there. This is a special behavior of APT on Ubuntu and you already have that with Mint 21 (and old versions normally).

Also, you should have the same result with Synactic (that MintUpdate uses to manage deb packages from Ubuntu repo), see screens below:
![VirtualBox_Linux Mint 22_13_07_2024_11_54_15](https://github.com/user-attachments/assets/d30f9409-3ed7-456b-8b3e-3b0fcc09c884)
![VirtualBox_Linux Mint 22_13_07_2024_11_53_33](https://github.com/user-attachments/assets/96c1259e-d75a-400e-a619-f8065e445132)

Now if you try via Terminal with apt update & upgrade, nothing will happen until the status `phased update` gets 100% (and so disappears), see below:

![VirtualBox_Linux Mint 22_13_07_2024_11_58_09](https://github.com/user-attachments/assets/12dc884f-48ce-4bd9-b4cd-c51745f1f788)

You can force the installation of these updates as indicated in link above but it's clearly not recommended.

I hope this will help to understand why there is a difference between upgradable packages on the apt list and MintUpdate.
