### ISSUE TITLE
mintUpdate: flatpak apps show different version updates

### ISSUE THREAD

**Issue by Qronikarz** [linuxmint/mint22-beta#153]
Something very fresh that seemed weird to me since the DXVK looks like it's downgrading the version. The issue only appears in MintUpdate:
![mintupd](https://github.com/linuxmint/mint22-beta/assets/84787215/ede3848b-5889-45d1-8db3-486a793872d7)

Flathub:
![flathub](https://github.com/linuxmint/mint22-beta/assets/84787215/647feaf9-0704-4c5e-bca2-8b193d3c40ea)

Flathub cli:
![cli](https://github.com/linuxmint/mint22-beta/assets/84787215/7594263a-f2cf-47ff-9f6a-018c6d33c3ac)

**Comment by archisman-panigrahi** [comment]
Does it persist if you refresh Mint Update page?

**Comment by Qronikarz** [comment]
Of course. I have refreshed it 5 times before and even right now once more. Still shows 1.10.3

I only didn't check rebooting the OS.

**Comment by mtwebster** [comment]
This is because there are multiple active versions of this plugin (one for each freedesktop runtime version it supports - 21.08, 22.08, 23.08.  The updater is getting confused - the 21.08 plugin's latest version is 1.10.3

**Comment by Qronikarz** [comment]
Just asking if it's supposed to be fixed now, or it needs to wait for new ISO. Because yesterday I got this again:
![emm](https://github.com/user-attachments/assets/ed35f8d0-55a2-42b7-bba7-7d89e250fac3)
The flathub remote cli was showing the same thing as in my OP.

**Comment by Harry-W-Haines-III** [comment]
@Qronikarz Fixes have not been released yet.
