### ISSUE TITLE
idea: mintUpdate showing changelog for Flathub apps

### ISSUE THREAD

**Issue by Qronikarz** [linuxmint/mint22-beta#156]
Native packages allow users to download changelog and see what was fixed/added/improved. (most of them, since Firefox just shows `* 128.0`)
![native](https://github.com/linuxmint/mint22-beta/assets/84787215/1b14b360-af82-4d74-8bcf-24766d72ba47)
Flatpak programs don't have that section in mintUpdate:
![flatpak](https://github.com/linuxmint/mint22-beta/assets/84787215/b2274648-ec6f-4343-8211-1551c6414048)
Bottles changelog on Flathub:
![flathub](https://github.com/linuxmint/mint22-beta/assets/84787215/ca5575dc-3d2b-4bbc-846f-6a0596b8355d)

There is this feature request in Flatpak repository along with PR for it and supposedly GNOME-Software already shows changelogs for Flatpaks
https://github.com/flatpak/flatpak/issues/5561

Don't know how it works for standalone Flatpaks, but at least ones in Flathub would have this function.

Edit: Quick question. Why do native packages and flatpak differ in the tab naming? Natives have "description" and flatpaks have "information".

**Comment by clefebvre** [comment]
We could unify the tab names I guess.

Thanks for the idea on flatpak changelog. I'm adding it to the roadmap for Mint 22.1.
