### ISSUE TITLE
Ejected external USB drive gets turned on when turning off Linux Mint

### ISSUE THREAD

**Issue by Qronikarz** [linuxmint/mint22-beta#158]
Don't know if it's Mint 22 issue or it happens in older versions too. Either way don't know where to post this.

Due to the way Mint copies files to other drives (meaning, the progress window doesn't actually sync the files so you need to wait) I have a procedure when copying files to external USB drive which looks as follows:
1. Wait for the progress dialog to disappear
2. Wait for the USB drive to stop spinning (it's quiet but you can hear it since it's HDD)
3. In Nemo right click the drive and choose "safely eject the drive" (or something like that, I translated it)
4. Wait for the drive to stop working and for it's LED to turn off.

At this point it's safe to disconnect the USB cable, but I forgot to do it few times and turned off Linux Mint. It always turns on the USB drive. And to make it worse, the drive keeps spinning when the computer is turned off.

I try to disconnect the USB cable, but this feels like a bug.

**Comment by clefebvre** [comment]
I'm not sure what to say... we use gvfs to copy files. This is upstream from us. There's a lot involved and it's not ideal but it's not really something we can fix easily.

**Comment by Qronikarz** [comment]
I am aware that syncing files is questionable since there's this Nemo issue exactly for this problem:
https://github.com/linuxmint/nemo/issues/3221

But, my issue here is with Linux Mint powering on a drive that was already unmounted, safely ejected and turned off. What functions does shutting down Mint call, that the USB device gets powered on?

Can I somehow record the shutting down process and maybe check in logs what exactly it is doing?

**Comment by fredcw** [comment]
To view the systemd log for previous session:

`journalctl -b -1`

log can be long so use pg down, end, etc.
