### ISSUE TITLE
l10n: goa-gtk Incomplete translations

### ISSUE THREAD

**Issue by anaximeno** [linuxmint/mint22-beta#16]
![Screenshot_LinuxMint22_2024-06-30_15:30:02](https://github.com/linuxmint/mint22-beta/assets/63073056/3facd0e0-6681-41cb-8135-d53582a0885f)

![Screenshot_LinuxMint22_2024-06-30_15:29:42](https://github.com/linuxmint/mint22-beta/assets/63073056/fbcff087-d6e2-475c-b305-bd00adb0252c)

![Screenshot_LinuxMint22_2024-06-30_15:30:12](https://github.com/linuxmint/mint22-beta/assets/63073056/36dc249c-e828-484f-9d60-3a285a392663)

Some parts also lack a translation since the installation is set to Portuguese but some labels are in English.

**Comment by clefebvre** [comment]
Make sure language-pack-gnome-pt* is installed.

libAdwaita is OK here. There's no other choice since libgoa-backend uses it.

**Comment by anaximeno** [comment]
It's installed:

![Screenshot_LinuxMint22_2024-06-30_16:02:34](https://github.com/linuxmint/mint22-beta/assets/63073056/41a1c550-0b9e-446e-8559-5c12dd5fff03)

**Comment by clefebvre** [comment]
The software itself is localized..

![image](https://github.com/user-attachments/assets/321b1a71-a435-4967-9882-13ead948d178)

![image](https://github.com/user-attachments/assets/056d08f3-9c28-4584-81da-b50b80cb1b3a)

**Comment by clefebvre** [comment]
It works in German also. I'll have a look at the translations to see if they're missing in Portuguese.

**Comment by clefebvre** [comment]
![image](https://github.com/user-attachments/assets/e4bcfa0c-58b3-4207-a82b-3db811f2f891)

https://github.com/GNOME/gnome-online-accounts/commit/3241c4de257c242bc947f33d2da6181c42672644
https://github.com/GNOME/gnome-online-accounts/commit/045436eaacfa36dfb9fb9f079855a5ca6952820c

PT translations updated in 3.51, but the version of libgoa in Ubuntu 24.04 is 3.50.

This being a point release, it might come as an update from Ubuntu.
