### ISSUE TITLE
artwork: No Steam tray-icon with Mint-Y-Sand

### ISSUE THREAD

**Issue by MiZoG99** [linuxmint/mint22-beta#162]
No Steam tray-icon with default icon set on Mint Cinnamon 22 beta

![Mint-Y-Sand-icon-set](https://github.com/user-attachments/assets/25e27f69-9341-4101-9c86-e5f7f182dbbb)

Switching to Papirus icons

![Papirus-icon-set](https://github.com/user-attachments/assets/1080b44f-63f4-49ee-8b94-4246955c3ca4)

Tray-icon is displayed

This is not happening on Linux Mint 21.3 with the default icon set and the same Steam package

THIS CONCERNS [steam-latest.deb](https://store.steampowered.com/about), Valve's own deb installer not the steam-installer package found in Ubuntu repos!

**Comment by StercusMax** [comment]
You should certainly report this here as well: https://github.com/linuxmint/mint-y-icons

**Comment by ghost** [comment]
> You should certainly report this here as well: https://github.com/linuxmint/mint-y-icons

No, the devs will redirect this to the correct place if they want to. The reporter did well, since it was [clearly](https://blog.linuxmint.com/?p=4725) stated to report bugs on this github project while using LM22 Beta... Also - the reporter clearly stated, it wasn't happening in 21.3. So let's keep things at bay please, and do not redirect people to upstreams, when LM team clearly wrote:

> Bugs in **this release should be reported** on Github at https://github.com/linuxmint/mint22-beta.

~~Ps. back on topic: **I can confirm this bug happening on my end too**~~
Ps2: Cancel that, can't reproduce on my end, steam was only restarting that time, but appeared perfectly afterwards.

**Comment by clefebvre** [comment]
I can't reproduce the issue.

**Comment by clefebvre** [comment]
![image](https://github.com/user-attachments/assets/c13232ae-838a-482a-af4d-26a9f90c719b)
![image](https://github.com/user-attachments/assets/31d38647-44b7-47a5-ad36-cec8664a73c3)
![image](https://github.com/user-attachments/assets/43a90054-1fad-4fc3-97c8-01dff493c38c)

**Comment by StercusMax** [comment]
Tried as well, i can't reproduce the issue too, if you ask it's the deb from steam so no error of me here:
![image](https://github.com/user-attachments/assets/394b7bce-3691-44db-bf48-b67f269ccab9)
![image](https://github.com/user-attachments/assets/1011ee4c-b9c8-49bc-8362-10bd3f347785)
![image](https://github.com/user-attachments/assets/987e28ce-dbf5-41c0-853d-27594f0259cf)
![image](https://github.com/user-attachments/assets/a36dbae9-975c-449b-8357-9b3679498d0f)

**Comment by clefebvre** [comment]
It's possible Steam fixed this with an update to their client.

**Comment by Ikytsu** [comment]
> > You should certainly report this here as well: https://github.com/linuxmint/mint-y-icons
> 
> No, the devs will redirect this to the correct place if they want to. The reporter did well, since it was [clearly](https://blog.linuxmint.com/?p=4725) stated to report bugs on this github project while using LM22 Beta... Also - the reporter clearly stated, it wasn't happening in 21.3. So let's keep things at bay please, and do not redirect people to upstreams, when LM team clearly wrote:
> 
> > Bugs in **this release should be reported** on Github at https://github.com/linuxmint/mint22-beta.
> 
> Ps. back on topic: **I can confirm this bug happening on my end too**

Sorry about my stupid answer, i was pretty tired when i wrote, i totally understand what you are saying, anyway how did you reproduce the issue, i did the same thing but can't have the issue
