### ISSUE TITLE
Mintinstall - Unverified flatpaks aren't listed if you open flatpak category

### ISSUE THREAD

**Issue by Angedestenebres** [linuxmint/mint22-beta#163]
As said in the title, even if you active the feature in preferences menu, they are not listed when you use flatpak category whereas I can find them by using the search engine. See video below with Spotify as example:

[cinnamon-2024-07-12T155632+0200.webm](https://github.com/user-attachments/assets/1bb92bed-64b3-42ef-a1ec-2b2b6217d4ee)

**Comment by mtwebster** [comment]
This is deliberate - no matter what the preference setting, unverified flatpaks are sorted to the end, and the flatpak category only shows the first 200 results. Enabling them does not make them safer and we still want to discourage/warn about their use.

**Comment by Angedestenebres** [comment]
@mtwebster : Thanks for your answer. Maybe a note could be added about that on new features list?
