### ISSUE TITLE
Libreoffice icons not working, maybe libreoffice-gnome is needed?

### ISSUE THREAD

**Issue by aldorgan** [linuxmint/mint22-beta#164]
![Skärmbild från 2024-07-12 18-16-34](https://github.com/user-attachments/assets/55d0c8c1-32ff-41b9-ba82-bfd8f3a38757)

**Comment by aldorgan** [comment]
Update, i can see that libreoffice-gnome is already installed so it must be something with mint icons? Mint-L and X is a bit better but not perfect.

**Comment by contrarybaton60** [comment]
It looks to appear that it's using the dark-mode icons instead of the default

**Comment by Angedestenebres** [comment]
Linked to: https://github.com/linuxmint/mint22-beta/issues/59
