### ISSUE TITLE
Installer Boot Failure - older HP notebook

### ISSUE THREAD

**Issue by becker44a** [linuxmint/mint22-beta#165]
Attempt to install Mint 22 on old HP laptop - failed to boot
HP Pavilion dv6-6117dx 15.6" HD AMD A8-3500M 4GB 500GB
Specs:  CPU A8-3500M APU 1.5 GHz   Ram 4 Gb   Hdd 500 Gb
Eventually succeeded by using Grub edit mode to add "nomodeset" boot option.

Previous successful install:  Mint 21.2 64-bit for testing
Booting from Ventoy USB tool, which was used for Mint 21.2 install.

**Comment by Angedestenebres** [comment]
Hey :cat: 

Did you try to boot directly from the Mint ISO?
Because, it could be a Ventoy issue.

**Comment by becker44a** [comment]
After more testing, this notebook does boot Mint 22, either from Ventoy, or direct from bootable USB.  When booting earlier versions of Mint, the Grub splash screen is graphic mode, showing the round Mint icon.  When booting Mint 22, the splash screen is  text mode, w/ 4 dots beneath the text.  Some little time after the splash screen displays, it blanks, and some error messages appear, seeming to do with recognizing the graphic hardware.  However the boot is continuing.  I think my mistake was not waiting long enough - I thought the errors were fatal.  This issue can be discarded.

**Comment by Harry-W-Haines-III** [comment]
@becker44a Usually the person who opens the issue can close it or developers can.
