### ISSUE TITLE
warpinator: Please clarify some stuff

### ISSUE THREAD

**Issue by carlosmintfan** [linuxmint/mint22-beta#166]
Dear team,
please let me make a suggestion. To prevent accidental data loss for users using Warpinator, please
1. add a warning to notifications if files are getting to be overwritten
2. in the settings, change “require approval when files would be overwritten” to “... when files **and folders** would be overwritten” in reference to https://github.com/linuxmint/warpinator/issues/205 and what we discussed in the Matrix.
Thanks!

**Comment by clefebvre** [comment]
Thank you.
Bringing this to @mtwebster 's attention.
