### ISSUE TITLE
Ugly bold systray icons

### ISSUE THREAD

**Issue by carlosmintfan** [linuxmint/mint22-beta#168]
The network and sound systray icons in Mint 22 are too ugly and bold as opposed to Mint 21.3.

**Comment by Harry-W-Haines-III** [comment]
What desktop?

**Comment by carlosmintfan** [comment]
Cinnamon.

**Comment by Harry-W-Haines-III** [comment]
I have not noticed that at all and I use all the themes.
Screenshots please?

**Comment by carlosmintfan** [comment]
Old (good):
![old image](https://github.com/user-attachments/assets/39a6b5a0-7445-412e-ac34-6db1395f26e8)

New (bad):
![new image](https://github.com/user-attachments/assets/de7dc354-d51c-40dc-aa2f-f21e9470a30d)

Sorry for the difference in the network icon, I don't have wifi in my virtual machine where I test the beta and I'm not sure if there's a difference with the disconnected icon...

**Comment by Harry-W-Haines-III** [comment]
Which theme?  The symbolic icons vary from theme to theme.  When I switch to Mint-Y they seem to be the same as they have always been.

**Comment by carlosmintfan** [comment]
> Which theme? The symbolic icons vary from theme to theme. When I switch to Mint-Y they seem to be the same as they have always been.

All the default, Mint-Y. Could you paste a screenshot how you see them?
Note: Sorry, but I haven't applied any updates to the ISO. I only have unlimited internet at night...

**Comment by Harry-W-Haines-III** [comment]
Keep in mind I use a panel that is only 25 px high to maximize screen space.  So I think if there was a problem I would have noticed it right away.
Here is Mint-X
![mint-x](https://github.com/user-attachments/assets/cc259c87-de51-47f4-95d3-0a44edb881de)

Here is Mint-Y
![mint-y](https://github.com/user-attachments/assets/fa0d9452-c932-4304-a34f-9f512b03a314)

**Comment by carlosmintfan** [comment]
The network icon seems quite thick. And if you turn off audio, you should also notice the difference in the sound icon.

**Comment by Harry-W-Haines-III** [comment]
Well it has been that way now for a number of Linux Mint iterations.  I'm just trying to help.  Feel free to leave this issue open for the Mint Developers to look at if you feel it is still an issue.

**Comment by Angedestenebres** [comment]
Hey :cat: 

I confirm there is a difference about these icons between Mint 21 & 22, see below:

21.3:
![LM21-3-icons](https://github.com/user-attachments/assets/c18fe0de-3e8e-44e5-8428-e4465b5a55ba)

22:
![LM22-icons](https://github.com/user-attachments/assets/34cc4521-b7a1-4479-9d2f-865fdad9e9b8)

In fact, icons in Mint 22 are the same than LMDE 6:
![LMDE6-icons](https://github.com/user-attachments/assets/deaa124d-0351-4bb7-a19d-177d0da8ba7d)

However, I don't know why there is a change there so I will let a Mint member to check & explain what happen there :)

**Comment by Harry-W-Haines-III** [comment]
Just for reference here is what a complete 3rd party set of icons looks like for the symbolics in the notification tray area.   This is the nordic-blueish icon set.  I believe there is a slight difference in the spacing of the icons in Mint-Y from Mint-X.

![nordic-blueish](https://github.com/user-attachments/assets/3731fe96-ee2e-4c37-8861-6454fdf9bb64)

**Comment by mtwebster** [comment]
Mint-X and Mint-Y inherit quite a few symbolic icons from the adwaita-icon-theme package. They can and do make tweaks and changes to these icons that are out of our control.

LMDE6 and Mint 22 have much newer package base than 21.3, so not too much of a mystery.

Changes to the `network-wired-symbolic` icon since adwaita-icon-theme 42:
![image](https://github.com/user-attachments/assets/3adcbfb9-ed93-435d-a548-2318e718f17e)

Debian Bullseye/LMDE5 version: 3.38
Ubuntu 22,04/Mint 21 version: 41

Debian Bookworm/LMDE6 version: 43
Ubuntu 24.04/Mint 22 version: 46
