### ISSUE TITLE
iso: Memtest86+ in GRUB menu

### ISSUE THREAD

**Issue by InfoLibre** [linuxmint/mint22-beta#17]
Last version of Memtest86+ is 7.00. Could you update Memtest86+ in GRUB menu?

https://www.memtest.org

**Comment by Fantu** [comment]
Ubuntu 24.04 (base of the mint 22) have already 7.00: https://packages.ubuntu.com/noble/memtest86+

**Comment by Ensam57** [comment]
@Fantu The problem is not in the packages but in the GRUB menu of the LM DVD iso.

**Comment by InfoLibre** [comment]
![image](https://github.com/linuxmint/mint22-beta/assets/3955499/00e8bbda-353c-43f5-a8fe-3b2887caa44b)

**Comment by InfoLibre** [comment]
![image](https://github.com/linuxmint/mint22-beta/assets/3955499/16561fda-bcf5-4cce-95b0-86ba520042e0)

**Comment by Fantu** [comment]
So I suppose that installer image is not updated, 7.00 was synced from Debian months ago, before the 24.04 release freeze

**Comment by InfoLibre** [comment]
Yes, the installer image is not updated.

**Comment by clefebvre** [comment]
Fixed in next ISO.

**Comment by InfoLibre** [comment]
Thank you very much :+1:
