### ISSUE TITLE
Attempting to install Wine from WineHQ repos tries to delete Cinnamon and XOrg (and all the graphical applications)

### ISSUE THREAD

**Issue by canofjuice** [linuxmint/mint22-beta#170]
As the title says, i wanted to install Wine and all of it's dependencies to make sure everything is present for what i want to do (setup a game). While the install was going, i noticed that it was [**REMOVING NVIDIA DRIVERS AND XORG**](https://gist.github.com/canofjuice/7df5e55bf529301bc1def3e81274a15f) and quickly cancelled the command.

I used the WineHQ repos to have the latest version of Wine available to me.
Yes, i am aware that i'm using a Beta version as a daily driver but i think it's better to do this since i don't do much testing in virtual machines.

I hope this bug report will prevent [similar incidences](https://youtu.be/0506yDSgU7M?t=632) from happening when the full version comes out.

**Comment by canofjuice** [comment]
In addition to Wine, trying to install Steam also tries to remove my NVIDIA drivers and XWayland.
![image](https://github.com/user-attachments/assets/98e5f7dc-30c0-47de-8169-9e2f59ae1fa2)

**Comment by carlosmintfan** [comment]
LOL :) Yeah, I've also watched the Linus video where steam removes his desktop 😀 
Applying all available updates should solve the issue, although of course this shall never happen and apt should be smart enough to update your packages instead of removing them. Hmm.

**Comment by carlosmintfan** [comment]
Could it be you added a wrong release of the WineHQ repo? Please share the output of inxi -r in a terminal (if you aren't getting a list of apt repos, try capitalising the r).

**Comment by carlosmintfan** [comment]
But Linus got a warning that he was going to remove important packages and forced to write "Yes, do what I want". And you not?? Maybe Clem has to mark these packages as important??

**Comment by mtwebster** [comment]
The steam-installer package works fine here.

Have you added PPAs? You've got an unsupported nvidia driver version there (555).

If this happens on a clean install of the beta *without* additional repositories or foreign packages, then we can open it again.

**Comment by canofjuice** [comment]
> The steam-installer package works fine here.
> 
> Have you added PPAs? You've got an unsupported nvidia driver version there (555).
> 
> If this happens on a clean install of the beta _without_ additional repositories or foreign packages, then we can open it again.


Just did a clean reinstall, with Mint packaged drivers, issue doesn't occur.

Bummer, i wanted to use the absolute latest NVIDIA drivers to make sure games would work.

**Comment by Harry-W-Haines-III** [comment]
@canofjuice If you open up nvidia-driver-535_535.183.01-0ubuntu0.24.04.1_amd64.deb and look in the change log you will see this:

  * New upstream release (LP: #2067597)

 -- Eduard de Vidal Flores <eduard.de.vidal.flores@canonical.com>  Thu, 30 May 2024 12:53:28 +0200

Seems recent enough.  A lot of the 555 changes won't really help Linux Mint at this point as they are Wayland fixes that are more important for Wayland only desktops like Fedora and POP!_OS COSMIC.

**Comment by MiZoG99** [comment]
There is no 555 driver in Ubuntu repos. You have added an "untrusted" third-party PPA to your software sources. Bring this issue to PPA maintainers. I have an nvidia card, tested both 535 (default) and 550 (available) drivers, installed steam-installer, removed steam-installer, installed valve's steam deb installer, removed valve's steam installer during my tests and this never happened.

**Comment by canofjuice** [comment]
> @canofjuice If you open up nvidia-driver-535_535.183.01-0ubuntu0.24.04.1_amd64.deb and look in the change log you will see this:
> 
>     * New upstream release (LP: #2067597)
> 
> 
> -- Eduard de Vidal Flores [eduard.de.vidal.flores@canonical.com](mailto:eduard.de.vidal.flores@canonical.com) Thu, 30 May 2024 12:53:28 +0200
> 
> Seems recent enough. A lot of the 555 changes won't really help Linux Mint at this point as they are Wayland fixes that are more important for Wayland only desktops like Fedora and POP!_OS COSMIC.

Ah, thanks for the info! I just want to be on the bleeding edge when it comes to GPU drivers and the kernel. Especially since 6.10 will include NTSYNC for better performance with Windows games.

> There is no 555 driver in Ubuntu repos. You have added an "untrusted" third-party PPA to your software sources. Bring this issue to PPA maintainers. I have an nvidia card, tested both 535 (default) and 550 (available) drivers, installed steam-installer, removed steam-installer, installed valve's steam deb installer, removed valve's steam installer during my tests and this never happened.

Hmm, i didn't know 550 drivers were available from the regular Ubuntu repos. I Assumed they didn't ship it since they didn't show up in the driver utility so i added the PPA. Thanks in advance!
