### ISSUE TITLE
Weird checkboxes when right clicking on Transmission system tray icon

### ISSUE THREAD

**Issue by whoami1i1i1i** [linuxmint/mint22-beta#172]
Here's a screenshot:
![Untitled](https://github.com/user-attachments/assets/96391365-e538-4951-a67c-1becedc20b9c)
The newer version of Transmission in mint 22 added a system tray icon.
It works perfectly fine, there are just those weird checkboxes that shouldn't be on majority of the options.
It's the same in cinnamon and xfce versions.
It seems to be working properly in the mate version, though the spacing seems a bit odd, as if leaving space for a checkbox that isn't there, but it could very well be unrelated and intended spacing (changing to dark theme doesn't cause any problems too, I forgot to do so in this screenshot):
![image](https://github.com/user-attachments/assets/cfcb64ba-6e38-4783-8789-545da2a834a9)
In cinnamon and xfce the checkboxes that are supposed to be there work as expected, the extra ones don't do anything.

**Comment by mtwebster** [comment]
Transmission is using a different tech for displaying tray icons now - this is the menu it generates, unfortunately. We don't really have any control over this.
