### ISSUE TITLE
Matrix/mintchat

### ISSUE THREAD

**Issue by LAP47** [linuxmint/mint22-beta#173]
Installed linux mint mate' 22 beta on my ThinkCentre M93p and matrix is not in and or under the Internet option in Menu and it is installed because it can be found and launched from the Software Manager and through Welcome Center Help option. Doesn't happen on or in my Dell Latitude E4310.

**Comment by carlosmintfan** [comment]
Do you find it in the Webapp Manager?

**Comment by LAP47** [comment]
> Do you find it in the Webapp Manager?

No. I don't want to do that, though. I just want to click on Menu and then Internet and be able to click on Matrix and have it open that way like it does on my laptop.

**Comment by StercusMax** [comment]
I just fresh installed mint 22 in a vm and matrix is in the internet section, did you do a manipulation or something like this who could potentially do this?

**Comment by carlosmintfan** [comment]
@Ikytsu are you running the Mate edition?

**Comment by StercusMax** [comment]
Yes i am running Mate edition:
![image](https://github.com/user-attachments/assets/be0554ac-6108-4dc6-9069-d1ad677e3eda)

**Comment by StercusMax** [comment]
As you can see Matrix is here, in internet section

**Comment by carlosmintfan** [comment]
Hmm. @LAP47 have you tried reinstalling the Beta? Have you verified the integrity of your ISO?

**Comment by carlosmintfan** [comment]
Do you see any output in the terminal when running `webapp-manager`? What do you get from `cat ~/.local/share/applications/webapp*`?

**Comment by LAP47** [comment]
> I just fresh installed mint 22 in a vm and matrix is in the internet section, did you do a manipulation or something like this who could potentially do this?

No. I didn't. I don't do any customization's.

**Comment by LAP47** [comment]
> @Ikytsu are you running the Mate edition?

Yes. I am.

**Comment by LAP47** [comment]
> As you can see Matrix is here, in internet section

Yes. I know but it's not in mine.

**Comment by LAP47** [comment]
> Hmm. @LAP47 have you tried reinstalling the Beta? Have you verified the integrity of your ISO?

Yes. I have multiple times.

**Comment by LAP47** [comment]
> Do you see any output in the terminal when running `webapp-manager`? 

I see mintchat Firefox but I put that there manually because there's no minchat icon under the Internet options. I'll be back with the results from cat.

**Comment by LAP47** [comment]
What do you get from `cat ~/.local/share/applications/webapp*`?

No such file or directory.

**Comment by carlosmintfan** [comment]
```bash
cat ~/.local/share/applications/*
cat /etc/skel/*
cat /etc/skel/.local/share/applications/*
```

**Comment by StercusMax** [comment]
Hi @LAP47 ,
sorry for my useless answer, i wanted to say that webapp exists for me, after some look around, i noticed that even creating another account doesn't create your issue, so your issue isn't really related to the beta or if it is you should be more precise to explain to us how did you get it.
However if you want to fix this you have to do this:
````bash
sudo apt install mintchat
````
if it is in the internet section now you should be good, if it don't fix the issue:
go to the ~/.local/share/applications, verify if there is the webapp thing here, if it's present everything should just working fine so you should send us the .desktop content, if there is nothing under the directory, stay in it and just add a file named `webapp-OnlineChat4519.desktop` with this content:

[Desktop Entry]
Version=1.0
Exec=mintchat
Terminal=false
X-MultipleArgs=false
Type=Application
Icon=mintchat
Categories=GTK;Network;
MimeType=text/html;text/xml;application/xhtml_xml;
StartupWMClass=WebApp-OnlineChat4519
StartupNotify=true
X-WebApp-Browser=Firefox
X-WebApp-URL=https://www.linuxmint.com/matrix.php
X-WebApp-CustomParameters=
X-WebApp-Navbar=false
X-WebApp-PrivateWindow=false
X-WebApp-Isolated=true
Name=Matrix
Comment=Online Chat
Comment[es]=Chat en línea
Comment[fr]=Discussions en ligne



Best regards

(Additional thing, don't forget to say what you did with your installation to get this result, this could help the linux mint team to fix the issue if it's really one related about linux mint)

**Comment by LAP47** [comment]
> Hi @LAP47 , sorry for my useless answer, i wanted to say that webapp exists for me, after some look around, i noticed that even creating another account doesn't create your issue, so your issue isn't really related to the beta or if it is you should be more precise to explain to us how did you get it. However if you want to fix this you have to do this:
> 
> ```shell
> sudo apt install mintchat
> ```
> 
> if it is in the internet section now you should be good, if it don't fix the issue: go to the ~/.local/share/applications, verify if there is the webapp thing here, if it's present everything should just working fine so you should send us the .desktop content, if there is nothing under the directory, stay in it and just add a file named `webapp-OnlineChat4519.desktop` with this content:
> 
> [Desktop Entry] Version=1.0 Exec=mintchat Terminal=false X-MultipleArgs=false Type=Application Icon=mintchat Categories=GTK;Network; MimeType=text/html;text/xml;application/xhtml_xml; StartupWMClass=WebApp-OnlineChat4519 StartupNotify=true X-WebApp-Browser=Firefox X-WebApp-URL=https://www.linuxmint.com/matrix.php X-WebApp-CustomParameters= X-WebApp-Navbar=false X-WebApp-PrivateWindow=false X-WebApp-Isolated=true Name=Matrix Comment=Online Chat Comment[es]=Chat en línea Comment[fr]=Discussions en ligne
> 
> Best regards

It's not useless and no need to apologize. mint chat is already installed as far as  I know. It's just nowhere to be found under Internet. So like I said I'd have to launch it from Software Manager, Welcome Screen, or the terminal maybe but I don't even know how to do that.

**Comment by LAP47** [comment]
Results of ls in ~/.local/share/applications
![applications](https://github.com/user-attachments/assets/52e9fab8-8fc1-46c8-a5bd-8fc9640af744)

**Comment by LAP47** [comment]
Ho do I get you the .desktop content?

> ```shell
> cat ~/.local/share/applications/*

#!/usr/bin/env xdg-open
[Desktop Entry]
Version=1.0
Terminal=false
Type=Application
Name=Google Drive
Exec=/opt/google/chrome/google-chrome --profile-directory=Default --app-id=aghbiahbpaijignceidepookljebhfak
Icon=chrome-aghbiahbpaijignceidepookljebhfak-Default
NoDisplay=true
StartupWMClass=crx_aghbiahbpaijignceidepookljebhfak
#!/usr/bin/env xdg-open
[Desktop Entry]
Version=1.0
Terminal=false
Type=Application
Name=YouTube
Exec=/opt/google/chrome/google-chrome --profile-directory=Default --app-id=agimnkijcaahngcdmfeangaknmldooml
Icon=chrome-agimnkijcaahngcdmfeangaknmldooml-Default
NoDisplay=true
StartupWMClass=crx_agimnkijcaahngcdmfeangaknmldooml
Actions=Explore;Subscriptions

[Desktop Action Explore]
Name=Explore
Exec=/opt/google/chrome/google-chrome --profile-directory=Default --app-id=agimnkijcaahngcdmfeangaknmldooml "--app-launch-url-for-shortcuts-menu-item=https://www.youtube.com/feed/explore?feature=app_shortcuts"

[Desktop Action Subscriptions]
Name=Subscriptions
Exec=/opt/google/chrome/google-chrome --profile-directory=Default --app-id=agimnkijcaahngcdmfeangaknmldooml "--app-launch-url-for-shortcuts-menu-item=https://www.youtube.com/feed/subscriptions?feature=app_shortcuts"
#!/usr/bin/env xdg-open
[Desktop Entry]
Version=1.0
Terminal=false
Type=Application
Name=Chromebook Recovery Utility
Exec=/opt/google/chrome/google-chrome --profile-directory=Default --app-id=jndclpdbaamdhonoechobihbbiimdgai
Icon=chrome-jndclpdbaamdhonoechobihbbiimdgai-Default
StartupWMClass=crx_jndclpdbaamdhonoechobihbbiimdgai
#!/usr/bin/env xdg-open
[Desktop Entry]
Version=1.0
Terminal=false
Type=Application
Name=GitHub
Exec=/opt/google/chrome/google-chrome --profile-directory=Default --app-id=mjoklplbddabcmpepnokjaffbmgbkkgg
Icon=chrome-mjoklplbddabcmpepnokjaffbmgbkkgg-Default
StartupWMClass=crx_mjoklplbddabcmpepnokjaffbmgbkkgg
[Desktop Entry]
Name=Element
Exec=/opt/Element/element-desktop %U
Terminal=false
Type=Application
Icon=element-desktop
StartupWMClass=Element
Comment=A feature-rich client for Matrix.org
MimeType=x-scheme-handler/io.element.desktop;x-scheme-handler/element;
Categories=Network;InstantMessaging;Chat;
[MIME Cache]
application/xhtml_xml=WebApp-mintchat5160.desktop;
text/html=WebApp-mintchat5160.desktop;
text/xml=WebApp-mintchat5160.desktop;
[Desktop Entry]
Version=1.0
Name=mintchat
Comment=Web App
Exec=sh -c 'XAPP_FORCE_GTKWINDOW_ICON="element" firefox --class WebApp-mintchat5160 --name WebApp-mintchat5160 --profile /home/linux-mint/.local/share/ice/firefox/mintchat5160 --no-remote "https://app.element.io/#/home"'
Terminal=false
X-MultipleArgs=false
Type=Application
Icon=element
Categories=GTK;WebApps;
MimeType=text/html;text/xml;application/xhtml_xml;
StartupWMClass=WebApp-mintchat5160
StartupNotify=true
X-WebApp-Browser=Firefox
X-WebApp-URL=https://app.element.io/#/home
X-WebApp-CustomParameters=
X-WebApp-Navbar=false
X-WebApp-PrivateWindow=false
X-WebApp-Isolated=true

**Comment by LAP47** [comment]
> cat /etc/skel/*

~$ cat /etc/skel/*
cat: '/etc/skel/*': No such file or directory

**Comment by LAP47** [comment]
> cat /etc/skel/.local/share/applications/*

~$ cat /etc/skel/.local/share/applications/*
[Desktop Entry]
Version=1.0
Exec=mintchat
Terminal=false
X-MultipleArgs=false
Type=Application
Icon=mintchat
Categories=GTK;Network;
MimeType=text/html;text/xml;application/xhtml_xml;
StartupWMClass=WebApp-OnlineChat4519
StartupNotify=true
X-WebApp-Browser=Firefox
X-WebApp-URL=https://www.linuxmint.com/matrix.php
X-WebApp-CustomParameters=
X-WebApp-Navbar=false
X-WebApp-PrivateWindow=false
X-WebApp-Isolated=true
Name=Matrix
Comment=Online Chat
Comment[es]=Chat en línea
Comment[fr]=Discussions en ligne

**Comment by carlosmintfan** [comment]
> > cat /etc/skel/.local/share/applications/*
> 
> ~$ cat /etc/skel/.local/share/applications/* [Desktop Entry] Version=1.0 Exec=mintchat Terminal=false X-MultipleArgs=false Type=Application Icon=mintchat Categories=GTK;Network; MimeType=text/html;text/xml;application/xhtml_xml; StartupWMClass=WebApp-OnlineChat4519 StartupNotify=true X-WebApp-Browser=Firefox X-WebApp-URL=https://www.linuxmint.com/matrix.php X-WebApp-CustomParameters= X-WebApp-Navbar=false X-WebApp-PrivateWindow=false X-WebApp-Isolated=true Name=Matrix Comment=Online Chat Comment[es]=Chat en línea Comment[fr]=Discussions en ligne

So this is the file that automatically gets copied to every user account.I  think the most likely thing is that you deleted the web app by mistake. Copy the file that you find in the directory /etc/skel/.local/share/applications to /home/linux-mint/.local/share/applications, then you have the official webapp (it's right that mintchat from the software manager even works without you copying that file, that's fine). I find it strange that it's still gone after multiple reinstallations. But it can't be reproduced here, so the error seems to be on your side :/

**Comment by LAP47** [comment]
I didn't delete anything. It's not user error. I've installed it on two different machines and it's there on one of them and not on the other. I wouldn't even know how to delete it without some serious effort.

**Comment by LAP47** [comment]
> > > cat /etc/skel/.local/share/applications/*
> > 
> > 
> > ~$ cat /etc/skel/.local/share/applications/* [Desktop Entry] Version=1.0 Exec=mintchat Terminal=false X-MultipleArgs=false Type=Application Icon=mintchat Categories=GTK;Network; MimeType=text/html;text/xml;application/xhtml_xml; StartupWMClass=WebApp-OnlineChat4519 StartupNotify=true X-WebApp-Browser=Firefox X-WebApp-URL=https://www.linuxmint.com/matrix.php X-WebApp-CustomParameters= X-WebApp-Navbar=false X-WebApp-PrivateWindow=false X-WebApp-Isolated=true Name=Matrix Comment=Online Chat Comment[es]=Chat en línea Comment[fr]=Discussions en ligne
> 
> So this is the file that automatically gets copied to every user account.I think the most likely thing is that you deleted the web app by mistake. Copy the file that you find in the directory /etc/skel/.local/share/applications to /home/linux-mint/.local/share/applications, then you have the official webapp (it's right that mintchat from the software manager even works without you copying that file, that's fine). I find it strange that it's still gone after multiple reinstallations. But it can't be reproduced here, so the error seems to be on your side :/

I didn't delete anything. It's not user error. I've installed it on two different machines and it's there on one of them and not on the other. I wouldn't even know how to delete it without some serious effort. Maybe it's a hardware issue. Idk.

**Comment by LAP47** [comment]
> Copy the file that you find in the directory /etc/skel/.local/share/applications to /home/linux-mint/.local/share/applications

This worked. Thank you. So that must mean that it was never there because when I went to copy it over it didn't warn me that there was already a file there with that same name.

**Comment by LAP47** [comment]
> > > cat /etc/skel/.local/share/applications/*
> > 
> > 
> > ~$ cat /etc/skel/.local/share/applications/* [Desktop Entry] Version=1.0 Exec=mintchat Terminal=false X-MultipleArgs=false Type=Application Icon=mintchat Categories=GTK;Network; MimeType=text/html;text/xml;application/xhtml_xml; StartupWMClass=WebApp-OnlineChat4519 StartupNotify=true X-WebApp-Browser=Firefox X-WebApp-URL=https://www.linuxmint.com/matrix.php X-WebApp-CustomParameters= X-WebApp-Navbar=false X-WebApp-PrivateWindow=false X-WebApp-Isolated=true Name=Matrix Comment=Online Chat Comment[es]=Chat en línea Comment[fr]=Discussions en ligne
> 
> So this is the file that automatically gets copied to every user account.I think the most likely thing is that you deleted the web app by mistake. Copy the file that you find in the directory /etc/skel/.local/share/applications to /home/linux-mint/.local/share/applications, then you have the official webapp (it's right that mintchat from the software manager even works without you copying that file, that's fine). I find it strange that it's still gone after multiple reinstallations. But it can't be reproduced here, so the error seems to be on your side :/

What does the number 5160 and 4519 mean in the name WebApp-mintchat5160.desktop and webapp-OnlineChat4519.desktop respectively? WebApp-mintchat5160.desktop was already there before I copied anything over.

**Comment by carlosmintfan** [comment]
> > > > cat /etc/skel/.local/share/applications/*
> > > 
> > > 
> > > ~$ cat /etc/skel/.local/share/applications/* [Desktop Entry] Version=1.0 Exec=mintchat Terminal=false X-MultipleArgs=false Type=Application Icon=mintchat Categories=GTK;Network; MimeType=text/html;text/xml;application/xhtml_xml; StartupWMClass=WebApp-OnlineChat4519 StartupNotify=true X-WebApp-Browser=Firefox X-WebApp-URL=https://www.linuxmint.com/matrix.php X-WebApp-CustomParameters= X-WebApp-Navbar=false X-WebApp-PrivateWindow=false X-WebApp-Isolated=true Name=Matrix Comment=Online Chat Comment[es]=Chat en línea Comment[fr]=Discussions en ligne
> > 
> > 
> > So this is the file that automatically gets copied to every user account.I think the most likely thing is that you deleted the web app by mistake. Copy the file that you find in the directory /etc/skel/.local/share/applications to /home/linux-mint/.local/share/applications, then you have the official webapp (it's right that mintchat from the software manager even works without you copying that file, that's fine). I find it strange that it's still gone after multiple reinstallations. But it can't be reproduced here, so the error seems to be on your side :/
> 
> What does the number 5160 and 4519 mean in the name WebApp-mintchat5160.desktop and webapp-OnlineChat4519.desktop respectively? WebApp-mintchat5160.desktop was already there before I copied anything over.

The number is a random number to avoid collision so multiple webapps with the same name can be created. The 4519 is the official Linux Mint Matrix web app. 5160... I suppose you created one also called mintchat, the same as the bunch of other webapps you have?

**Comment by LAP47** [comment]
> > > cat /etc/skel/.local/share/applications/*
> > 
> > 
> > ~$ cat /etc/skel/.local/share/applications/* [Desktop Entry] Version=1.0 Exec=mintchat Terminal=false X-MultipleArgs=false Type=Application Icon=mintchat Categories=GTK;Network; MimeType=text/html;text/xml;application/xhtml_xml; StartupWMClass=WebApp-OnlineChat4519 StartupNotify=true X-WebApp-Browser=Firefox X-WebApp-URL=https://www.linuxmint.com/matrix.php X-WebApp-CustomParameters= X-WebApp-Navbar=false X-WebApp-PrivateWindow=false X-WebApp-Isolated=true Name=Matrix Comment=Online Chat Comment[es]=Chat en línea Comment[fr]=Discussions en ligne
> 
>Copy the file that you find in the directory /etc/skel/.local/share/applications to /home/linux-mint/.local/share/applications

How do I do this on Linux Mind Debian Edition 6 now? I tried to do it the same way but there's no .local in skel.

**Comment by carlosmintfan** [comment]
LMDE6 doesn't include mintchat (yet). You may send that file via email/warpinator/etc. from a Mint 22 to LMDE6 machine and put in /home/your-username/.local/share/applications
