### ISSUE TITLE
ubiquity: Language script not shown correctly

### ISSUE THREAD

**Issue by ovari** [linuxmint/mint22-beta#175]
[Jami](https://jami.net/) `User interface language` list does not show the languages correctly in Linux Mint 22 Cinnamon beta. This seems to be a regression as the languages show correctly with Linux Mint 21.3 Cinnamon.

Can this regression please be fixed?

Thank you

## Linux Mint 21.3 Cinnamon
![Linux Mint 21.3 Cinnamon](https://github.com/user-attachments/assets/1ff09b29-31b1-4ee4-9e9f-9ec8db00a527)

## Linux Mint 22 beta
![Linux Mint 22 beta](https://github.com/user-attachments/assets/ee0b44d2-1606-4dc5-8ee7-27e35e28e10b)

**Comment by clefebvre** [comment]
Adding fonts-noto-core fixes the isssue.

**Comment by clefebvre** [comment]
Added to next ISO.

**Comment by ovari** [comment]
> Added to next ISO.

Will fonts-noto-core be available in the Update Manager? If so, can you please advise when it will be available to check the fix?

Thank you

**Comment by Harry-W-Haines-III** [comment]
@ovari fonts-noto-core will not come thru the update manager.  I will be included in the next LM 22 ISO.  You can add it now thru the Software Manager.  You can also add fonts-noto-core in the live USB boot session.

**Comment by ovari** [comment]
Thank you for your comment.

Installing fonts-noto-core with the Software Manager and restarting computer fixed this issue.

Verified fixed.

Thank you once again.
