### ISSUE TITLE
file-roller: fails to open text files inside password protected zip archives

### ISSUE THREAD

**Issue by MiZoG99** [linuxmint/mint22-beta#176]
This might be related to another [issue already reported](https://github.com/linuxmint/mint22-beta/issues/138) but it seemed to me slightly different.
I'm testing Cinnamon beta.
When I compress a text file to zip with password protection and try to access this text file inside the window of archive manager (file-roller) I get a blank file instead of the expected password prompt (which is what I get when I do the same thing with file-roller on Mint 21.3)

![filerollerapparentbug](https://github.com/user-attachments/assets/bdfe1334-135c-46e7-99b5-f25166d56621)

Unlike the issue with encrypted 7z files reported previously, I still can extract successfully the content of zip from Nemo's right-click menu option "Extract Here"

**Comment by haggen88** [comment]
I confirm the bug

**Comment by clefebvre** [comment]
Fixed in 44.1 (but it's libAdwaita...)

**Comment by clefebvre** [comment]
Same issue with engrampa.

**Comment by clefebvre** [comment]
Fixed in file-roller 43.0+mint1

**Comment by carlosmintfan** [comment]
> Fixed in file-roller 43.0+mint1

Why are most pins on GitLab instead of GitHub?
