### ISSUE TITLE
celluloid: Resize option doesn't work properly

### ISSUE THREAD

**Issue by ruldc** [linuxmint/mint22-beta#177]
It's a problem with the preferences player setting, if I uncheck that box so that it doesn't maximize after the video resolution and it remains as it is when I resize it, it doesn't keep the setting every time the player restarts, the size is reset....

**Comment by clefebvre** [comment]
I can't reproduce this issue, it works perfectly fine for me.

**Comment by StercusMax** [comment]
Hi, after disabling this option:
![image](https://github.com/user-attachments/assets/58eb87e2-27a3-4cb2-9fe8-9634f7bed6c7)

i don't have any issue with the resize, everytime i restart the player it keeps the size i gave before, i tried also to restart the pc and nothing again. The size is kept. In conclusion it works fine in my side too.
