### ISSUE TITLE
Konversation IRC Client Is Good Replacement For No Longer Supported HexChat.

### ISSUE THREAD

**Issue by JesseLeePalser** [linuxmint/mint22-beta#178]
Hi,

When HexChat development stopped, I looked for a replacement for Linux Mint Cinnamon.
The closest one to HexChat that I could find was Konversation.

Works fine with Linux Mint 22 Cinnamon Beta.
Perhaps it can be added to the default apps before release?

Jesse Lee

**Comment by fredcw** [comment]
Mint has moved its chat network to Matrix so it has no need for an IRC client by default now. Besides, konversation brings in lots of KDE/qt6 dependencies with it.

**Comment by ivodopiviz** [comment]
https://github.com/SrainApp/srain looks like a better alternative, it's based on GTK 3.

**Comment by Harry-W-Haines-III** [comment]
However, if you are looking for a working Wayland GUI based chat client, Konversation is a viable alternative for IRC.  Yes it brings a lot of Qt dependencies with it but if you already have at one Qt based application installed you probably have a lot of them already present on your system.
