### ISSUE TITLE
Nemo: Incongruence with the translation of the Desktop folder name

### ISSUE THREAD

**Issue by anaximeno** [linuxmint/mint22-beta#18]
I have an installation set to Portuguese, the Desktop folder was created with the translation "Secretária" (which is a valid translation), but there's an incongruence with how the folder name is presented in Nemo, it is showing up as "Área de Trabalho" (which is also a valid and better translation, as well the one that the folder is translated to on current installations of LMDE 6).

![Screenshot_LinuxMint22_2024-06-30_15:47:35](https://github.com/linuxmint/mint22-beta/assets/63073056/5438aa5f-1959-4b26-94ed-61ca172df6c7)

![Screenshot_LinuxMint22_2024-06-30_15:47:57](https://github.com/linuxmint/mint22-beta/assets/63073056/32235771-6f9a-4a26-aa7d-a77679f3093c)

I guess the issue here is nemo not showing the real folder name and instead using an alternate translation, maybe knowing that the folder is a DESKTOP xdg-usr-dir it is translating and showing up the original name Desktop to the system locale instead of using the real name of the folder.

**Comment by mtwebster** [comment]
Nemo doesn't name the folders, but the sidebar entry is hardcoded.

The xdg-user-dirs-gtk-update program gets run at login to sync the names of your xdg (desktop, download, etc...) folders with the system locale.

https://www.unix.com/man-page/opensolaris/1/xdg-user-dirs-gtk-update/

I could change the sidebar so it uses the actual name of desktop folder (which in your case would be Secretária) but for existing installations this could have undesirable side effects (for some reason when I tried it it didn't rename my desktop folder, but created a new, empty one with the new name. 

I'm not sure which translation is best (to me it seems like Área de Trabalho would be but that's just with google translate), but we don't have any control over the folder names themselves.

**Comment by anaximeno** [comment]
I did some digging, and I found out that in the [**xdg-user-dirs** source code](https://gitlab.freedesktop.org/xdg/xdg-user-dirs/-/blob/master/po/pt.po?ref_type=heads#L30), 'Área de Trabalho' is being used for the Portuguese translation of 'Desktop', [**xdg-user-dirs-gtk-update** seems to be using the same translation](https://gitlab.gnome.org/GNOME/xdg-user-dirs-gtk/-/blob/master/update.c#L53) from the xdg-user-dirs, so I'm not sure where 'Secretária' is introduced as a translation here, but it doesn't seem to be a regression caused by downstream in mint.

> I could change the sidebar so it uses the actual name of desktop folder (which in your case would be Secretária) but for existing installations this could have undesirable side effects (for some reason when I tried it it didn't rename my desktop folder, but created a new, empty one with the new name.

For now, you probably should let it as it is currently then, I tested Dolphin and the behavior is similar (couldn't test for nautilus because it was messing with the session), so I'll close the issue.
