### ISSUE TITLE
cinnamon: Keyboard layout applets not showing up

### ISSUE THREAD

**Issue by caliarim** [linuxmint/mint22-beta#181]
The keyboard applet does not show its icon in the panel. If the panel edit mode is activated, the icon is visible. If I go to Preferences-Keyboard-Layouts, and move one of the keyboard layouts up, then down again, then the Keyboard applet icon appears in the panel. The same problem and workaround is described in [https://forums.linuxmint.com/viewtopic.php?t=325641](https://forums.linuxmint.com/viewtopic.php?t=325641).

**Comment by Harry-W-Haines-III** [comment]
@caliarim Is this an issue that existed before the Mint 22 Beta?  Or it is something that became worse/changed since LM 21.3?  We are really looking for new issues since LM 21.3 for the purpose of this bug reporting.

**Comment by billyswong** [comment]
That forum post described a problem when one try to use both fcitx and the built-in keyboard layout switching. One is supposed to use only one of them in a computer. Not both.

One may ask for a better UI hint so that users don't make such a mistake. But this will be a feature request.

**Comment by StercusMax** [comment]
> @caliarim Is this an issue that existed before the Mint 22 Beta? Or it is something that became worse/changed since LM 21.3? We are really looking for new issues since LM 21.3 for the purpose of this bug reporting.

According to the issue, the forum post https://forums.linuxmint.com/viewtopic.php?t=325641 is from 2020, so the issue was even on mint 20/before linux mint 20

**Comment by clefebvre** [comment]
This applet doesn't show up if you only have one layout, or if you're using a specific input method (such as Fcitx). This is by design.

**Comment by billyswong** [comment]
@clefebvre I wrote up an "idea" for this matter in the discussion page https://github.com/orgs/linuxmint/discussions/531
