### ISSUE TITLE
mintUpdate: when focused, the "info" tab doesn't show it's name

### ISSUE THREAD

**Issue by Qronikarz** [linuxmint/mint22-beta#182]
Weird small thing that I noticed when I clicked on mintUpdate icon while it was automatically refreshing. It can also be done manually. Just click refresh and wait for it to finish without switching windows or doing anything else. When it finished click on any entry and notice the "info/description" tab is missing it's name. Doesn't matter if native package or flatpak:
![native](https://github.com/user-attachments/assets/f8407985-85af-46d0-af7e-19c94f506c4c)
![flatpak](https://github.com/user-attachments/assets/745e8700-4f3f-4fc8-81d8-bc7acc16d85f)
However as soon as the window gets unfocused the text appears so it's not a big deal - for example making the screenshot or restarting the app.

**Comment by StercusMax** [comment]
Hi, exactly the same issue on my side and no matter what the language is.
