### ISSUE TITLE
Process Still Running After Log Out

### ISSUE THREAD

**Issue by JerryF1257** [linuxmint/mint22-beta#184]
I've noticed that when I log out as User2 (not the real name) and then log in as User1 (not the real name), User2 has a process called panel-10-xapp-s still running that uses about 13% of the CPU as listed from System Monitor.

It also happens if I log out as User1, then log in as User2.

**Comment by clefebvre** [comment]
in Cinnamon?

**Comment by StercusMax** [comment]
Tried to reproduce the issue in cinnamon, nothing appear to be anormal, maybe you could give more informations,  like what you are doing when logging off, the desktop environnement?

**Comment by Harry-W-Haines-III** [comment]
@JerryF1257 We still need more information about this issue as time is running short to resolve it.

**Comment by JerryF1257** [comment]
Xfce

**Comment by JerryF1257** [comment]
> Tried to reproduce the issue in cinnamon, nothing appear to be anormal, maybe you could give more informations, like what you are doing when logging off, the desktop environnement?

I had all apps closed, then logged out as User2 using the menu.  Logged in as the User1, then checked processes running using gnome-system-monitor.

**Comment by JerryF1257** [comment]
I had all apps closed, then logged out as User2 using the menu. Logged in as the User1, then checked processes running using gnome-system-monitor.

**Comment by StercusMax** [comment]
Hello @JerryF1257 ,
i can't reproduce your issue, i even tried to disconnect and connect into another user multiple times, but it works fine, without any process of the other user.

**Comment by StercusMax** [comment]
(on linux mint 22 xfce if you ask)
