### ISSUE TITLE
Why is some stuff on GitLab instead of GitHub?

### ISSUE THREAD

**Issue by carlosmintfan** [linuxmint/mint22-beta#187]
> Fixed in file-roller 43.0+mint1

Why are most pins on GitLab instead of GitHub?

_Originally posted by @carlosmintfan in https://github.com/linuxmint/mint22-beta/issues/176#issuecomment-2237180788_
            
Mint uses GitHub for most stuff, but why is there this secret GitLab place?

**Comment by adrianlopezgalera** [comment]
I don't understand you. That GitLab repository for File Roller belongs to Gnome. Clem has tested a working version of the program that does not depend on libadwaita.

Regards.

**Comment by carlosmintfan** [comment]
> I don't understand you. That GitLab repository for File Roller belongs to Gnome. Clem has tested a working version of the program that does not depend on libadwaita.
> 
> Regards.

https://gitlab.com/linuxmint
That stuff.

**Comment by clefebvre** [comment]
We use different tools for different purposes. We used bitbucket also for a while.

Github is usually used for our own software projects, for issues and pull requests. Gitlab is used for pins on upstream projects, we prefer to work with git commits than patches. Gitlab allows us to group repositories and it's less exposed than Github so it doesn't give the wrong impression (we don't maintain these projects, we just patch them, so we don't encourage issues/PRs there).
