### ISSUE TITLE
Unplugging a monitor (set as primary display) from a suspended laptop with closed lid and then opening the laptop causes a broken state

### ISSUE THREAD

**Issue by carlosmintfan** [linuxmint/mint22-beta#188]
1. Use an external monitor as primary display while the laptop lid is closed
2. Suspend the laptop and turn off the monitor
3. Plug out the monitor of the laptop
4. Open the laptop lid
5. The desktop is broken, it's half screensaver half desktop and you have to enter your password to make things work, and even then the desktop is some weird and you should restart cinnamon.
That happens on Mint 21.3 Cinnamon, not tested on Beta – however, even if it doesn't happen in the Beta anymore, it's a security issue as you see half the desktop while you should unlock and it's also a stupid and irritating issue as everything seems to hang while you have to guess you must enter your password without seeing the field :)

**Comment by clefebvre** [comment]
Not a regression.
Not tested with latest version.
Should be reported upstream in Cinnamon if not done already.
