### ISSUE TITLE
Intel audio not working (only listing dummy output)

### ISSUE THREAD

**Issue by johgh** [linuxmint/mint22-beta#189]
My hardware is this:

**Audio:
  Device-1: Intel Alder Lake-N PCH High Definition Audio vendor: Lenovo
    driver: sof-audio-pci-intel-tgl bus-ID: 00:1f.3 chip-ID: 8086:54c8 class-ID: 0403
  API: ALSA v: k6.8.0-38-generic status: kernel-api
  Server-1: PipeWire v: 1.0.5 status: active with: 1: pipewire-pulse status: active
    2: wireplumber status: active 3: pipewire-alsa type: plugin**

I tried installing pulseaudio (uninstalling pipewire), but still no audio. I think it seems a driver problem as no device is listed

![image](https://github.com/user-attachments/assets/f5539669-72c0-470e-9387-85c6e421e4ea)

I also tried Ubuntu 24.04 and same problem  (no audio)

Thank you for your support and effort!!
Jorge

**Comment by clefebvre** [comment]
Hi Jorge,

I hope you find a solution/workaround for this. 

I see this after a quick search, but you'll need to troubleshoot:
https://forums.debian.net/viewtopic.php?t=156215
https://forums.linuxmint.com/viewtopic.php?t=388636
https://github.com/thesofproject/linux/issues/4611

I'm closing it here since it's upstream from us.

**Comment by johgh** [comment]
> Hi Jorge,
> 
> I hope you find a solution/workaround for this.
> 
> I see this after a quick search, but you'll need to troubleshoot: https://forums.debian.net/viewtopic.php?t=156215 https://forums.linuxmint.com/viewtopic.php?t=388636 [thesofproject/linux#4611](https://github.com/thesofproject/linux/issues/4611)
> 
> I'm closing it here since it's upstream from us.

Thank you for the links, it helped a lot! I found that it was solved in 6.9 kernel so I just installed a very new kernel from ubuntu ppa. 

I installed linux-image-oem-24.04b (6.10 kernel) from canonical-kernel-team ppa.

So far, sound works and not any other problem, so I will stick with it for the moment

Thank you again!
