### ISSUE TITLE
Online Accounts Webdav/Nextcloud HTTP/2 Error: NO_ERROR

### ISSUE THREAD

**Issue by mrmelon54** [linuxmint/mint22-beta#190]
When trying to setup a webdav account I receive a popup with the error message "HTTP/2 Error: NO_ERROR"

```
(gnome-online-accounts-gtk:2550): libsoup-WARNING **: 11:27:36.005: (../libsoup/soup-connection-manager.c:84):soup_host_free: runtime check failed: (host->conns == NULL)
```

This can be bypassed by forcing my server to disable HTTP/2 communication. It appears like the client is not working properly.

Upstream: https://gitlab.gnome.org/GNOME/gnome-online-accounts/-/issues/356

**Comment by clefebvre** [comment]
Hi @mrmelon54,

gnome-online-accounts-gtk is only a frontend to libgoa-backend.

Note that libgoa-backend is made for GNOME, so if you report this issue upstream you should make sure it happens in GNOME using GNOME Control Center as the frontend.

**Comment by mrmelon54** [comment]
I tried it in VanillaOS too. I was setting up an account to report it upstream when I received your comment
