### ISSUE TITLE
dependencies: Removing fonts-ubuntu-classic removes important other packages

### ISSUE THREAD

**Issue by Harry-W-Haines-III** [linuxmint/mint22-beta#192]
This is on a fully updated LM Cinnamon system on bare hardware.  Someone brought this up in Matrix as they saw it in a VM.  Just tried it on my system to double check.  Expected results is it would remove fonts-ubuntu-classic but not all the other packages.  Even if it is upstream and not fixable before release, the issue could be added to the release notes.
See screenshot below:

![Screenshot from 2024-07-18 19-24-14](https://github.com/user-attachments/assets/c875d9f2-fe1a-4798-84b5-f7e1353097a0)

**Comment by billyswong** [comment]
What happen if you do `apt install fonts-ubuntu` and let it removes fonts-ubuntu-classic automatically?

**Comment by Harry-W-Haines-III** [comment]
This what happens with: apt install fonts-ubuntu

![Screenshot from 2024-07-18 19-46-04](https://github.com/user-attachments/assets/a07db539-7bb8-4c5d-8054-e1ceae33dea2)

**Comment by carlosmintfan** [comment]
Maybe Firefox just depends on "this or that fonts"?

**Comment by billyswong** [comment]
> Maybe Firefox just depends on "this or that fonts"?

Likely so. But it is still better for mintchat and firefox packages to not hard depend on any font packages but just take whatever default font setting set in DE.

Plymouth run in boot time and can't fetch per-user default font setting. So such hard dependency makes sense.

**Comment by clefebvre** [comment]
plymouth-label depends on fonts-ubuntu. That's upstream.

On our side we can potentiall drop the following dependencies: Firefox -> ubuntu-system-adjustments and ubuntu-system-adjustments -> plymouth-theme-spinner.

**Comment by clefebvre** [comment]
dep removed in u-s-a.

The rest of the issue is upstream.
