### ISSUE TITLE
Patch to engrampa as well?

### ISSUE THREAD

**Issue by billyswong** [linuxmint/mint22-beta#193]
Linux Mint is patching file-roller in https://github.com/linuxmint/mint22-beta/issues/176

However, Mint MATE is not running file-roller but engrampa. Will Linux Mint distribute a patched version of engrampa until a patched release is available in Ubuntu repo?

**Comment by clefebvre** [comment]
file-roller 43 isn't maintained upstream, this is already fixed upstream in 44.

For engrampa I forwarded the info to the MATE team on Matrix. Hopefully they react to this.

Failing that I'll create an issue for engrampa in github.

**Comment by billyswong** [comment]
Could it be this closed ticket? https://github.com/mate-desktop/engrampa/issues/510

**Comment by clefebvre** [comment]
It looks similar.
