### ISSUE TITLE
Release notes: possibly incorrect info on home directory encryption

### ISSUE THREAD

**Issue by Lanchon** [linuxmint/mint22-beta#194]
[wilma release notes](https://www.linuxmint.com/rel_wilma.php) state:

> ### Home directory encryption
>
> Benchmarks have demonstrated that, in most cases, home directory encryption is slower than full disk encryption.
>
> The move to systemd caused a regression in ecrypts which is responsible for mounting/unmounting encrypted home directories when you login and logout. Because of this issue, **please be aware that in Mint 20 and newer releases, your encrypted home directory is no longer unmounted on logout:** https://bugs.launchpad.net/ubuntu/+source/gnome-session/+bug/1734541.

however, it seems this was [fixed upstream in debian](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=765854#132).

please consider removing the outdated info from release notes if applicable, as some people have genuine use for home dir encryption.

**Comment by AtomicRobotMan0101** [comment]
The bug still exists.

- Log on to your account that uses ecryptfs (`foo`)
- Log out
- Log into another account
    `sudo su`
    `ls /home/foo`
    `cat /home/foo/nuclear_codes.txt`

All there to be seen :(

**Comment by Lanchon** [comment]
ok thanks, i never tried that installer option.

so i better close this then.
