### ISSUE TITLE
cinnamon: Buttons that have been scrolled outside the menu can be activated

### ISSUE THREAD

**Issue by DokterKaj** [linuxmint/mint22-beta#198]
When the menu is open, if you scroll down the application list then move the cursor above the menu, the description at the bottom right will change according to what app would be there if the menu was that large. Clicking will launch that app despite the cursor not being within the menu. This applies to the favourite list as well.
As for the category list, if there are enough categories and you scroll down until some are outside the menu, hovering the cursor above the menu will switch the application list to that category.

**Comment by fredcw** [comment]
duplicate https://github.com/linuxmint/cinnamon/issues/11123

**Comment by clefebvre** [comment]
Fixed in cinnamon 6.2.6
