### ISSUE TITLE
mintreport: wrong Ubuntu base in info tab

### ISSUE THREAD

**Issue by Qronikarz** [linuxmint/mint22-beta#2]
When looking at mintReport in the system info tab you can see
`Distro: Linux Mint 22 Wilma base: Ubuntu 22.04 jammy`

Shouldn't it be Ubuntu 24.04?

**Comment by clefebvre** [comment]
It seems to be an issue with inxi.

It calls `inxi -Fxxxrzc0`

**Comment by clefebvre** [comment]
It's on our side in ubuntu-system-adjustments.

**Comment by clefebvre** [comment]
Fixed in ubuntu-system-adjustments 2024.07.02-wilma.
