### ISSUE TITLE
l10n: Missing translation in a nemo extension

### ISSUE THREAD

**Issue by haggen88** [linuxmint/mint22-beta#20]
In Nemo-emblems the description still appears in English

- spanish
![nemo emblems](https://github.com/linuxmint/mint22-beta/assets/68134588/9af4a87b-21a6-4400-8be0-09f5cda2116b)

**Comment by rcalixte** [comment]
I can't replicate this with all of the latest updates for `cinnamon-l10n` and the Nemo extensions installed.

![nemo](https://github.com/linuxmint/mint22-beta/assets/10281587/6fa4931b-ae5c-4537-b9a1-9e6817efbb84)

**Comment by haggen88** [comment]
interesting... the same happens when installing the brazilian portuguese language.

![www](https://github.com/linuxmint/mint22-beta/assets/68134588/81f8e232-7144-4895-8ce5-6d513e16a709)

**Comment by rcalixte** [comment]
I have:
nemo-emblems 6.2.0
cinnamon-l10n 6.2.1

**Comment by haggen88** [comment]
I have the same.
otherwise... when installing the languages I get this error:

![l10n](https://github.com/linuxmint/mint22-beta/assets/68134588/22f4e0ea-ddc9-4ecd-8ece-d71d208c9929)

**Comment by adrianlopezgalera** [comment]
> In Nemo-emblems the description still appears in English

I am also a Spaniard. Does the title of the system menu also appear in English to you (installed system)?

![Captura de pantalla de 2024-06-28 16-05-34](https://github.com/linuxmint/mint22-beta/assets/77041822/0f22ab3a-35a1-45cd-a26d-b7f21743f965)

**Comment by haggen88** [comment]
![qq](https://github.com/linuxmint/mint22-beta/assets/68134588/4fb37b5d-0437-4dff-bb17-23166890b004)

**Comment by clefebvre** [comment]
![image](https://github.com/user-attachments/assets/794bd7d6-8b54-4ae8-96ab-65be37cab550)

![image](https://github.com/user-attachments/assets/7e44ef18-d279-4dcf-b71f-330c9fe5da5e)

**Comment by clefebvre** [comment]
![image](https://github.com/user-attachments/assets/af6fd90c-9f9c-4950-94d7-d90f4db664a5)

Something is weird here :)

**Comment by clefebvre** [comment]
![image](https://github.com/user-attachments/assets/6f57a2e0-f863-49e2-b5b4-deb02c70a988)

Moving the gettext call outside of the function helps here.

**Comment by adrianlopezgalera** [comment]
Hello, Clem. I am deeply grateful that you invest so much effort in searching for the origin of a translation bug. From experience, most distributions, and even application authors, have very little appreciation for the experience of non-English speaking users. For example, I have found in many programs (other than Mint) that certain strings do not appear translated because the templates used in Weblate, Transifex and others do not even include the strings to be able to translate them. It makes me nervous that a program is half translated due to the laziness of its authors.

Regards.

**Comment by clefebvre** [comment]
Thanks. It's taken very seriously for our own software, and to some extent for everything we ship by default.

I've a fix coming for this one anyway.

**Comment by clefebvre** [comment]
Fixed in nemo-emblems 6.2.1
