### ISSUE TITLE
cinnamon-settings-users: Clicking your own user causes a delay.

### ISSUE THREAD

**Issue by contrarybaton60** [linuxmint/mint22-beta#200]
This was talked about in the Matrix server, but I'll reported here.

How to reproduce:

Open cinnamon-settings-users either through CLI or clicking "Users and Groups" in System Settings.

Click on a user in the "Users" tab.

There is delay between clicking a user and the response given.

Here is the log in LM 22: https://pastebin.com/Pwuw9ZNJ

**Comment by contrarybaton60** [comment]
This is in a KVM/QEMU virtual machine with virt-manager 4.0.0 being the GUI, I forgot to clarify that.
![image](https://github.com/user-attachments/assets/8355c2fa-3337-4614-9c6e-f8600f02402d)

**Comment by StercusMax** [comment]
Same issue on my side, however it has only a delay when i click on the original user, i just recorded this to show what i am saying

https://github.com/user-attachments/assets/3e88b764-caff-4e0a-be0c-b77e495dab7d

i am using kvm as well

**Comment by StercusMax** [comment]
More informations in user2, my theory is confirmed, the only user who has this delay is the actual user used.
In user2:

https://github.com/user-attachments/assets/7250b41a-50cf-4371-80a1-0b82f725db91

**Comment by contrarybaton60** [comment]
https://github.com/user-attachments/assets/52de2640-4fbe-4b67-871c-a0dc77e30cb6
https://pastebin.com/6m89vNz5

I can confirm that.

**Comment by adrianlopezgalera** [comment]
I can confirm it. When clicking on a user, it takes a while for the right column to appear. I have a Ryzen 7 5700U, with four cores dedicated to the virtual machine, so it is not due to a lack of "power".

Regards.

**Comment by clefebvre** [comment]
![image](https://github.com/user-attachments/assets/bba170d2-48f8-4684-bc42-8ebeeb77d854)

**Comment by clefebvre** [comment]
`w -sh` segfaults for some reason... similar to https://gitlab.com/procps-ng/procps/-/issues/301.

Anyway, w -h works, we can just use that instead.
