### ISSUE TITLE
mintsystem: apt download requires root

### ISSUE THREAD

**Issue by sedererdj** [linuxmint/mint22-beta#201]
command "apt" from mintsystem requires root access for "download" command in non-root directory.
this problem extends to aptitude as well since it is a thin wrapper around apt cli.

**Comment by Angedestenebres** [comment]
Hey :cat: 

It was already the case in Mint 21.3:

![image](https://github.com/user-attachments/assets/f6aee8ce-a588-4066-a482-68ef68c2b713)

And it seems normal due to the fact that an `apt update` is done before the download of the package.

**Comment by sedererdj** [comment]
> Hey 🐱
> 
> It was already the case in Mint 21.3:
> 
> ![image](https://private-user-images.githubusercontent.com/21110485/350675080-f6aee8ce-a588-4066-a482-68ef68c2b713.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE0OTI3NzYsIm5iZiI6MTcyMTQ5MjQ3NiwicGF0aCI6Ii8yMTExMDQ4NS8zNTA2NzUwODAtZjZhZWU4Y2UtYTU4OC00MDY2LWE0ODItNjhlZjY4YzJiNzEzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzIwVDE2MjExNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTFmYjEzM2Q3YjMxMzA0ZmQwYjI2YzQ2Y2U4Y2UwZGNkZDI0NDA1MDA4ODRkOWNjMDUzNTFiMWNlNDJiOGY5YzMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.vSKZIaFJp5gKGYYmga4MNpli3UV5wKBnp47AKTFpKT0)
> 
> And it seems normal due to the fact that an `apt update` is done before the download of the package.

I see, even though i have a 21.3 installation i haven't done apt download there, this caught me by suprise.
I have seen novice users trying trying install stuff without updating apt cache so it looks like a good default.
