### ISSUE TITLE
GPU Hang & complete system freeze

### ISSUE THREAD

**Issue by tsjnachos117** [linuxmint/mint22-beta#203]
Hi. I have an integrated Intel Arrandale GPU, which doesn't seem to like Mint 22 for some reason. Whenever I try to log in (via lightdm), everything on the system freezes, including sshd. Not even magic-sysrq keys can shut the system down, so it's more than just an Xorg crash.

The last time this happened to me, I did get one error via sshd + dmesg:

    i915 0000:00:02.0: [drm] GPU HANG: ecode 5:1:020fffff, in Xorg [2197]

If I reboot with the `nomodeset` arg, the problem goes away, but I'm obviously going to be stuck in a lousy resolution. My CPU is an Intel Core i5 M-520.

Also: I reported the bug to the Ubuntu devs, as well, so maybe they can fix it? [See Here](https://bugs.launchpad.net/ubuntu/+source/linux/+bug/2073648). I won't go into as much detail here as I did there, so please give that report a read. Note my mention of specific kernel versions there.

**Comment by clefebvre** [comment]
Thanks Tyler. It's definitely upstream from us and likely to be a kernel regression indeed. I'm glad you found a workaround. Hopefully this gets fixed in newer kernel versions.
