### ISSUE TITLE
Installation creates superfluous (?!) folders on root file system

### ISSUE THREAD

**Issue by Rockets31** [linuxmint/mint22-beta#205]
I installed LM-22-cinn-beta on a testing drive. Installer copies following 'additional' folders from iso to installation drive:

- bin.usr-is-merged
- lib.usr-is-merged
- sbin.usr-is-merged

I think these folders are not used by operating system (FHS). 
Is it save deleting them?

**Comment by Angedestenebres** [comment]
Hey :cat: 

I didn't noticed that until your issue but you are right, I have these folders too. Moreover, they are empty on my side:

![VirtualBox_Linux Mint 22_20_07_2024_09_50_40](https://github.com/user-attachments/assets/3ccbc192-52fd-49c9-9bb2-8f8c853c5840)

**Comment by clefebvre** [comment]
This is part of the usrmerge and DEP17 M4 efforts from Debian. It's expected to be like that and prevents issues with APT and other programs.
