### ISSUE TITLE
Text not totally visible in unlock disk screen while booting system

### ISSUE THREAD

**Issue by Kwyrky** [linuxmint/mint22-beta#206]
When I boot into LM22 Beta Cinnamon which has been installed using LVM and full disk encryption I can not fully see the text next to the keyboard symbol.![image](https://github.com/user-attachments/assets/f2ac2f4c-c1a8-47ac-86be-0802b0ae36f1)

**Comment by LinuxOnTheDesktop** [comment]
Cf. #3. EDIT: and #19.
