### ISSUE TITLE
Font config error

### ISSUE THREAD

**Issue by InfoLibre** [linuxmint/mint22-beta#21]
During installation of LM Cinnamon, there's this error:

![Capture d’écran du 2024-06-30 22-00-12](https://github.com/linuxmint/mint22-beta/assets/3955499/1888c552-6e60-41b9-82b1-e8f26e92a63c)

**Comment by Harry-W-Haines-III** [comment]
Just an additional observation.  There are quite a few errors that occur in ubiquity.  Some because the target system does not have the items in existence yet.  You will notice the command option 'force' used frequently to get things done in the installer without stalling out for a failure.

**Comment by clefebvre** [comment]
Closing as observation. It's worth noting but it doesn't lead to known issues.
