### ISSUE TITLE
onboard: does not register accented characters

### ISSUE THREAD

**Issue by haggen88** [linuxmint/mint22-beta#22]
Test done in usb live mode, this problem does not occur with virtual keyboard.

[onboard.webm](https://github.com/linuxmint/mint22-beta/assets/68134588/c3fc7338-2b21-4603-91ea-efcb58ff4e95)

mint@mint:~$ onboard
/usr/lib/python3/dist-packages/Onboard/LayoutLoaderSVG.py:447: SyntaxWarning: 'str' object is not callable; perhaps you missed a comma?
  raise Exceptions.LayoutFileError("Unrecognized modifier %s in" \
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/Onboard/XInput.py", line 393, in _on_device_event
    callback(ev)
  File "/usr/lib/python3/dist-packages/Onboard/TouchInput.py", line 436, in _on_device_event
    self._on_button_release_event(self, event)
  File "/usr/lib/python3/dist-packages/Onboard/TouchInput.py", line 592, in _on_button_release_event
    self._input_sequence_end(sequence)
  File "/usr/lib/python3/dist-packages/Onboard/TouchInput.py", line 740, in _input_sequence_end
    self.on_input_sequence_end(sequence)
  File "/usr/lib/python3/dist-packages/Onboard/KeyboardPopups.py", line 447, in on_input_sequence_end
    keyboard.key_up(key, self, sequence)
  File "/usr/lib/python3/dist-packages/Onboard/Keyboard.py", line 1148, in key_up
    self._do_key_up_action(key, view, button, event_type)
  File "/usr/lib/python3/dist-packages/Onboard/Keyboard.py", line 1294, in _do_key_up_action
    self._release_non_sticky_key(key, view, button, event_type)
  File "/usr/lib/python3/dist-packages/Onboard/Keyboard.py", line 1664, in _release_non_sticky_key
    self.send_key_up(key, view, button, event_type)
  File "/usr/lib/python3/dist-packages/Onboard/Keyboard.py", line 1373, in send_key_up
    self.get_text_changer().insert_string_at_caret(key.code)
  File "/usr/lib/python3/dist-packages/Onboard/Keyboard.py", line 435, in insert_string_at_caret
    self._key_synth.press_key_string(text)
  File "/usr/lib/python3/dist-packages/Onboard/Keyboard.py", line 264, in press_key_string
    self.press_unicode(ch)
  File "/usr/lib/python3/dist-packages/Onboard/Keyboard.py", line 189, in press_unicode
    keysym = self._vk.keysym_from_unicode(char)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
SystemError: argument 1 (impossible<bad format char>)

**Comment by clefebvre** [comment]
I'll check the code.

Note that the virtual keyboard is libcaribou (completely different project than onboard).

**Comment by rik-shaw** [comment]
At slick-greeter login I cannot enter a `.` or a `,` as part of a password using the virtual keyboard. When pressing either of those virtual keys the first time, the virtual key turns grey like it is pretending to be a modifier or something like that, but it will not register the input. Not certain what other keys may have this issue. I didn't get a chance to check if the `.` and `,` are working normally after being logged in, but I thought they were? Will report back here.

**Comment by clefebvre** [comment]
This works with the latest onboard in Mint 21.x. I think we're looking at a regression with python 3.12.

**Comment by clefebvre** [comment]
It's to do with the removal of Py_Unicode in Python 3.12.

**Comment by billyswong** [comment]
Someone posted in Linux Mint forum https://forums.linuxmint.com/viewtopic.php?t=417738 that they are trying to revive / take on the Onboard maintenance through https://github.com/dr-ni/onboard. Any chance of collaboration?

**Comment by clefebvre** [comment]
We can definitely help.

We've an onboard fork (or at least the idea to review our dependencies on onboard/libcaribou) in our roadmap already. So I don't know if we'll go our own way on this or continue to use onboard going forward.

**Comment by dr-ni** [comment]
Dear all, accented characters are working in my my fork on raspberrypi 4 on bookworm 64bit.
Can you please check my v.1.4.2?

**Comment by clefebvre** [comment]
are you running Python 3.12?

**Comment by haggen88** [comment]
@clefebvre, haven't you thought of replacing Onboard with something like [Maliit keyboard](https://github.com/maliit/keyboard)  (which supports x11 and Wayland).

**Comment by dr-ni** [comment]
@clefebvre 
my raspberrypi has v3.11.2 but my ubuntu mate 24.04 amd64 has v3.12.3 and is also working with 'gtk' setting

**Comment by clefebvre** [comment]
> @clefebvre my raspberrypi has v3.11.2 but my ubuntu mate 24.04 amd64 has v3.12.3 and is also working with 'gtk' setting

I get the same issue with your git master.

**Comment by clefebvre** [comment]
> @clefebvre, haven't you thought of replacing Onboard with something like [Maliit keyboard](https://github.com/maliit/keyboard) (which supports x11 and Wayland).

I don't remember reviewing Maliit. It's a tough call to replace an entire app during the BETA phase anyhow.

**Comment by dr-ni** [comment]
> > @clefebvre my raspberrypi has v3.11.2 but my ubuntu mate 24.04 amd64 has v3.12.3 and is also working with 'gtk' setting
> 
> I get the same issue with your git master.

also with 'gtk' setting instead of 'XInput' ?

**Comment by clefebvre** [comment]
Yes.

**Comment by dr-ni** [comment]
hmm strange - on ubuntu mate 24.04 it is working

**Comment by haggen88** [comment]
> > 
> I don't remember reviewing Maliit. It's a tough call to replace an entire app during the BETA phase anyhow.

It is certainly not convenient to do something like this in a Beta, I meant to analyze it as a possible future replacement.

**Comment by clefebvre** [comment]
Yes, we'll definitely look into it amongst other solutions. We're not super happy with the situation with onboard+libcaribou anyway, even when they work fine.

**Comment by clefebvre** [comment]
Fixed in 1.4.1+mint4.
