### ISSUE TITLE
Comments are deleted on blog

### ISSUE THREAD

**Issue by InfoLibre** [linuxmint/mint22-beta#23]
On https://blog.linuxmint.com/?p=4719, two of my comments were not published. Is there censorship or a technical problem?

**Comment by haggen88** [comment]
Sometimes it happens that multiple comments are taken as spam. Perhaps it is simply a problem with the filtering system {sucuri ?}.

**Comment by InfoLibre** [comment]
Could it be solved?

**Comment by JosephMcc** [comment]
Were they deleted or not published? You are saying two different things. Please be clear about the issue. I don't know if it's still true but at one point things had to be manually approved. Not sure if that's still the case. It could be it just wasn't approved yet. Regardless, this has absolutely nothing to do with the beta. It hasn't even been released yet or a blog post done for it.

**Comment by InfoLibre** [comment]
It has absolutely to do with the beta because when a blog post will be done, the problem will be here again and again, since a long time. Not solving it and simply closing reports will not improve quality of Linux Mint.

**Comment by InfoLibre** [comment]
It has absolutely to do with the beta because when a blog post will be done, the problem will be here again and again, since a long time. Not solving it and simply closing reports will not improve quality of Linux Mint. And users will be tired to take time to make reports.
