### ISSUE TITLE
Error during first system updating

### ISSUE THREAD

**Issue by InfoLibre** [linuxmint/mint22-beta#24]
After installing LM Cinnamon, I reboot and make the first system updating. This error appears : 

![image](https://github.com/linuxmint/mint22-beta/assets/3955499/5ef600f9-5c04-4220-81b9-45877d14a92e)

**Comment by haggen88** [comment]
similar error
![update error](https://github.com/linuxmint/mint22-beta/assets/68134588/c635a184-8720-4a0b-95eb-e2e419008d3c)

**Comment by clefebvre** [comment]
This is only cosmetic. We've seen it for a while. It usually happens in live mode and then doesn't happen anymore. We don't know how to fix it or avoid it.

I'll close it here since we already looked into it and don't know how to tackle it.
