### ISSUE TITLE
Idea: reboot to Wayland/X11 shortcut

### ISSUE THREAD

**Issue by Qronikarz** [linuxmint/mint22-beta#28]
I was reading how to test Wayland on Cinnamon and due to me having encrypted boot and user auto login I may run into some issues?

https://forums.linuxmint.com/viewtopic.php?t=411761
> If you were curious and went into Wayland to see what it looks like, make sure to reboot before you return to standard Cinnamon Xorg session so everything works properly

So here's an idea. Make 2 new button shortcuts that would provide the option to reboot into other session.
1. Reboot to Wayland
2. Reboot to X11

It would be like some other Operating Systems allowing you to boot into Recovery or BIOS/UEFI.

I wanted to open this idea in linuxmint/wayland GitHub repository, but it only accepts bug reports.

**Comment by clefebvre** [comment]
This is a very niche use case. I'd suggest making your own scripts for that, or for someone to make an applet.
