### ISSUE TITLE
Encrypted disk password boot window is bigger

### ISSUE THREAD

**Issue by Qronikarz** [linuxmint/mint22-beta#3]
When using the installer with LVM to encrypt whole disk the window that appears during the boot is way larger than in previous Mint versions.

Also I think the Mint logo disappeared from there and for some reason one of the fans in the computer (either GPU or CPU) gets enabled when previously it didn't during that part. (the fan gets disabled after you enter the password so not a big deal, but kind of annoying)

**Comment by clefebvre** [comment]
Please provide a screenshot or photo of the screen.

**Comment by Qronikarz** [comment]
May be hard to convey. But I made a photo. Sadly I don't have 21.3 installed so can't compare it side by side.

I looked at youtube install tutorials to see if the older versions had logo, but no they didn't. Still it is visibly bigger than before and pixelated. (USB for scale, 24 inch FHD monitor)
![IMG_20240630](https://github.com/linuxmint/mint22-beta/assets/84787215/512cf588-6f76-48da-98fb-1015f77a2211)
And here just the text:
![IMG_202406302](https://github.com/linuxmint/mint22-beta/assets/84787215/78fae01c-429e-481a-8d9c-8175447cdfb7)

Also, related question. What does ml stand for? In tutorials on YouTube it was just "us"

**Comment by clefebvre** [comment]
It indicates your keyboard layout. I think ml is Malayalam.

**Comment by clefebvre** [comment]
Can you reproduce the issue with Ubuntu 24.04? I have a feeling this is upstream from us and to do with HiDPI changes in plymouth.

**Comment by Qronikarz** [comment]
I can't currently download such large files. I'll get back to it tomorrow.

> It indicates your keyboard layout. I think ml is Malayalam.
That's weird. Good thing I didn't use any Polish characters in the password. I have everything set up with Polish language so this feels like a bug.

**Comment by clefebvre** [comment]
What's in your /etc/default/keyboard?

**Comment by Qronikarz** [comment]
```
# KEYBOARD CONFIGURATION FILE

# Consult the keyboard(5) manual page.

XKBMODEL="pc105"
XKBLAYOUT="pl"
XKBVARIANT=""
XKBOPTIONS=""

BACKSPACE="guess"
```

**Comment by Qronikarz** [comment]
Reporting the results. All installed from the same USB stick on the same SD card without internet connection.

This is the Mint 21.3 boot:
![IMG_20240701mint21](https://github.com/linuxmint/mint22-beta/assets/84787215/89cc0c5f-db74-46d1-9e6a-0f40f18e883c)

This is the Ubuntu 24 LTS boot:
![IMG_20240701ubuntu24lts](https://github.com/linuxmint/mint22-beta/assets/84787215/8a6ee6ef-68fb-44d1-8d3a-6707c5099a3c)

Both Ubuntu 24 and Mint 22 have this encrypted boot enlarged and on both of them the fan keeps spinning (Mint 21.3 doesn't enable the fan). So probably you were right about it being upstream. 

As for the keyboard detection this issue was created: https://github.com/linuxmint/mint22-beta/issues/19
But as you can see on Ubuntu 24 LTS it's fixed and on Mint not.

**Comment by storm1ng** [comment]
@Qronikarz you can change the scaling by creating the file `/etc/plymouth/plymouthd.conf` with the following content:
```
[Daemon]
DeviceScale=1.0
```

Then simply run `update-initramfs -u` and the scaling should be changed to 100%.

However, the text for the keyboard layout remains as large as before.

**Comment by clefebvre** [comment]
Ignoring the scale as upstream. The keymap issue is tracked at #19 and has more info so I'll mark this one as a duplicate.
