### ISSUE TITLE
Text Editor (xed) - issue with dark theme

### ISSUE THREAD

**Issue by Angedestenebres** [linuxmint/mint22-beta#34]
As said in the title, when you display line number, there is an issue with all Mint themes in dark mode, see screen with Mint-Y as example:

![VirtualBox_Linux Mint 22_01_07_2024_20_10_31](https://github.com/linuxmint/mint22-beta/assets/21110485/c15f2e04-f6f0-4390-8a9a-ae55abef03a0)

Even without line number, you can see a white line in the left side:

![VirtualBox_Linux Mint 22_01_07_2024_20_13_05](https://github.com/linuxmint/mint22-beta/assets/21110485/4e8b4249-05d2-48fb-8631-97d3fb1affcf)

**Comment by haggen88** [comment]
#5  related

**Comment by Angedestenebres** [comment]
Thanks @haggen88 for the notice. I close my ticket as it's clearly a duplicate ;)
