### ISSUE TITLE
gstreamer1.0-vaapi: User session crashes when executing Rhythmbox atfer installation

### ISSUE THREAD

**Issue by adrianlopezgalera** [linuxmint/mint22-beta#35]
Hi!

I have installed Mint 22 beta (Cinnamon and Xfce) on Virtualbox for testing. My configuration is the default regional setting for Spain, with a Spanish language and a Spanish keyboard.

After a successful installation, I was testing that each program runs correctly. I discovered that starting Rhythmbox (either via the menu or the console) causes a sudden crash of the user session. That is, instead of starting the program, Mint immediately returns to the login screen.

**This bug occurs always** and in both versions tested. I need to install the Mate version, but possibly the same thing will happen. This error does not occur in the live version, only once installed.

Regards.

**Comment by Angedestenebres** [comment]
Hey :cat: 

Can you confirm that you installed the mint codecs?
If it's the case, you will have a similar issue with pix for instance.

In fact, this is an issue already identified for LMDE 6, see: https://github.com/linuxmint/lmde6-beta/issues/24#issuecomment-1727374620

**Comment by adrianlopezgalera** [comment]
> Hey 🐱
> 
> Can you confirm that you installed the mint codecs? If it's the case, you will have a similar issue with pix for instance.
> 
> In fact, this is an issue already identified for LMDE 6, see: [linuxmint/lmde6-beta#24 (comment)](https://github.com/linuxmint/lmde6-beta/issues/24#issuecomment-1727374620)

I checked the box for video codecs during installation. I'm going to try Pix. Thank you.

**Comment by adrianlopezgalera** [comment]
> Hey 🐱
> 
> Can you confirm that you installed the mint codecs? If it's the case, you will have a similar issue with pix for instance.
> 
> In fact, this is an issue already identified for LMDE 6, see: [linuxmint/lmde6-beta#24 (comment)](https://github.com/linuxmint/lmde6-beta/issues/24#issuecomment-1727374620)

Yes. Mint Codecs are installed (screenshot). This problem arises with Rhythmbox and Pix (too).

I think it's a severe bug. If the "gstreamer1.0-vaapi" package is affected, Linux Mint should offer a workaround. A system cannot be released if two important default applications cause a crash.

![Captura de pantalla de 2024-07-01 22-29-28](https://github.com/linuxmint/mint22-beta/assets/77041822/9ce70ee7-4c4a-41c4-b3b3-8aadd435dd19)

**Comment by User0755** [comment]
Hi!

My application calls gst-play-1.0 for dialog notification sound and this results in similar Cinnamon crash and immediate return to login screen. I have a strong feeling that these issues are related. And yes, mint codecs are installed here.

Reproducible always e.g. from terminal with:

$ gst-play-1.0 /usr/share/sounds/freedesktop/stereo/dialog-information.oga

// Tom

EDIT: OK, I followed the above mentioned linuxmint/lmde6-beta#24 and removed gstreamer1.0-vaapi:

sudo apt-get remove gstreamer1.0-vaapi

Now running the above gst-play-1.0 no longer crashes.

**Comment by becker44a** [comment]
I reviewed the LMDE6 issue at https://github.com/linuxmint/lmde6-beta/issues/24, and at the bottom Clem mentions 2 issues, and that this problem seems to be well known upstream.  I read the bugs.launchpad.net issue 1745345, and at the bottom of that issue, the comments suggest that the upstream people believe or did believe this issue was solved.  Obviously it isn't, and they need to know this ! !

**Comment by ajgreeny** [comment]
Same problem here with a KVM/QEMU virtual installation. 
It always requires two login attempts to get to the Xfce GUI and often crashes simply when opening the file-manager. I don't use rhythmbox so haven't yet tried that.
Ŕemoving gstreamer1.0-vaapi has solved the problem for me so far.

**Comment by clefebvre** [comment]
Information was added to the release notes to explain this issue and document the removal of the package and/or enabling 3D acceleration.
