### ISSUE TITLE
wayland cinnamon gtk flatpak theme is not being respected with cursor and theme 

### ISSUE THREAD

**Issue by pollux78** [linuxmint/mint22-beta#36]
installed linux mint 22 wilma and stremio doesnt like when i switch to wayland on cinnamon, as the theme on both the cursor and header  either stop seeing the theme that is being used or something else is happening

i have given flatpak access to my .themes and .icons but this doesnt solve the problem for me atleast 

i have ran the flatpak through the terminal aswell and their isnt a error that i see

under x11
![Screenshot from 2024-07-02 04-08-59](https://github.com/linuxmint/mint22-beta/assets/81181814/35736672-c34e-46fd-a6da-ac09c0bf2804)

under wayland
![Screenshot from 2024-07-02 04-11-01](https://github.com/linuxmint/mint22-beta/assets/81181814/a64a3dd8-3ea1-4f75-b77b-36b38adb113b)

**Comment by MiZoG99** [comment]
"Note: Do not report Wayland related bugs. We have a dedicated github repository for them at https://github.com/linuxmint/wayland."

[ReadMe](https://github.com/linuxmint/mint22-beta)
