### ISSUE TITLE
mintinstall: partial translation of software manager preferences

### ISSUE THREAD

**Issue by haggen88** [linuxmint/mint22-beta#37]
In addition, in the flatpaks section the text is not aligned correctly. There are cut words (c-ualquiera / Flatpa-ks), I checked in launchpad and the translations are not cut off.

![traduccion parcial software manager](https://github.com/linuxmint/mint22-beta/assets/68134588/ec10d5fb-4c55-41ef-b979-249afeaafc26)
- maximized window:

![w](https://github.com/linuxmint/mint22-beta/assets/68134588/3c5ee35c-bbc0-4ee6-98c5-c5af69fb9f0d)

![full installed-partial translation](https://github.com/linuxmint/mint22-beta/assets/68134588/2ea1578c-c3d6-40c5-abfa-8c272c46e367)

**Comment by clefebvre** [comment]
Fixed in git. Will be fixed in repo when translations and mintinstall are updated.
