### ISSUE TITLE
Thunderbird doesn't take in account system language

### ISSUE THREAD

**Issue by Angedestenebres** [linuxmint/mint22-beta#38]
As said in the title, see screen:

![VirtualBox_Linux Mint 22_01_07_2024_20_50_09](https://github.com/linuxmint/mint22-beta/assets/21110485/8f3bb787-88e2-49ae-81ba-deadb8ce6b78)

In my case, it should be in FR. After checking, the package `thunderbird-locale-fr` has been installed but not applied.

**Comment by adrianlopezgalera** [comment]
The same occurs in Spanish:

![Captura de pantalla de 2024-07-01 23-06-04](https://github.com/linuxmint/mint22-beta/assets/77041822/87a6809d-de57-4b89-9a51-903626b7749e)

**Comment by clefebvre** [comment]
Fix on the way.

**Comment by clefebvre** [comment]
Fixed in thunderbird 128.0esr+linuxmint2
