### ISSUE TITLE
DMZ-White and DMZ-Black cursors "inherit" the "separator" icon that previously was used.

### ISSUE THREAD

**Issue by adrianlopezgalera** [linuxmint/mint22-beta#39]
When selected DMZ-White or DMZ-Black cursors, they "inherit" the "separator" icon that previously was used. For example, if the user change from Bibata-Modern-Classic to DMZ-White, the "separator" icon (for columns) doesn't change accordingly.

![Captura de pantalla de 2024-07-01 22-53-49](https://github.com/linuxmint/mint22-beta/assets/77041822/4494cfac-b4cc-4298-a6ff-1578bb233bb4)

![Captura de pantalla de 2024-07-01 22-54-45](https://github.com/linuxmint/mint22-beta/assets/77041822/bdefb827-240e-481e-9993-1b81d77c7a0b)

**Comment by fredcw** [comment]
The specific cursor that's causing this problem (`col-resize`) is missing from the DMZ cursor themes in Mint.

It seems there's quite a few missing icons from the Ubuntu version. In the [AUR version](https://aur.archlinux.org/packages/xcursor-dmz) of the theme, they've added an extra 27 icon aliases.

**Comment by StercusMax** [comment]
After testing myself, there is no issue, the issue actually happen when you change of cursor theme when an application is open, if you close nemo and then reopen it the cursor theme shouldn't have any issues.

**Comment by adrianlopezgalera** [comment]
Hello. Yes. It is solved by restarting Nemo. However, it should be emphasized that this only happens with both sets of icons. The other icon sets change automatically without needing to restart Nemo or another application.

Regards.

**Comment by StercusMax** [comment]
I see what you mean. DMZ White is a pretty old cursor theme and no longer receives updates, so it has some similar issues. In my opinion, Linux Mint Cinnamon has the best DMZ integration. The best way to fix this is to make a fork of the DMZ White cursor or use an existing one like the AUR one, as Fred suggested. Despite these minor bugs, DMZ White remains quite usable by default.

**Comment by billyswong** [comment]
DMZ White is buggy also in web browsing. Visit https://developer.mozilla.org/en-US/docs/Web/CSS/cursor and test the cursor theme. In Mint 22 beta, one will need to change the cursor also through
```
sudo update-alternatives --config x-cursor-theme
```
then relogin to get the DMZ White cursor applied to Firefox. One can see that some cursor styles are missing, in particular the most common cases for web browsing need will be zoom-in and zoom-out.

@fredcw does this problem also occur in the "AUR" version?

**Comment by StercusMax** [comment]
@billyswong on my side on linux mint 22 cinnamon DMZ white cursor is already applied to firefox, are you talking about xfce version (i know there were some DMZ white issues there) ?

**Comment by fredcw** [comment]
@billyswong yes, there's a few missing in the AUR black and white versions as well: context-menu, vertical-text, no-drop, zoom-in, zoom-out.

**Comment by billyswong** [comment]
For other's reference: At this moment I am using https://gitlab.com/donut2/notwaita-cursor-theme their whitened version of Adwaita cursor theme in place of DMZ-White.

Neither Yaru nor Adwaita provide a white version of their cursor theme by themselves. The Mate cursor theme added a stylish gradient to the normal pointer which is too eye-catching already for my taste.

**Comment by StercusMax** [comment]
I know another mouse cursor like dmz white who is also great: https://gitlab.com/Enthymeme/hackneyed-x11-cursors

**Comment by StercusMax** [comment]
Anyway, that's a DMZ-White issue, the only way to fix this is to do a fork of dmz white or find an existing, i don't think it's the priority of beta, that's an existing bug since previous version.
Even with theses issues DMZ-White works pretty well for me in cinnamon, so that's really ok

**Comment by fredcw** [comment]
I think that Mint needs a bog standard, non-fancy, non-modern cursor theme as an option, similar to DMZ or Adwaita. DMZ now has too many missing cursors, and Adwaita, although installed as a dependency of gtk, can no longer be selected in the themes dialog https://github.com/linuxmint/cinnamon/commit/13b1ad104e88197f6c4e2d02ab2674c07254b8e8. Adwaita probably also has many missing cursors (it has 59 compared to Bibata's 145) e.g. nesw-resize, nwse-resize

btw. Adwaita can still be enabled with `gsettings set org.cinnamon.desktop.interface cursor-theme "Adwaita"`

I don't think there's any good alternative available in the repos.

@billyswong 
>At this moment I am using https://gitlab.com/donut2/notwaita-cursor-theme

Nice find, 123 cursors and scalable. I don't know if this could be included by default in Mint, as there's no apt package.

**Comment by adrianlopezgalera** [comment]
Hello everyone. Thank you very much for such good information. I am a very classic user. I don't like to change what I use if I don't have good reasons to do so. Overall I like the options offered by Mint, but I think, as fredcw has expressed, that Mint should maintain a classic (but updated) set of cursors. Bibata, for example, seems horrible to me.

I think that each new major version is a good opportunity to address small details that leave Mint behind other distributions or that simply do not take advantage of its full potential. In the long term, for example, developers will have to make drastic decisions about GTK because Gnome is going its own way.

Other desktop environments are also making decisions based on imitating Windows or Mac without taking into account what the user actually uses. I believe that sometimes those who only use a certain distro as a hobby and not as part of their job tend to express their opinion more than others who have been using it for more years. Therefore, I consider it essential that those of us who have been using Mint for many years also warn about the loss of "classic" functionalities.

PS: Sorry for my English.

Regards.

**Comment by StercusMax** [comment]
Hello, hope you have a good day/night depending when you are seeing this message, i totally agree with you, the bibata default one isn't really classic and the DMZ white is dying because of the lack of update. Linux mint should definitely have a cursor theme more classic who works well.

PS: Don't worry i have a worst english :D

**Comment by billyswong** [comment]
> I think that each new major version is a good opportunity to address small details that leave Mint behind other distributions or that simply do not take advantage of its full potential. In the long term, for example, developers will have to make drastic decisions about GTK because Gnome is going its own way.
 
I wish the mouse cursor switching mechanism can improve too. Currently the GUI dialogs in Cinnamon / MATE / Xfce for this only work partially and one need extra terminal commands for complete cursor theme and cursor size setting. This is far from ideal. But it will probably take some significant development time investment.

**Comment by fredcw** [comment]
@billyswong What do you mean by "mouse cursor switching mechanism"?

**Comment by billyswong** [comment]
@fredcw I mean when one wants to set a different mouse cursor theme or a different mouse cursor size, ideally it should be a one-stop solution for everything after login*. But currently it involves setting it in GUI dialog plus extra terminal commands. It is confusing for a setting that exist in GUI dialog already to require extra terminal commands. Instead of seeking the extra terminal command procedure, a user may just deem the GUI dialog or the whole DE broken. It also leaves a valid question, why can't the GUI dialog be better streamlined, for example run that terminal command in background automatically?

`*` It makes sense for the mouse cursor setting in login screen to need to be set separately in "Login Window". Multiple user accounts may want different mouse cursor setting. But after login? Not so much.

**Comment by fredcw** [comment]
@billyswong Do you mean the command `gsettings set org.cinnamon.desktop.interface cursor-theme "Adwaita"`? You can select any suitable cursor theme and theme size in the theme and mouse settings dialogs. Adwaita theme is only blocked because it has probably lots of missing cursors and isn't designed for use in other DEs, only GNOME. So I think it's right that it's blocked in the GUI.

**Comment by billyswong** [comment]
@fredcw Your command is just a CLI counterpart of the normal GUI operation (if one is not trying to select Adwaita cursor theme).

I mean commands such as
`sudo update-alternatives --config x-cursor-theme`
and
`sudo sh -c 'echo "export XCURSOR_SIZE=48" > /etc/profile.d/qt_mouse_pointer_size.sh'`
