### ISSUE TITLE
nemo-actions-layout-editor: Added or removed actions only appear/disappear after closing the layout editor

### ISSUE THREAD

**Issue by anaximeno** [linuxmint/mint22-beta#43]
1. Install a new action
2. Go to the layout editor, the newly installed action won't be there
3. Close the settings app and reopen
4. Go to the actions layout editor, now the new action will appear there
5. Now remove that action
6. Go to the layout editor, the removed action will still be there
7. Close and reopen the settings app
8. Go to the actions layout editor section, now the removed action won't be there anymore

The case is the same if you open the nemo actions layout editor from nemo and perform the operations while it is open.

**Comment by haggen88** [comment]
maybe it is related to #14

**Comment by anaximeno** [comment]
> maybe it is related to #14

Yeah, it seems to be related, so the commit https://github.com/linuxmint/nemo/commit/393d979a25c491d8e9b63a5b35727077bfb0a4c4 should potentially fix this also, I'll let them to close if that's the case.

**Comment by mtwebster** [comment]
Yes this should be fixed already, thanks
