### ISSUE TITLE
[Suggestion] Replace neofetch with fastfetch in Linux mint 22

### ISSUE THREAD

**Issue by whoami1i1i1i** [linuxmint/mint22-beta#46]
[Issue moved from the linuxmint issue tracker as it concerns the 22 release and would be more appropriate here.]
Neofetch has been deprecated and its repository archived a few months back.
A lot of people and distros are moving to actively maintained replacements like fastfetch because of that, and I think it would be a good idea for mint to include it by default instead of neofetch in the new 22 release.
Fastfetch is actively developed, has more features, and is much faster than neofetch.
For ubuntu-based distros it can be gotten through an official PPA found on the fastfetch GitHub page. For debian-based distros it's available in the debian repos from Debian 13 and up. Packaging it in both the mint and LMDE repos is also an option since the up-to-date deb for both ubuntu and debian based distros is available from the fastfetch GitHub page.

**Comment by ChooChooAl** [comment]
I would suggest screenfetch be evaluated.  No PPA needed to be used.

**Comment by whoami1i1i1i** [comment]
> I would suggest screenfetch be evaluated. No PPA needed to be used.

It can theoretically seem like a good alternative but its last update was 5 years ago, meanwhile neofetch's last update was 4 years ago.
Neofetch's repository *is* archived and screenfetch's isn't but based on the last update times I don't think it would be a good alternative.
On the contrary fastfetch gets updated very frequently, with the last update being a few days ago.

**Comment by billyswong** [comment]
An earlier discussion about neofetch vs fastfetch in the forum https://forums.linuxmint.com/viewtopic.php?t=418887

I consider fastfetch unsafe for general public as it is by default exposing one's IP address. And it is silly for trying to make an eyecandy such as neofetch "fast". Nobody is running it in background emitting output constantly.

**Comment by whoami1i1i1i** [comment]
> An earlier discussion about neofetch vs fastfetch in the forum https://forums.linuxmint.com/viewtopic.php?t=418887
> 
> I consider fastfetch unsafe for general public as it is by default exposing one's IP address. And it is silly for trying to make an eyecandy such as neofetch "fast". Nobody is running it in background emitting output constantly.

There is a big difference between local IP and public IP.
Fastfetch only displays local IP by default, which does not provide **any** sort of information except for the machines in your local network.
The IP that does expose an user, is unsafe to share is the public IP which fastfetch does not display by default.
Here's the part regarding this from fastfetch's FAQ:
![image](https://github.com/linuxmint/mint22-beta/assets/162520490/5cb3c8e7-f027-4bcb-a218-8df0969764f2)
There have been concerns in the thread you linked about the public IP being displayed instead of the local IP on non NAT routers but from my understanding it since has been fixed:
![Screenshot from 2024-07-02 11-13-24](https://github.com/linuxmint/mint22-beta/assets/162520490/0e5783db-66ad-4b02-a91a-b00f43630610)
from may 14th update:
![image](https://github.com/linuxmint/mint22-beta/assets/162520490/0815c44c-ec5b-4137-b939-4b695ac70eb7)
The speed factor does have its uses, for example people that configure their terminal to use fastfetch at every open.
But more importantly fastfetch is simply an actively maintained, more featureful alternative to now deprecated neofetch.

**Comment by Jeremy7701** [comment]
Since `neofetch` is installed by mint22 and it continues to work properly, and Debian have not seen fit to remove it on any security grounds, why not continue to use `neofetch`?
Obviously, a backup application will be needed in the future.

**Comment by whoami1i1i1i** [comment]
> Since `neofetch` is installed by mint22 and it continues to work properly, and Debian have not seen fit to remove it on any security grounds, why not continue to use `neofetch`? Obviously, a backup application will be needed in the future.

It's true that it still works and poses no security issues at the moment.
It will eventually have to be replaced for reasons like newer hardware and software compatibility among others.
Since replacing one package isn't resource intensive to implement, I think it would be a good idea for the 22 release, it being faster and displaying more information more accurately also being significant improvements.

**Comment by Jeremy7701** [comment]
But not a bug, since fastfetch is not part of Mint22.

**Comment by whoami1i1i1i** [comment]
> But not a bug, since fastfetch is not part of Mint22.

Yes, that's why I added "[Suggestion]" in the title.
It's a suggestion for the mint 22 release.
It's mentioned in the "to read" link in this repo's readme that suggestions and ideas are allowed.

**Comment by clefebvre** [comment]
Thanks for the suggestion. Most of my thoughts have been said above, but here goes anyway :)

For such a little tool it doesn't really matter when the latest commit occurred as long as it continues to work well. So far this has been the case and if something comes up it'll be easy to patch.

Now, the fact that neofetch is discontinued means that long term we'll either need to remove it or seek alternatives. It's good that the github repository was archived, it's a clear signal to the community and we're already seeing a multitude of new tools being developed as potential replacement. Which ones will get popular? which ones will get forgotten? which ones will we see in Debian/Ubuntu bases going forward? We don't really know yet.

I think right now we continue with neofetch. One of its key skill isn't just that it works, it's also that people know it as a command, so let's leave it in for now. In 2 years time, we can ask ourselves again, and by then hopefully everyone will agree on neofetch's natural successor.
