### ISSUE TITLE
mintstick: ISO verification doesn't work

### ISSUE THREAD

**Issue by carlosmintfan** [linuxmint/mint22-beta#49]
Because https://ftp.heanet.ie/mirrors/linuxmint.com//testing/sha256sum.txt isn't up to date and doesn't contain the 22 beta, mintstick can't verify the ISO image.

**Comment by clefebvre** [comment]
Email sent to Heanet.

**Comment by clefebvre** [comment]
Heanet is abandoning its mirror so we need a solution.

**Comment by clefebvre** [comment]
Fixed in mintstick 1.6.2.
