### ISSUE TITLE
Online Accounts gray text hard to read

### ISSUE THREAD

**Issue by mahtiankka** [linuxmint/mint22-beta#52]
Gray text on a gray background. I have a hard time reading the text. Would it be possible to change the color to either black or brown? I would be happy if the team could think about this. Image Mint 22 Wilma.
![graytext](https://github.com/linuxmint/mint22-beta/assets/48694735/5734c80d-c6d1-4dee-b01f-064b31db1201)

**Comment by clefebvre** [comment]
That's the libAdwaita style, it's not something we control unfortunately and it's not themable. The reason it's dimmed also is because the window isn't focused.
