### ISSUE TITLE
The hexchat config folder is still present in /home/.config/

### ISSUE THREAD

**Issue by whoami1i1i1i** [linuxmint/mint22-beta#54]
A pretty minor thing, the folder shouldn't be there since hexchat isn't being included by default anymore.
There's still some files leftover in there so it would be a few KB of saved space too.
I noticed a caja folder in /home/.config/ too even though I was running 22 cinnamon beta which doesn't include caja, but that might be there for a reason since cinnamon mint always came with a bunch of mate packages for some reason.
If it isn't there for a reason it could be deleted from the cinnamon (and presumably xfce) versions as well.

**Comment by clefebvre** [comment]
Removed from skel config in mint-artwork.

**Comment by Harry-W-Haines-III** [comment]
Saw this message this morning in an update:
dpkg: warning: unable to delete old directory '/etc/skel/.config/hexchat': Directory not empty
