### ISSUE TITLE
LibreOffice Display Issue With Toolbars White Text On White Background - I Am Using Cinnamon

### ISSUE THREAD

**Issue by JesseLeePalser** [linuxmint/mint22-beta#59]
Hi,

There is an issue with LibreOffice and the toolbars.
Please see attached screenshot.

Second Screenshot is my theme configuration...
Thanks!

Jesse Lee

![Screenshot from 2024-07-02 15-19-28](https://github.com/linuxmint/mint22-beta/assets/138352613/c0e116ff-38b1-4cb2-846c-58ec0c05c2da)

![Screenshot from 2024-07-02 15-23-09](https://github.com/linuxmint/mint22-beta/assets/138352613/251b1356-4bae-4a38-975c-9de47178061e)

**Comment by Harry-W-Haines-III** [comment]
Hello Jesse.  The icons are working correctly.  "Dark" icons means icons for dark background system themes so they should have some white in them to stand out.   The icon sets for "Light" themes are not really specified as such because it is assumed a theme with a light background is the default.

**Comment by Angedestenebres** [comment]
Hello,

In the configuration above with Systeme theme & The "automatic" one for icons, it should switch to Light / Dark mode according to the system theme.
And I confirm it doesn't switch for icons on my installation by switching to dark mode with Mint-Y :

[cinnamon-2024-07-03T120407+0200.webm](https://github.com/linuxmint/mint22-beta/assets/21110485/94ede550-36ac-4099-a41f-758b83a63c88)

**Comment by Harry-W-Haines-III** [comment]
They work fine here when you use the "Advanced settings..." so that might be the difference.

**Comment by Angedestenebres** [comment]
> They work fine here when you use the "Advanced settings..." so that might be the difference.

I'm sorry but even by using advanced settings, it doesn't work on my side:

[cinnamon-2024-07-03T145454+0200.webm](https://github.com/linuxmint/mint22-beta/assets/21110485/9ce14f61-872b-4034-a9c0-f43d0e85728e)

**Comment by Harry-W-Haines-III** [comment]
Are you doing this in a VM or bare hardware?

**Comment by JesseLeePalser** [comment]
Fresh install via USB drive to bare hardware

**Comment by Angedestenebres** [comment]
> Are you doing this in a VM or bare hardware?

On my side, this is on Virtualbox but I think this can happen on a physical hardware.

**Comment by clefebvre** [comment]
LO uses its own icons, not system icons, so they don't change according to the global theme settings. That's a limitation of LO.

**Comment by clefebvre** [comment]
What can be considered a bug or something we can fix, on our side, is that things look OK out of the box (i.e. with the default theme and the default LO theme).

**Comment by clefebvre** [comment]
I checked all three editions. The default is colibre everywhere, which looks OK out of the box both in light and dark themes. Switching to Colibre (dark) manually in LO makes it look even better with dark themes.
