### ISSUE TITLE
mintinstall: Verified flatpaks need app restart to show correctly

### ISSUE THREAD

**Issue by Qronikarz** [linuxmint/mint22-beta#6]
During first boot I always install all the apps I need before rebooting and when enabling the unverified flatpaks I noticed a weird thing. None of the flatpaks were verified. There was no problem installing them, but I didn't test it before enabling that option so don't know.

After finishing the installation I managed to make a screenshot where none of my installed flatpaks were verified:
![softfirst](https://github.com/linuxmint/mint22-beta/assets/84787215/96e32379-9421-44c7-a538-02c364df67cb)

Fortunately only restarting the software center fixed that issue:
![softnow](https://github.com/linuxmint/mint22-beta/assets/84787215/e226115f-47c4-471b-8d45-f588b91347af)

**Comment by haggen88** [comment]
I confirm the bug, the unverified emblem is shown even in flathub verified apps.

![bus mintinstall](https://github.com/linuxmint/mint22-beta/assets/68134588/eb631b28-ca53-4257-acd3-6b50f3b6cbed)

Even with verified apps already installed

![app ya instalada](https://github.com/linuxmint/mint22-beta/assets/68134588/446c3b6b-17f0-4ee4-a27b-e9bbccc579b7)


 Also if you don't activate the option to show unverified app the flatpak category appears empty.

[flatpak category.webm](https://github.com/linuxmint/mint22-beta/assets/68134588/50c789e7-0b54-44ff-b744-9191eda21e3f)

**Comment by haggen88** [comment]
The app search also excludes flatpak if the unverified app option is not activated.

[search flatpak apps.webm](https://github.com/linuxmint/mint22-beta/assets/68134588/e353f5de-05e6-4572-b547-f4b255828ba6)
