### ISSUE TITLE
xed: Default gtksourceview style doesn't work well with dark themes

### ISSUE THREAD

**Issue by Jeremy7701** [linuxmint/mint22-beta#60]
`/usr/share/nemo/actions/sample.nemo_action` is unreadable, at least in dark mode since most of the text is pale blue on black.

I suggest all colour coding is removed.

Part example:-
![Screenshot from 2024-07-02 20-24-20](https://github.com/linuxmint/mint22-beta/assets/52585119/37c86052-7de6-472e-96d9-3522f41343e2)

**Comment by mtwebster** [comment]
This Xed's default theme color for comments in many (most?) file formats. It's not specific to nemo action files. Select a different theme in Xed's preferences as a workaround for now. I'm not sure we can modify these themes, depending on what package provides them.

**Comment by Jeremy7701** [comment]
There is a solution : Xed allows you to choose a theme from its Edit -> preferences.
The 'Kate' theme looks quite good on a dark screen.
Sorry if I misinterpreted your use of the word "theme" !
![Screenshot from 2024-07-02 21-20-47](https://github.com/linuxmint/mint22-beta/assets/52585119/4d361531-8039-4c8d-9418-035011b79772)

**Comment by clefebvre** [comment]
I wonder if we could provide a light gtksourceview theme, and default to it. The one we default to right now, isn't always light, it's made for light, but doesn't hardcode the background color..

**Comment by clefebvre** [comment]
For the line numbers there's a regression between 21.x and 22:

![image](https://github.com/linuxmint/mint22-beta/assets/1138515/ff0a5d28-7cb6-49e7-9651-96ff5eece2d8)

They went from a relative rgba shade to a hardcoded color.

**Comment by clefebvre** [comment]
It comes from this commit upstream: https://gitlab.gnome.org/GNOME/gtksourceview/-/commit/7942b41c7929a86bf81a4f0bddbf11f6de8d82ef

**Comment by clefebvre** [comment]
Reverting this and switching the comments to grey gives a good result in both light and dark scenarios.

**Comment by clefebvre** [comment]
Fixed in xed 3.6.4 (with new default "Xed" style chosen).
