### ISSUE TITLE
Periodic Loss Of All Audio Until Reboot - I Am Using Cinnamon

### ISSUE THREAD

**Issue by JesseLeePalser** [linuxmint/mint22-beta#62]
Hi,

Sometimes I lose all audio and only a reboot fixes it?
I use headphones plugged into my computer's 3.5mm jack.

Below is system specifications:
[](https://termbin.com/0u80)

I hope this is a bug and can be resolved - I am rebooting at least once a day to restore audio...

Thanks!

Jesse Lee

**Comment by JesseLeePalser** [comment]
Sorry, I guess links are not allowed
[SystemSpecs.txt](https://github.com/user-attachments/files/16075071/SystemSpecs.txt)

**Comment by clefebvre** [comment]
Hi @JesseLeePalser, you need to find the cause of the issue. It could be anything so we're not at the stage where we can reproduce it here or fix anything.

I'd suggest using the forums/chat to seek and help and troubleshoot this. Check dmesg/logs etc..
