### ISSUE TITLE
Mint Sources becomes unusable after adding PPAs

### ISSUE THREAD

**Issue by kneekoo** [linuxmint/mint22-beta#64]
Mint 22 Beta Cinnamon

After adding the following PPAs, mintsources no longer works:
```
ppa:libreoffice/ppa
ppa:minetestdevs/stable
```

![mintsources-crash](https://github.com/linuxmint/mint22-beta/assets/566306/359d42c0-7971-4b73-bfef-5739b1e4eb15)

**Comment by haggen88** [comment]
#29 duplicate

**Comment by kneekoo** [comment]
Thanks, I haven't noticed that.
