### ISSUE TITLE
Choosing dark or light theme in libreoffice does not work (Cinnamon)

### ISSUE THREAD

**Issue by Iaokhan** [linuxmint/mint22-beta#67]
The light or dark theme does not work in Libreoffice. The theme remains that of the native package system. No problems with flatpak or another distribution like Fedora

**Comment by Angedestenebres** [comment]
Hey :cat: 

On my side, the theme change but the icons theme don't switch to light / dark.
Is it your issue?

**Comment by Harry-W-Haines-III** [comment]
It is working fine here.  This is for Cinnamon?  It wasn't mentioned what desktop.  I can change the theme internally that LibreOffice uses and it respects the system theme, including a custom theme I developed "Dusk".  Are you talking about the flatpack version or the one included with the distro?  Or were you talking about the writing surface not changing to dark with light text?

Please provide screen captures showing examples of the issues you have mentioned.

BTW, are you using the "Simplified Settings..." or the "Advanced Settings..." to change your system theme?  That could be the difference.

![dusk](https://github.com/linuxmint/mint22-beta/assets/45599505/2a52d77a-b1b5-4516-b004-531001e0cd9f)

![mint-y-dark](https://github.com/linuxmint/mint22-beta/assets/45599505/1fadf331-2da9-4d45-95c0-87f7be5e0dba)

![mint-x](https://github.com/linuxmint/mint22-beta/assets/45599505/ea70be63-1920-409b-bd46-b1a201e08c03)

![Screenshot from 2024-07-03 08-15-50](https://github.com/linuxmint/mint22-beta/assets/45599505/71120460-bac0-4895-a2af-25edce99b7dc)

**Comment by JesseLeePalser** [comment]
Related:  https://github.com/linuxmint/mint22-beta/issues/59

**Comment by Iaokhan** [comment]
![Screenshot from 2024-07-04 07-47-16](https://github.com/linuxmint/mint22-beta/assets/174593698/5954c406-aa17-4a24-b92f-0887372d9e05)
![Screenshot from 2024-07-04 07-48-01](https://github.com/linuxmint/mint22-beta/assets/174593698/d33d5db7-2e99-4fd0-a0ae-609504abbb93)

**Comment by clefebvre** [comment]
I can't reproduce, it all works fine here.

Make sure you've got System as the selected mode.

![image](https://github.com/linuxmint/mint22-beta/assets/1138515/edd3523a-1f61-47fb-887b-58fa54b7a39b)

**Comment by Iaokhan** [comment]
Pay attention to my setting, it's when the cinnamon theme is dark and I want a permanent light theme with Libreoffice. The toggle actually works if i'm in system mode in Libreoffice
