### ISSUE TITLE
Jitsi-Meet-electron doesnt run unde LM 22

### ISSUE THREAD

**Issue by LM-Rudi** [linuxmint/mint22-beta#71]
I tried to run jitsi-meet-electron ( Version 2024.6.0 ) installed from the actual *.deb from github.
It start and was terminated immediately with the following error:
ahmed@ahmed-TERRA-MOBILE-1749:~$ "/opt/Jitsi Meet/jitsi-meet"
LaunchProcess: failed to execvp:
/opt/Jitsi
[3025:0703/151451.255168:FATAL:zygote_host_impl_linux.cc(201)] Check failed: . : Das Argument ist ungültig (22)
Trace/Breakpoint ausgelöst (Speicherabzug geschrieben)
Same issue when I start it from the menu.

Trying ti start Appimage for jitsi meet ( also from github) I get the following error:

ahmed@ahmed-TERRA-MOBILE-1749:~/Downloads$ ./jitsi-meet-x86_64.AppImage 
[3174:0703/151553.345717:FATAL:setuid_sandbox_host.cc(158)] The SUID sandbox helper binary was found, but is not configured correctly. Rather than run without sandboxing I'm aborting now. You need to make sure that /tmp/.mount_jitsi-iIOh2F/chrome-sandbox is owned by root and has mode 4755.
Trace/Breakpoint ausgelöst (Speicherabzug geschrieben)

The *.deb jitsi meet was running on the same machine under LM 21.3 succesfully.

Hope it helps.

**Comment by Angedestenebres** [comment]
Hey :cat: 

After checking, it seems this is an upstream issue, see: https://github.com/electron/electron/issues/41066

**Comment by arxo** [comment]
Yes, this is due to the apparmor change that came with Ubuntu 24.04.
This comment in the above upstream issue also gives an example of a manually created apparmor profile for an electron app:
https://github.com/electron/electron/issues/41066#issuecomment-2186041169

**Comment by LM-Rudi** [comment]
Thanks for the info.
I try it with sudo sysctl -w kernel.apparmor_restrict_unprivileged_userns=0 as temporarly solution and jitsi-meet was started.
