### ISSUE TITLE
The app categories bar in the Start menu is tearing while scrolling in Cinnamon

### ISSUE THREAD

**Issue by vivomelette** [linuxmint/mint22-beta#73]
Steps to reproduce:

1. Open the Start menu
2. Make sure that not all app categories fit in the menu by resizing the menu and making the scroll bar appear (shown in the video)
3. Select one of the categories, then scroll down/up.

Expected behavior: the app categories bar will scroll perfectly

Current behavior: the bar is tearing while scrolling

Tested in VirtualBox after the fresh installation of Mint 22 BETA. Also reproducible in 21.3 Stable (I have this issue on real hardware with 21.3)

https://github.com/linuxmint/mint22-beta/assets/174616151/1fb96997-5d1c-4f56-bdb5-6d49579cfb93

**Comment by haggen88** [comment]
I confirm the bug in LM22-beta and 21.3

**Comment by adrianlopezgalera** [comment]
Yes, I can replicate it too. I think an option should be added to make the menu stay in a fixed position. This prevents a user from accidentally moving it. I know there is an option to revert to the default size, but I think it would be more user-friendly if, by default, the menu remained static.

**Comment by fredcw** [comment]
Cinnamon issue for this: https://github.com/linuxmint/cinnamon/issues/11760

**Comment by clefebvre** [comment]
Tracked in cinnamon.
