### ISSUE TITLE
Virtualbox black screen boot issue

### ISSUE THREAD

**Issue by iamdtms** [linuxmint/mint22-beta#74]
Actually it's kind of undefined issue it seems, but I'm still want to be reported: 

1. The installation process was successful
2. Virtual machine turned off, media removed
3. Image started, worked well
4. After some precize turn off/on round it started to give black screen after boot 
5. Unfortunately I'm did not checked logs, actually I do not know where can I debug the whole process 
6. So, it's functionan somewhat, and unfunctioan a bit sometimes. 

If it's represented in another issue, probably having the same one, I'm just wanted to be known.

**Comment by Angedestenebres** [comment]
Hey :cat: 

I use VirtualBox (version provided in repositories of LM 21.3) for my tests and didn't get this issue.
Maybe you can check if you have these requirements: https://github.com/linuxmint/mint22-beta/issues/57#issuecomment-2204371502

**Comment by iamdtms** [comment]
I'll check, probably that's it. Thank you.

**Comment by iamdtms** [comment]
Virtual video memory increment looks like solving this issue.

**Comment by iamdtms** [comment]
[Enabling virtual 3D Acceleration...](https://github.com/linuxmint/mint22-beta/issues/85)
