### ISSUE TITLE
goa-gtk: Incorrect rendering in VirtualBox with 3D acceleration

### ISSUE THREAD

**Issue by arxo** [linuxmint/mint22-beta#78]
- install LM 22 in VirtualBox 7 with 3D acceleration enabled
- insert guest additions image and install guest additions
- make sure you are logged into Cinnamon in default (accelerated) mode
- open Online Accounts from system settings
=> renders incorrectly - initially white window, gets partially redrawn as you move the mouse across the window
![image](https://github.com/linuxmint/mint22-beta/assets/43294041/2ededbd4-619b-4575-b27e-3e0935102094)
- select any account type
=> popup also renders incorrectly
![image](https://github.com/linuxmint/mint22-beta/assets/43294041/5015f360-a329-45cf-bec4-52fe08202220)

Running Cinnamon in software-rendered mode does not have this issue.

**Comment by adrianlopezgalera** [comment]
I cannot replicate your error after following the instructions you indicate. Perhaps there are more factors involved, such as the version of VirtualBox in use.

**Comment by clefebvre** [comment]
I wonder if it's using webkit... if that's the case we could disable acceleration. @mtwebster what do you think?

**Comment by contrarybaton60** [comment]
I am able to replicate this in a VM, running on Virtualbox 7.0.18 r162988
![image](https://github.com/linuxmint/mint22-beta/assets/110365948/95a37da0-ee60-4852-874d-dab0700ff8db)

**Comment by clefebvre** [comment]
![image](https://github.com/linuxmint/mint22-beta/assets/1138515/0102a2f0-37b7-4be6-ba24-1772ca4b8428)

**Comment by clefebvre** [comment]
OK, it's not a Webkit issue, it's a GTK4 issue. Disabling hw acceleration in GTK4 solves it.

![image](https://github.com/linuxmint/mint22-beta/assets/1138515/7c44ea1c-11d8-4499-b594-dbc2bd30064d)

**Comment by clefebvre** [comment]
Note: This affects all GTK4 apps.

**Comment by clefebvre** [comment]
The release notes were updated to provide clear instructions on how to set Virtualbox to avoid this issue.
