### ISSUE TITLE
No redshift included

### ISSUE THREAD

**Issue by Qronikarz** [linuxmint/mint22-beta#8]
Redshift isn't included in Mint 22.
I've heard that it stopped working, but there should be some alternative included by default.

I tried the recommend applet QRedshift, but due to me using the vertical task panel it only allowed to have the icon next to the Mint Menu Logo at the bottom and it complained about that.

The only other applet that worked - Redshift (by marvel4u) worked, but you need to enter the latitude and longitude manually so that's not exactly an option for newbies. Also it only has the red icon which looks out of place with other icons in that top area.
![redshiftvertical](https://github.com/linuxmint/mint22-beta/assets/84787215/f4092108-ff0f-4268-ba85-1dfae3b48373)

For some countries it would make sense to just pick one town and the problem is solved - like in Poland pick Warsaw just like the timezone.

**Comment by Harry-W-Haines-III** [comment]
Redshift is in the repositories and working here on Cinnamon.

apt list redshift*
Listing... Done
redshift-gtk/wilma,wilma,now 1.12+mint5+wilma all [installed]
redshift-qt/noble 0.6-3build3 amd64
redshift/wilma,now 1.12+mint5+wilma amd64 [installed]

![Screenshot from 2024-06-30 09-29-42](https://github.com/linuxmint/mint22-beta/assets/45599505/75151430-d627-4652-b125-e8ca069d4453)

**Comment by Harry-W-Haines-III** [comment]
Redshift is mentioned in the release notes:
https://www.linuxmint.com/rel_wilma.php

**Comment by Qronikarz** [comment]
> The Linux Mint team will consider developing an alternative.

That's good. I hope it will be soon enough. That's quite a common feature nowadays and the release notes said it best:
> Redshift can still be installed and used in manual mode by entering these coordinates in its configuration files but it's no longer useful out of the box for casual users.

**Comment by adrianlopezgalera** [comment]
I think it would be essential for Linux Mint to integrate an effective and simple alternative, as in other DEs. Maybe, some of the plugins already developed could be implemented some way. It should be enough for the user to be able to choose the temperature of the screen.

Regards.

**Comment by haggen88** [comment]
Currently there are alternatives that work on both x11 and wayland: https://gitlab.com/chinstrap/gammastep
