### ISSUE TITLE
blueman: manager unresponsive

### ISSUE THREAD

**Issue by adrianlopezgalera** [linuxmint/mint22-beta#80]
"blueman-manager" does not respond to selections on its interface (such as "exit" or "help"). If the daemon is not active, it freezes and returns an error message. It seems to me to be an error-prone program that, perhaps, should not be incorporated by default in this state.

![Captura de pantalla de 2024-07-03 22-32-54](https://github.com/linuxmint/mint22-beta/assets/77041822/efc4f7e1-70d6-4439-ae26-1b304cc9914c)

**Comment by clefebvre** [comment]
That's a bit harsh.

Please provide the steps to reproduce the issue.

**Comment by adrianlopezgalera** [comment]
Hi Clem,

I'm testing on two virtual machines running Linux Mint Beta (Cinnamon), one on my desktop and another on my laptop. Both have the same problem.

When running Blueman, the graphics window appears (everything correct). The menu options, although visible, do not react when I click on them. For example, if I click on "Help", nothing appears. The same with other options.

Whether the user interacts or not, half a minute later a window appears (capture in Spanish), which warns that the "Bluez" service is not running and the program crashes. Regardless of whether the service is running or not, I consider it a bug that the program supposedly allows you to interact with the menu options but nothing works. If the options are dependent on the service being running, they may be shaded or hidden in the meantime, or a temporary loading indicator may appear.

Regards.

![Captura de pantalla de 2024-07-13 22-24-34](https://github.com/user-attachments/assets/b0dacd55-fbac-43e0-bb42-7067f295176f)

**Comment by clefebvre** [comment]
It works perfectly fine when the daemon is running. I can reproduce your issue when there is no bluetooth hardware.

Blueman could handle this situation better but it's not a release blocker for us.

I'd suggest reporting this upstream at https://github.com/blueman-project/blueman/issues.
