### ISSUE TITLE
Thnderbird - wrong time stamp

### ISSUE THREAD

**Issue by SquigglyDog** [linuxmint/mint22-beta#81]
Testing out Thunderbird on Mint 22 BETA, by sending email to accounts in my Thunderbird. The time stamp for message received (from my account to my wifes account on same machine same TB) is 31 12 1969. Other emails received have correct time stamp and time stamp on affected email is correct in Sent Folder, just not Inbox

**Comment by clefebvre** [comment]
Just to make it clear... is the date set wrong by Thunderbird when composing the email?
or is displayed wrong when receiving it? (you can check that by reading the email from a different client)

Also, are you in live mode? This can have an impact on datetime.

**Comment by SquigglyDog** [comment]
Not sure I understand how to view it on another client. I forwarded it to a gmail address and it was dated correctly in the message header. I tried replying to my gmail address and in Gmail it had the worng message header (On 1969-12-31 19:00, wrote:).

**Comment by clefebvre** [comment]
If you're using imap you can connect to it from multiple clients.

**Comment by SquigglyDog** [comment]
Only pop3 is available from my provider, sorry
Just to clarify I have two accounts in TB my own and my wife's. It only happens if I send her an email or she sends one to me. It is marked in the sent folder with the correct date, but at the receiving end it is 1969

**Comment by clefebvre** [comment]
I think that date is the equivalent of 0 programmatically.

Are you in a live session or is the OS installed?

Also, is that in Cinnamon, MATE or Xfce?

**Comment by SquigglyDog** [comment]
I am in installed version of Cinnamon

**Comment by clefebvre** [comment]
It turned out we were shipping a BETA version of Thunderbird.

You can update it to version 128.0esr using the Update Manager. Hopefully this should take care of the issue.

**Comment by SquigglyDog** [comment]
Thanks. Hopefully some of the addons like Shrunken Image Resizer will work on 128 too

**Comment by SquigglyDog** [comment]
Well the update did not seem to change the way eamils between accounts on the same PC are handled, still get the 1969 timestamp. On a positive note and of more value the Shrunken Image Resizer now works

**Comment by clefebvre** [comment]
I'll mark this as upstream then. We're basically shipping the exact same version as Mozilla's here, so I don't think it's on our side.

https://www.reddit.com/r/Thunderbird/comments/x38o71/weird_email_error/
