### ISSUE TITLE
efi Stub: Warning: Failed to measure data

### ISSUE THREAD

**Issue by SquigglyDog** [linuxmint/mint22-beta#83]
On boot get warning message before GUI starts after Grub(black screen) `efi Stub: Warning: Failed to measure data for Event 1` followed by a code like OX00000b
It does not cause further problems and Mint boots fine affter that. It's a dual  boot with Mint 21.3 on another partition and Mint 22BETA with the warning
Ryzen 7600 CPU< Gigabyte B650M aorus-elite-ax 32 GB RAM (Corsair)

**Comment by clefebvre** [comment]
It might be worth investigating but in any case it's upstream from us:

PopOS: https://www.reddit.com/r/pop_os/comments/159f5o3/efi_stub_failed_to_measure_data_for_event_1_error/
Ubuntu: https://askubuntu.com/questions/1519290/efi-stub-warning-failed-to-measure-data-for-event-1-0800000000000000b-efi-stu

**Comment by SquigglyDog** [comment]
Just a note. Seems to be related to Secure Boot. When I disabled it message did not show up
