### ISSUE TITLE
cups-browsed: High CPU Usage on Fresh Install

### ISSUE THREAD

**Issue by Lenger34** [linuxmint/mint22-beta#86]
After a fresh installation and update of the kernel and packages, the cups-browsed process consumes a high amount of CPU resources, even though I haven't used the printer and only have a network printer connected. Restarting the cups-browsed service resolved the issue.
I have attached the logs, system information, and a dump of the process.
![top](https://github.com/linuxmint/mint22-beta/assets/113196887/69a27215-79e4-4b88-9231-badd34dd4628)
[core.1470.zip](https://github.com/user-attachments/files/16099939/core.1470.zip)

[cups_access_log.txt](https://github.com/user-attachments/files/16099850/cups_access_log.txt)
[cups_error_log.txt](https://github.com/user-attachments/files/16099851/cups_error_log.txt)
[system_info.txt](https://github.com/user-attachments/files/16099853/system_info.txt)

**Comment by MenthaSuaveolens** [comment]
After installing Linux Mint 22 Cinnamon. I wanted to connect to a hp-printer with Wifi-access. The standard app to set up a wireless printer showed the printer at once. I selected the proper printer but it looked as the app wasn't responsive at all. On the hand a message popped up that the printer was being installed. After a while the app behaved normal and showed the installed printer. The printer was ready to use. I will try this again soon.

**Comment by MenthaSuaveolens** [comment]
Reinstalled Linux Mint 22 Cinnamon. Wireless printer/scanner was detected automatically before I could select the app (fine!). I noticed that there are a lot of warnings with "[cups-driverd] Bad driver information file ..." (See error_log.txt).
 In demsg the following event was recorded : 
[error_log.txt](https://github.com/user-attachments/files/16118703/error_log.txt)
[  311.469000] show_signal_msg: 108 callbacks suppressed
[  311.469004] w[4198]: segfault at 4c ip 000062f696a74e73 sp 00007ffe4c65d060 error 4 in w[62f696a74000+3000] likely on CPU 3 (core 3, socket 0)

**Comment by Harry-W-Haines-III** [comment]
I just noticed this earlier this morning:

audit: type=1400 audit(1721188814.230:130): apparmor="DENIED" operation="capable" class="cap" profile="/usr/sbin/cupsd" pid=91899 comm="cupsd" capability=12  capname="net_admin"

cupsd is essential to Linux.  Why it was denied I have no idea.

**Comment by clefebvre** [comment]
Update ubuntu-system-adjustment and reboot, it re-enables user namespaces.
