### ISSUE TITLE
mintsources: Changing sources doesn't refresh cache

### ISSUE THREAD

**Issue by DigitalArchon** [linuxmint/mint22-beta#87]
After installing 22 beta, I got the usual message suggesting I change to a local repository. Normally when you change software source, it refreshes the apt package list with the new source. But on the beta it doesn't, which can obviously cause potential problems if the repos don't have identical packages and you start trying to install or update based on the prior repo.

**Comment by clefebvre** [comment]
On changes a button appears at the bottom:

![image](https://github.com/linuxmint/mint22-beta/assets/1138515/5f0fca74-1a9d-4fc0-b32a-8040e1b4d87e)

Clicking that button refreshes the cache.

**Comment by DigitalArchon** [comment]
Embarrassingly, i didn't even notice that. Was just used to the auto refresh. Thanks.

**Comment by clefebvre** [comment]
It's OK. It never auto-refreshed but in the past we had an infobar which was more noticeable that this no-relief button. It was a little TOO noticeable, now it's a little TOO un-noticeable :)

It's better like that imo though. It's a convenience button which doesn't need to be done as soon as the first change or for every single change, and we don't want it to get in the way like it did in the past.
