### ISSUE TITLE
relnotes: Updated Ubuntu font

### ISSUE THREAD

**Issue by Harry-W-Haines-III** [linuxmint/mint22-beta#9]
Since this directly impacts Linux Mint it might be more helpful to have it on the LM release notes because it is buried in the details of the [Ubuntu release notes ](https://discourse.ubuntu.com/t/ubuntu-24-04-lts-noble-numbat-release-notes/39890) that are linked to LM 22.

Updated Ubuntu font

A more modern slimmer version of the Ubuntu font family is now shipped as standard. Anyone wishing to return to the older Ubuntu font used in 22.04 can do so by installing the fonts-ubuntu-classic package.

Just a suggestion.  Thanks.

**Comment by NintendoManiac64** [comment]
I don't suppose this is the reason for #101?

**Comment by billyswong** [comment]
I expressed my concern on this issue in https://discourse.ubuntu.com/t/ubuntu-font-update-available-for-testing/34676/35
It is difficult to get the message across though.

**Comment by contrarybaton60** [comment]
> I expressed my concern on this issue in https://discourse.ubuntu.com/t/ubuntu-font-update-available-for-testing/34676/35 It is difficult to get the message across though.

From what it looks like, wouldn't it be better if it includes the font separately by default instead of having to replace the new ones by installing the fonts-ubuntu-classic package?

"For “local downgrade”, I mean the “classic” package is overwriting the font files with the old version, not re-introducing the old font alongside the new font. The two packages don’t coexist. They remove each other." from the link above.

**Comment by Harry-W-Haines-III** [comment]
This is part of the 'self destructive' behavior of Linux Nabobs that I don't like.  Just because they are the upstream bosses.  We had something that was working fine for a decade, Ubuntu Fonts on the Ubuntu side and creating a new document on the GNOME side.  So why change?
--
I use a high quality 32 inch 2560x1440 monitor and I noticed right away the new Ubuntu fonts were not as legible after a long day at the monitor as the old ones, especially if you are looking at another remote desktop also using the newer fonts.  I can't imagine what the new Ubuntu fonts look like on a 4K monitor at 27 inches or even 32 inches.
--
This is why Linux will always be a 'niche' operating system.  Knowledgeable end users will always be trying to work around nonsensical decisions from upstream.  Instead of working together to fix long standing bugs, upstream diddles with nonsense.
--
For example:  Will we ever have a clean, bug free, implementation of SAMBA?
Wayland is still in development after how many years now?

**Comment by clefebvre** [comment]
> > I expressed my concern on this issue in https://discourse.ubuntu.com/t/ubuntu-font-update-available-for-testing/34676/35 It is difficult to get the message across though.
> 
> From what it looks like, wouldn't it be better if it includes the font separately by default instead of having to replace the new ones by installing the fonts-ubuntu-classic package?
> 
> "For “local downgrade”, I mean the “classic” package is overwriting the font files with the old version, not re-introducing the old font alongside the new font. The two packages don’t coexist. They remove each other." from the link above.

This was reported here https://bugs.launchpad.net/ubuntu/+source/fonts-ubuntu-classic/+bug/2052390

**Comment by clefebvre** [comment]
Info added to release notes.
