### ISSUE TITLE
gstreamer1.0-vaapi: Unknown Bug forced me to return to login screen when tried to open Kazam

### ISSUE THREAD

**Issue by gmanskibiditoilet** [linuxmint/mint22-beta#90]
https://github.com/linuxmint/mint22-beta/assets/168109528/620652c1-f8b8-49b1-9a4c-a22f4880845f

Please help me fix this problem, i tried to open Kazam to record screenshots but when i opened the app an unknown bug forced signed out of my login screen....... again.

**Comment by Angedestenebres** [comment]
Hey :cat: 

Did you installed the codec package?
If yes, it's probably linked to this issue: https://github.com/linuxmint/mint22-beta/issues/35

**Comment by gmanskibiditoilet** [comment]
I did, but it crashed again. i tried to autopurge and install mint-meta-cinnamon, but the problem was still there. not fixed :((

**Comment by Angedestenebres** [comment]
This is not `mint-meta-cinnamon` to uninstall but `mint-meta-codecs` ;)

In fact, you can just remove `gstreamer1.0-vaapi`.
