### ISSUE TITLE
Evolution Mail fails to open

### ISSUE THREAD

**Issue by phred2** [linuxmint/mint22-beta#92]
Working off a bootable Cinnamon 22 beta USB :

Tested Evolution both by installing from Software Manager and by apt install evolution - both ways behave similarly.

Fired up bootable 22 beta USB, installed Evolution and could see from the installer Evolution is at 3.52.0.-1

After install tried to launch. The app does not appear (open) on the desktop. Monitoring with System Monitor process name "Evolution" appears and then disappears. The other evolution processes ( alarm-notify, calendar-factory, etc) remain.

After failed launch, then for the next few seemingly random mouse movements and clicks (3 or 4) the desktop goes blank for a second and then returns.

**Comment by phred2** [comment]
Cinnamon

**Comment by Angedestenebres** [comment]
Hey :cat: 

I tried to install it on my Mint 22 installation and it works:

![VirtualBox_Linux Mint 22_05_07_2024_13_41_50](https://github.com/linuxmint/mint22-beta/assets/21110485/e3912a7e-db6b-4ff3-a5b3-f904a9d05ebe)

I guess this is linked to the fact you use the liveISO. Maybe you can check by opening it via terminal if there is an error message.

**Comment by phred2** [comment]
Indeed! Installs and opens when using full install instead of Live ISO USB.
