### ISSUE TITLE
qt5: toolbar appearance issue in texmaker

### ISSUE THREAD

**Issue by Christophe76fr** [linuxmint/mint22-beta#93]
Hello, I am a daily user of texmaker. Trying mint22-beta, I am noticing an annoying issue in the way texmaker toolbar appear in this version, in comparison to how it is suppose to look like, and how it looks now.
I suspect this problem is qt-related. 
This is how it looks :
![Screenshot from 2024-07-05 13-36-28](https://github.com/linuxmint/mint22-beta/assets/174808436/058e304e-a1eb-49ac-8c55-922a5d544bed)
And this is how it is suppose to look : 
![image](https://github.com/linuxmint/mint22-beta/assets/174808436/15aa9a1b-de4a-4ead-bc58-2b6d5106d172)

I did not go further yet in the problems that might appear with this program using the new mint 22 beta.
Christophe

**Comment by Jeremy7701** [comment]
Probably just a later version - 5.1.3 or perhaps a theming difference.
A dark mode version looks like this:-
![Screenshot from 2024-07-05 22-14-11](https://github.com/linuxmint/mint22-beta/assets/52585119/ad4fa9fa-894e-4368-94b6-9e669f7d2bcc)

**Comment by Christophe76fr** [comment]
Here is how the flatpak version (last version) looks under Mint DE 5 : 
![Capture d’écran du 2024-07-06 14-43-24](https://github.com/linuxmint/mint22-beta/assets/174808436/909b330b-aa6d-4507-ba52-ee261f46fe4e)
So the issue with the appearance does not seem related to a new version of TexMaker.
I am wondering : as it seems that TexMaker is written with QT5, maybe it is a problem with QT5 under Mint 22 beta.
I must add that the same problem appeared with Mint DE 6, that is partly why I stayed with Mint DE 5.

**Comment by Jeremy7701** [comment]
Not sure what the problem is? Is it just the colour scheme?
The Mint22 distro version is 5.1.3 and whilst there is a later 5.1.4 version, you will get a warning saying that this is not recommended.
I  don't know anything about flatpack, since I have **never** installed a flatpack app - ever.

**Comment by Christophe76fr** [comment]
Yes, it's a bug in the colour appearance of the toolbar. It's not how it's meant to look like. For example, on the very 5.1.3 version, on windows, it looks like this : 
![image](https://github.com/linuxmint/mint22-beta/assets/174808436/50d98d17-8351-47a8-b049-1ccaa0066016)

**Comment by Jeremy7701** [comment]
I would suggest that it's because texmaker is a QT5 app, and so won't support the Mint (GDK) themes. I would imagine the same effect will occur in LMDE6.
You could try a dark theme - **which will affect most apps** - if you really need a closer match for the texmaker colour scheme.
Dark theme version:-
[https://github.com/linuxmint/mint22-beta/issues/93#issuecomment-2211421846](https://github.com/linuxmint/mint22-beta/issues/93#issuecomment-2211421846)

**Comment by Christophe76fr** [comment]
The same effect occurs in LMDE6. What has changed so much between LMDE5 and LMDE6 that QT5 apps don't look alright with the newer cinnamon desktop ?

**Comment by Christophe76fr** [comment]
Do you think this bug will be investigated ?

**Comment by Jeremy7701** [comment]
I would guess that it won't, since Mint doesn't provide any native QT5 apps.
I find that theming differences between LMDE5 and LMDE6 to be very minor - except that LMDE6 has much better support for dark themes.
Since LMDE5 has just reached "end of life", so no security fixes  will be issued for it.
So you should do the upgrade soon!

**Comment by Christophe76fr** [comment]
Would compiling TeXmaker from the source would change something ?

**Comment by Jeremy7701** [comment]
It would still be a Qt5 app.

**Comment by Christophe76fr** [comment]
I tried changing the mint theme to Legacy (Mint-L). The same appearance error appears. So it seems it's not related to the new Mint-Y theme but to the way QT5 apps are rendered with LM 22 or LMDE6. Is it a regression ?
I should add that another problem appears when trying to install TeXmaker : I get an error "Error while installing package 79.4872".

**Comment by Jeremy7701** [comment]
The screen appearance isn't a bug or an error.
QT5 apps don't depend on Mint theming.
An install error is a lot more serious - but you will need to provide a lot more information:-
Does it prevent a successful install of TeXmaker ?
Is it a reproducible?
Do you get any information in your logs?
etc

**Comment by Christophe76fr** [comment]
It does not prevent a successful install of TeXmaker. To reproduce, simply try install TeXmaker using software manager.
I did not get information in my log.

**Comment by Jeremy7701** [comment]
Why did you say you got an "Error while installing package 79.4872"?
What caused this?
Did you install Texlive first?
A typical install should follow something like [https://www.linuxfordevices.com/tutorials/ubuntu/install-tex-live-texmaker](https://www.linuxfordevices.com/tutorials/ubuntu/install-tex-live-texmaker)
Note that a minor screen appearance difference is not a bug, especially for LaTeX - its the output that matters.

**Comment by Christophe76fr** [comment]
Just like I said. I just searched "texmaker" in the software manager and installed it without installing TeXlive first. That's exactly how it worked flawlessly in the previous versions of Linux Mint. The "error while installing package 794872" appeared in a window that opened shortly before the installation ended.

**Comment by Christophe76fr** [comment]
I am not home at the moment. I am wondering if the same appearance issue also happen in a standard ubuntu 24.04 install. I cannot try. If you could check... that would maybe help.

**Comment by Jeremy7701** [comment]
Then you should have reported the error - probably as a new issue with full details on how you produced it.
Does this error (or warning) stop you using texmaker?
Try installing Ubuntu in a VM yourself - and find error diagnostics.
Other people aren't going to attempt installing 5GB of packages if you don't give full details.
Report your findings, either to texmaker or to Mint.

You should close this issue about a minor cosmetic difference in the colour scheme.

**Comment by Christophe76fr** [comment]
The error during install does not appear when using a virtual machine (I used to try LM22 with an usb stick with persistence). 
For the toolbar issue, I have found clues, but I don't know if it's relevant : 
- Installing texmaker on ubuntu 22.04 : no problem with the toolbar.
- Removing the qt5-gtk2-platformtheme package from LM22 does solve the problem of the toolbar too.
- Installing qt5ct, qt5-gtk2-platformtheme and adding the line "QT_QPA_PLATFORMTHEME=qt5ct" in /etc/environment makes the problem appear in ubuntu 22.04.
So the problem seems related to the way qt5-gtk2-platformtheme "renders" TeXmaker.

**Comment by clefebvre** [comment]
Removing qt5ct fixes the issue. We'll do that.

We've got other reasons to do so also:

- It's weird to ship qt5ct and not qt6ct...
- These app look out of place in the DE to casual users who don't understand what they're for
- If done properly this would either be integrated in the DE settings, or work out of the box with all Qt versions without configuration
- Our experience with Qt is that Qt itself tries to integrate, sometimes our efforts collide, like here.

XApps could potentially help improve compatibility ootb between Qt and GTK desktops. In the meantime, if adding qt5ct to Mint 22 causes issues, we're better off letting Qt apps use their native style by default.
