### ISSUE TITLE
Vivaldi browser does not install

### ISSUE THREAD

**Issue by Ferryfolk** [linuxmint/mint22-beta#94]
Vivaldi browser does not install on 22 beta. (No problem with 21.3).

**Comment by Ferryfolk** [comment]
Just to clarify, Vivaldi does not install in Live session.

**Comment by Angedestenebres** [comment]
Hey :cat: 

Tried to install Vivaldi (on installed LM 22) with the deb version from their website and it works on my side:

![VirtualBox_Linux Mint 22_05_07_2024_19_13_56](https://github.com/linuxmint/mint22-beta/assets/21110485/4dcdf4b3-f0d8-46be-97ef-419315ee3b47)

I guess you have the same issue than for Chrome installation in liveISO, see: https://github.com/linuxmint/mint22-beta/issues/72

**Comment by becker44a** [comment]
Testing Mint 22 in Virtualbox VM.  Vivaldi installed just fine there for me.  Migrated profile from host, vivaldi came up and operated under migrated profile w/ no issues.
Edit: Vivaldi 6.8.3381.46 / Chrome 126.0.6478.133, vivaldi-stable installed from Vivaldi's repository.

**Comment by haggen88** [comment]
installs but does not open the application

installed deb version:  vivaldi-stable_6.8.3381.46-1_amd64  - (live usb mode)

mint@mint:~$ vivaldi
[37719:37719:0707/174426.537581:FATAL:credentials.cc(127)] Check failed: . : Permission denied (13)
Trace/breakpoint trap (core dumped)


- report:     https://termbin.com/uado

when uninstalling from the cinnamon menu the following window appears:

![UNINSTALL](https://github.com/linuxmint/mint22-beta/assets/68134588/ad18191e-63df-45f1-ab21-952d401fb9a4)

**Comment by clefebvre** [comment]
Looks similar to https://github.com/linuxmint/mint22-beta/issues/72.

The live session isn't really made to install software. It has FS limitations, not a real user account and anything written to disk gets written to memory so you can't perform normal operations long-term.
