### ISSUE TITLE
Middle-click paste doesn't seem to work

### ISSUE THREAD

**Issue by whoami1i1i1i** [linuxmint/mint22-beta#96]
From my testing the middle-click paste function doesn't work regardless of whether it's turned on in mouse settings or not on mint 22 cinnamon.
It could be because of my hardware as I am using a USB extender for my mouse (basically a hub but it's one port).
I went on a website to check mouse input and it was detecting middle clicking just fine though.
Update: After further testing seems the middle click paste works in firefox and libreoffice, but it's only pasting whatever has been highlighted at any point, not from clipboard (in libreoffice it needs to be actively highlighted to paste, on firefox it only needs to have been highlighted).
Changing the middle click paste in system settings most likely doesn't affect them because their middle click paste seems to be separate from the system one; it's also connected (things highlighted in libreoffice will be pasted with middle-click into firefox and viceversa).

**Comment by mtwebster** [comment]
Middle-click paste isn't using the same 'clipboard' as when you right-click copy/paste or ctrl-c/v - this is normal behavior. It *only* pastes the current selection (theoretically from any app).

For most normal graphical applications (like Mint tools), the Mouse setting controls this behavior, but browsers can define their own behavior so there's no guarantee everything will work the same there.

**Comment by whoami1i1i1i** [comment]
> Middle-click paste isn't using the same 'clipboard' as when you right-click copy/paste or ctrl-c/v - this is normal behavior. It _only_ pastes the current selection (theoretically from any app).
> 
> For most normal graphical applications (like Mint tools), the Mouse setting controls this behavior, but browsers can define their own behavior so there's no guarantee everything will work the same there.

Oh, sorry for getting it wrong.
Still, the system setting doesn't seem to work on my end regardless of if I try pasting a selection or something from the clipboard.
I tested it in programs like xed and nemo which don't have separate middle-click paste behavior from the system.

**Comment by Harry-W-Haines-III** [comment]
Just a helpful comment.  The middle click paste is mostly beneficial for use in the terminal to quickly copy and paste commands.
