### ISSUE TITLE
 libgl1-mesa-glx not install for linux mint 22 beta

### ISSUE THREAD

**Issue by Hossam-Majrashi** [linuxmint/mint22-beta#97]
i can install linux mint 21.3

bet beta i didn't can install

`sudo dpkg -i CiscoPacketTracer822_amd64_signed.deb 
Selecting previously unselected package packettracer.
(Reading database ... 492609 files and directories currently installed.)
Preparing to unpack CiscoPacketTracer822_amd64_signed.deb ...
Unpacking packettracer (8.2.2) ...
dpkg: dependency problems prevent configuration of packettracer:
 packettracer depends on libgl1-mesa-glx; however:
  Package libgl1-mesa-glx is not installed.
 packettracer depends on libxcb-xinerama0-dev; however:
  Package libxcb-xinerama0-dev is not installed.

dpkg: error processing package packettracer (--install):
 dependency problems - leaving unconfigured
Processing triggers for gnome-icon-theme (3.12.0-5) ...
Processing triggers for shared-mime-info (2.4-4) ...
Errors were encountered while processing:
 packettracer
`

**Comment by Angedestenebres** [comment]
Hey :cat: 

According what I see, the package is only for Ubuntu 20.04 and 22.04 LTS. So I guess you will have to wait until they make a package for Ubuntu 24.04 LTS.

Anyway, from my point of view, this is not a Linux Mint issue but an Upstream one.
