### ISSUE TITLE
relnotes: Can't mount NTFS-formatted devices (volume is dirty and "force" flag is not set!)

### ISSUE THREAD

**Issue by MenthaSuaveolens** [linuxmint/mint22-beta#98]
I use 1TB usb external drives for backup. These devices are working ok on linux mint 21.3 (Cinnamon). On Cinnamon 22 I can't mount these volumes.

See dmesg-output below:

[  588.794842] usb 3-2: new high-speed USB device number 6 using xhci_hcd
[  588.921621] usb 3-2: New USB device found, idVendor=1058, idProduct=0748, bcdDevice=10.10
[  588.921638] usb 3-2: New USB device strings: Mfr=1, Product=2, SerialNumber=5
[  588.921645] usb 3-2: Product: My Passport 0748
[  588.921650] usb 3-2: Manufacturer: Western Digital
[  588.921655] usb 3-2: SerialNumber: 5758343145383143444B3730
[  588.924621] usb-storage 3-2:1.0: USB Mass Storage device detected
[  588.924881] scsi host7: usb-storage 3-2:1.0
[  589.952716] scsi 7:0:0:0: Direct-Access     WD       My Passport 0748 1010 PQ: 0 ANSI: 6
[  589.953264] scsi 7:0:0:1: Enclosure         WD       SES Device       1010 PQ: 0 ANSI: 6
[  589.955390] sd 7:0:0:0: Attached scsi generic sg3 type 0
[  589.955525] scsi 7:0:0:1: Attached scsi generic sg4 type 13
[  589.956477] sd 7:0:0:0: [sdc] Spinning up disk...
[  590.975895] ........ready
[  598.159934] sd 7:0:0:0: [sdc] 1953458176 512-byte logical blocks: (1.00 TB/931 GiB)
[  598.160642] sd 7:0:0:0: [sdc] Write Protect is off
[  598.160651] sd 7:0:0:0: [sdc] Mode Sense: 47 00 10 08
[  598.161066] sd 7:0:0:0: [sdc] No Caching mode page found
[  598.161077] sd 7:0:0:0: [sdc] Assuming drive cache: write through
[  598.163904]  sdc: sdc1
[  598.164039] sd 7:0:0:0: [sdc] Attached SCSI disk
[  598.171346] scsi 7:0:0:1: Wrong diagnostic page; asked for 1 got 8
[  598.171351] scsi 7:0:0:1: Failed to get diagnostic page 0x1
[  598.171354] scsi 7:0:0:1: Failed to bind enclosure -19
[  598.171368] ses 7:0:0:1: Attached Enclosure device
[  598.468951] ntfs3: Max link count 4000
[  598.468956] ntfs3: Enabled Linux POSIX ACLs support
[  598.468957] ntfs3: Read-only LZX/Xpress compression included
[  598.470132] ntfs3: sdc1: It is recommened to use chkdsk.
[  598.570266] ntfs3: sdc1: volume is dirty and "force" flag is not set!
[  628.051150] ntfs3: sdc1: It is recommened to use chkdsk.
[  628.349447] ntfs3: sdc1: volume is dirty and "force" flag is not set!

----
[  934.566073] usb 3-2: new high-speed USB device number 10 using xhci_hcd
[  934.694466] usb 3-2: New USB device found, idVendor=0bc2, idProduct=2323, bcdDevice= 0.00
[  934.694484] usb 3-2: New USB device strings: Mfr=2, Product=3, SerialNumber=1
[  934.694490] usb 3-2: Product: Expansion+
[  934.694496] usb 3-2: Manufacturer: Seagate
[  934.694500] usb 3-2: SerialNumber: NAAG35JR
[  934.701805] scsi host7: uas
[  934.702805] scsi 7:0:0:0: Direct-Access     Seagate  Expansion+       9300 PQ: 0 ANSI: 6
[  934.705456] sd 7:0:0:0: Attached scsi generic sg3 type 0
[  934.705879] sd 7:0:0:0: [sdc] Spinning up disk...
[  935.756122] ...ready
[  937.906017] sd 7:0:0:0: [sdc] 1953525167 512-byte logical blocks: (1.00 TB/932 GiB)
[  937.906369] sd 7:0:0:0: [sdc] Write Protect is off
[  937.906377] sd 7:0:0:0: [sdc] Mode Sense: 4f 00 00 00
[  937.906816] sd 7:0:0:0: [sdc] Write cache: enabled, read cache: enabled, doesn't support DPO or FUA
[  937.906947] sd 7:0:0:0: [sdc] Preferred minimum I/O size 512 bytes
[  937.906951] sd 7:0:0:0: [sdc] Optimal transfer size 33553920 bytes
[  937.918811]  sdc: sdc1
[  937.918919] sd 7:0:0:0: [sdc] Attached SCSI disk
[  938.175765] ntfs3: sdc1: It is recommened to use chkdsk.
[  938.249547] ntfs3: sdc1: volume is dirty and "force" flag is not set!
[  955.579388] ntfs3: sdc1: It is recommened to use chkdsk.
[  955.713793] ntfs3: sdc1: volume is dirty and "force" flag is not set!
[  974.103396] ntfs3: sdc1: It is recommened to use chkdsk.
[  974.162728] ntfs3: sdc1: volume is dirty and "force" flag is not set!

**Comment by Harry-W-Haines-III** [comment]
@MenthaSuaveolens Just to check things out.  Could you try this from a live boot of Ubuntu 24.04?  This looks like an upstream regression.  Let's see if we can rule that out.

**Comment by MenthaSuaveolens** [comment]
I have the same problem when booting with the Ubuntu 23.10 stick.

  170.720831] usb 1-1.3.4: new high-speed USB device number 6 using ehci-pci
[  170.830740] usb 1-1.3.4: New USB device found, idVendor=1058, idProduct=0748, bcdDevice=10.10
[  170.830751] usb 1-1.3.4: New USB device strings: Mfr=1, Product=2, SerialNumber=5
[  170.830755] usb 1-1.3.4: Product: My Passport 0748
[  170.830757] usb 1-1.3.4: Manufacturer: Western Digital
[  170.830760] usb 1-1.3.4: SerialNumber: 5758343145383143444B3730
[  170.831642] usb-storage 1-1.3.4:1.0: USB Mass Storage device detected
[  170.831970] scsi host6: usb-storage 1-1.3.4:1.0
[  171.838614] scsi 6:0:0:0: Direct-Access     WD       My Passport 0748 1010 PQ: 0 ANSI: 6
[  171.839862] scsi 6:0:0:1: Enclosure         WD       SES Device       1010 PQ: 0 ANSI: 6
[  178.855278] sd 6:0:0:0: Attached scsi generic sg3 type 0
[  178.855508] scsi 6:0:0:1: Attached scsi generic sg4 type 13
[  178.855894] sd 6:0:0:0: [sdd] 1953458176 512-byte logical blocks: (1.00 TB/931 GiB)
[  178.856903] sd 6:0:0:0: [sdd] Write Protect is off
[  178.856911] sd 6:0:0:0: [sdd] Mode Sense: 47 00 10 08
[  178.858510] sd 6:0:0:0: [sdd] No Caching mode page found
[  178.858515] sd 6:0:0:0: [sdd] Assuming drive cache: write through
[  178.871402]  sdd: sdd1
[  178.871589] sd 6:0:0:0: [sdd] Attached SCSI disk
[  178.983488] scsi 6:0:0:1: Wrong diagnostic page; asked for 1 got 8
[  178.983496] scsi 6:0:0:1: Failed to get diagnostic page 0x1
[  178.983498] scsi 6:0:0:1: Failed to bind enclosure -19
[  178.983532] ses 6:0:0:1: Attached Enclosure device
[  302.889735] ntfs3: Max link count 4000
[  302.889741] ntfs3: Enabled Linux POSIX ACLs support
[  302.889742] ntfs3: Read-only LZX/Xpress compression included
[  303.188894] ntfs3: sdd1: It is recommened to use chkdsk.
[  303.288140] ntfs3: sdd1: volume is dirty and "force" flag is not set!
![Screenshot from 2024-07-06 09-38-52](https://github.com/linuxmint/mint22-beta/assets/47174957/b44cb0c5-0f90-4542-8e31-42a7a41668e3)

**Comment by Harry-W-Haines-III** [comment]
Here is something I found about the issue.  Some recommend turning off fast boot in Windows with the drive under Windows and also the command "sudo ntfsfix -d /dev/sda1"
'fixed this temporarily on my USB key until I plug it in again'

https://bugs.launchpad.net/ubuntu/+source/ntfs-3g/+bug/2062972
and some other information here: https://github.com/tuxera/ntfs-3g/issues/108
and here https://askubuntu.com/questions/1514663/i-cant-open-ntfs-external-hdd-mounting-error/1517948

Maybe some other with NTFS drives can post their observations.

**Comment by MenthaSuaveolens** [comment]
The issue can be easily fixed by opening the app disks and selecting the option "repair filesystem". After that the disk can be properly mounted. The issue applies only to NTFS-formatted drives. I presume we can close this bug?

An ext4-formatted drive is automatically mounted (see below)

[   67.952424] usb 4-2: new SuperSpeed USB device number 2 using xhci_hcd
[   67.971680] usb 4-2: New USB device found, idVendor=174c, idProduct=5106, bcdDevice=80.00
[   67.971698] usb 4-2: New USB device strings: Mfr=2, Product=3, SerialNumber=1
[   67.971705] usb 4-2: Product: StoreJet Transcend
[   67.971711] usb 4-2: Manufacturer: StoreJet Transcend
[   67.971716] usb 4-2: SerialNumber: S2S6J9BCA09006      
[   67.974049] usb-storage 4-2:1.0: USB Mass Storage device detected
[   67.974414] scsi host7: usb-storage 4-2:1.0
[   69.005862] scsi 7:0:0:0: Direct-Access     StoreJet Transcend        0    PQ: 0 ANSI: 6
[   69.006363] sd 7:0:0:0: Attached scsi generic sg3 type 0
[   69.036621] sd 7:0:0:0: [sdc] 1953525168 512-byte logical blocks: (1.00 TB/932 GiB)
[   69.036932] sd 7:0:0:0: [sdc] Write Protect is off
[   69.036934] sd 7:0:0:0: [sdc] Mode Sense: 43 00 00 00
[   69.037200] sd 7:0:0:0: [sdc] Write cache: enabled, read cache: enabled, doesn't support DPO or FUA
[   69.039379]  sdc: sdc1
[   69.039525] sd 7:0:0:0: [sdc] Attached SCSI disk
[   69.639433] EXT4-fs (sdc1): mounted filesystem 571f3e4f-ae2c-4d93-a38f-4446b06c1e33 r/w with ordered data mode. Quota mode: none.

FAT-formatted drives are also automatically mounted (but there is a warning that the device might be corrupt)

[ 1077.256698] usb 3-12: new high-speed USB device number 7 using xhci_hcd
[ 1077.398662] usb 3-12: New USB device found, idVendor=0718, idProduct=0619, bcdDevice= 1.00
[ 1077.398680] usb 3-12: New USB device strings: Mfr=1, Product=2, SerialNumber=3
[ 1077.398687] usb 3-12: Product: TF10
[ 1077.398692] usb 3-12: Manufacturer: TDK LoR
[ 1077.398696] usb 3-12: SerialNumber: 07034270574E2498
[ 1077.400832] usb-storage 3-12:1.0: USB Mass Storage device detected
[ 1077.401138] scsi host7: usb-storage 3-12:1.0
[ 1078.418964] scsi 7:0:0:0: Direct-Access     TDK LoR  TF10             PMAP PQ: 0 ANSI: 4
[ 1078.419548] sd 7:0:0:0: Attached scsi generic sg3 type 0
[ 1082.513402] sd 7:0:0:0: [sdc] 120913920 512-byte logical blocks: (61.9 GB/57.7 GiB)
[ 1082.516216] sd 7:0:0:0: [sdc] Write Protect is off
[ 1082.516228] sd 7:0:0:0: [sdc] Mode Sense: 23 00 00 00
[ 1082.518069] sd 7:0:0:0: [sdc] No Caching mode page found
[ 1082.518079] sd 7:0:0:0: [sdc] Assuming drive cache: write through
[ 1082.534197]  sdc: sdc1
[ 1082.534519] sd 7:0:0:0: [sdc] Attached SCSI removable disk
[ 1087.405063] FAT-fs (sdc1): Volume was not properly unmounted. Some data may be corrupt. Please run fsck.

**Comment by clefebvre** [comment]
I'll add a note in the release notes for this.

**Comment by clefebvre** [comment]
Done.
