### ISSUE TITLE
relnotes: Detail how to switch back to PA

### ISSUE THREAD

**Issue by brothergc** [linuxmint/mint22-beta#99]
I installed this , however the sound does not work well . it is tinny and weak . so I uninstalled pipewire and installed pulseaudio and works just fine now . My sound is a realtek ALC 4080 usb  on a asus motherboard
 May I strongly suggest staying with pusleaudio or at least give one the option to choose which sound server to install 
EDIT: just to add that this issue is not just related to Mint , but  to pipewire . tried some other distros and the same proplem with pipewire . IMO pipewire is not ready for primetime

**Comment by LinuxOnTheDesktop** [comment]
I suggest that you rename your post - please give it an informative title.

**Comment by clefebvre** [comment]
@brothergc can you detail the steps you took to switch back to PA? We might add that to the release notes for people with similar issues.

**Comment by brothergc** [comment]
in reply to clefbvre:
  Uninstalling pipewire  thru the package synaptic manager then I selected all the pulseaudio files I needed simple as that . :)

**Comment by ewangi** [comment]
> in reply to clefbvre: Uninstalling pipewire thru the package synaptic manager then I selected all the pulseaudio files I needed simple as that . :)

Which files were those?

**Comment by clefebvre** [comment]
Info added to the release notes.
